### ISSUE TITLE
abcls crash due to negative string length

### ISSUE THREAD

**Issue by nyue** [alembic/alembic#101]
Hi,

  In AbcLs.cpp, the printChild() method, they way string length is calculated for the creation of the spacing character will in sum situation resulting in the creation of negative string length and for unsigned value that would be bad.

  It is currently happening for an alembic file I tried to run abcls on

  Interestingly, "abcls -lar" is fine but "abcls -lr" is not because the -a option seems to translate to the "all" parameter being initialized to true

`//-*****************************************************************************
void printChild( AbcG::IObject iParent, AbcG::IObject iObj,
                 bool all = false, bool long_list = false, bool meta = false,
                 bool values = false )
{

    AbcA::MetaData md = iObj.getMetaData();

    if ( long_list ) {
        std::string schema = md.get( "schema" );
        std::cout << "START(" << schema << ")END" << std::endl;
        int spacing = COL_1;
        if ( all )
            spacing = COL_1 + COL_2;
        std::cout << "SPACING START(" << spacing << ") SPACING END" << std::endl;
        std::cout << "schema.length() START(" << schema.length() << ") schema.length() END" << std::endl;
        std::cout << schema << std::string(spacing - schema.length(), ' ');
    }
    std::cout << GREENCOLOR << iObj.getName();

    if ( meta )
         printMetaData( md, all, long_list );

    std::cout << RESETCOLOR;

    if ( long_list )
        std::cout << std::endl;
    else
        std::cout << "   ";
}`

Cheers

**Comment by rsgalloway** [comment]
Sounds like we could solve this by adding a max, yeah?

`std::string(std::max(0, spacing - schema.length()), ' ')`

**Comment by lamiller0** [comment]
Released in 1.7.1
