### ISSUE TITLE
Requested revision overlaps with other requested revisions

### ISSUE THREAD

**Issue by kizniche** [alembic/alembic#103]
Hello,

I've been using alembic to upgrade a database for a project of mine, [Mycodo](https://github.com/kizniche/Mycodo). It's a generic [single SQLite3 database configuration](https://github.com/kizniche/Mycodo/tree/b6cb3feb04abaf74ec756a81603089009e847e5d/databases/alembic). There is normally a database, 'mycodo.db' in that directory that is upgraded with the command '[alembic upgrade head](https://github.com/kizniche/Mycodo/blob/b6cb3feb04abaf74ec756a81603089009e847e5d/mycodo/scripts/upgrade_post.sh#L57-L58)' that is executed as a part of the upgrade script.

This has been working great for a long time, up until recently. I'm not exactly sure what I've done, if anything, to cause this (although I have been making significant changes to the Mycodo framework), but I'm receiving the following error when attempting to upgrade through the upgrade script:

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.util.messaging] Requested revision e4f984cd01d4 overlaps with other requested revisions 6a5508a5f078
FAILED: Requested revision e4f984cd01d4 overlaps with other requested revisions 6a5508a5f078

Interestingly, the changes from the upgrade script don't apply to the database, but after the error, there are two entries for the column version_num in the table alembic_verision, one for e4f984cd01d4 and one for 6a5508a5f078.

Any help in understanding this error would be great. Search results haven't been helpful in figuring this out.

Many thanks,
Kyle

**Comment by kizniche** [comment]
Additionally, I'm not sure if this was responsible for the issue in any way, but it's worth mentioning. I recently found that in my upgrade system, there were two places where the database was upgraded to head, although I know from manual upgrades that if it's already at head, nothing is changed. The error above occurs at the second upgrade command. [This](https://github.com/kizniche/Mycodo/blob/db4bef61be1755c5a981ce9ba3f6d032a8f069a9/mycodo/scripts/upgrade_mycodo_release.sh#L103-L108) was the first upgrade command.

**Comment by VyacheslavHashov** [comment]
I assume that you need https://bitbucket.org/zzzeek/alembic. This repository is for http://alembic.io/ project.

**Comment by kizniche** [comment]
Wow, what an idiot I am. Sorry for the oversight.
