### ISSUE TITLE
alembic fails to link to hdf5 1.10.0

### ISSUE THREAD

**Issue by iMichka** [alembic/alembic#104]
Hi

I am one of the maintainers of the homebrew package manager. We distribute alembic, and are currently preparing to update hdf5 to version 1.10.0-patch1.

Alembic 1.7.0 does not link against this version of hdf5 (tested on OS X Sierra).
Here is the relevant error (with the full log):
https://gist.github.com/iMichka/ba828c7e284b15cc9c63cb0d94fd81c6#file-02-make-L268-L456

It would be great if somebody could have a look at this. Thanks in advance.

**Comment by lamiller0** [comment]
The errors look to be related to how you have HDF5 1.10 configured?
I'm seeing a lot of complaints about MPI which Alembic is not using directly.

You could also drop HDF5 support as it is now an optional dependency.

**Comment by iMichka** [comment]
Right, I recompiled HDF5 without MPI, and it worked.

Now it compiles up to the end. Then the test suite is run, and one test is failing:
```
16/62 Testing: AbcCoreHDF5_ArchiveTESTS
16/62 Test: AbcCoreHDF5_ArchiveTESTS
Command: "/tmp/alembic-20170202-99756-1a8elcl/alembic-1.7.0/lib/Alembic/AbcCoreHDF5/Tests/AbcCoreHDF5_ArchiveTests"
Directory: /tmp/alembic-20170202-99756-1a8elcl/alembic-1.7.0/lib/Alembic/AbcCoreHDF5/Tests
"AbcCoreHDF5_ArchiveTESTS" start time: Feb 02 22:20 CET
Output:
----------------------------------------------------------
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: ERROR: Failed Throw in File: /tmp/alembic-20170202-99756-1a8elcl/alembic-1.7.0/lib/Alembic/AbcCoreHDF5/Tests/ArchiveTests.cpp Line: 93
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"AbcCoreHDF5_ArchiveTESTS" end time: Feb 02 22:20 CET
"AbcCoreHDF5_ArchiveTESTS" time elapsed: 00:00:00
----------------------------------------------------------
```

I can remove the hdf5 option, but maybe some users will still maybe want build it with the HDF5 option? Or is it not needed at all?

**Comment by lamiller0** [comment]
Hmmmm, interesting, this one is fairly harmless to ignore if the rest of the HDF5 tests are passing.

Some users may need it if they have very old assets that they haven't converted over, but in that case couldn't they fall back on an earlier homebrew?

**Comment by iMichka** [comment]
So basically HDF5 was the old file format, and hdf5 is only needed in 1.7.0 if you want to convert your old files to the new one?

What I can do is remove the "make test" step, so that everything builds. We can then ship 1.7.0 with HDF5, I'll make a note that we can drop it completely in the next version. Would that be OK for you?

**Comment by lamiller0** [comment]
Yes, that sounds good.

**Comment by iMichka** [comment]
Thank you for the fast answer. I will make sure the package is updated accordingly.
