### ISSUE TITLE
auto generate not working for postgres JSONB

### ISSUE THREAD

**Issue by pvanderlinden** [alembic/alembic#112]
When I auto generate a migration for a model with a jsonb field i get the following error:
```
    sa.Column('data', postgresql.JSONB(astext_type=Text()), nullable=True),
NameError: name 'Text' is not defined
```
This is with version alembic `0.8.10` and sqlalchemy `1.1.5`, it used to work, and would not add the `astext_type=Text()` (in version alembic `0.8.9` and sqlalchmey `1.0.15`).

**Comment by lamiller0** [comment]
I think this is where you want to put this issue:
https://bitbucket.org/zzzeek/alembic/issues?status=new&status=open
