### ISSUE TITLE
Why is IObject::instanceSourcePath() not const?

### ISSUE THREAD

**Issue by sybrenstuvel** [alembic/alembic#114]
The member function [IObject::instanceSourcePath()](https://github.com/alembic/alembic/blob/master/lib/Alembic/Abc/IObject.h#L226) is declared as non-const. However, from the description it doesn't seem to actually modify the `IObject`. Looking at [its implementation](https://github.com/alembic/alembic/blob/master/lib/Alembic/Abc/IObject.cpp#L464) it doesn't do much more than possibly create some shared pointers and read some data; nothing seems to modify the object state.

Couldn't it be a `const` function instead?

**Comment by lamiller0** [comment]
Yes, this looks like it can be const.

**Comment by lamiller0** [comment]
Released in 1.7.1
