### ISSUE TITLE
AbcExport : -autoSubd disable ability to write multiuvs -writeUVSets

### ISSUE THREAD

**Issue by nyue** [alembic/alembic#116]
Just writing UV sets
AbcExport -verbose -j "-frameRange 1001 1025 -noNormals -ro -stripNamespaces -uvWrite -writeColorSets -writeUVSets -writeFaceSets -wholeFrameGeo -worldSpace -writeVisibility -eulerFilter -dataFormat ogawa -root |pCube1 -file C:/Users/nyue/Documents/maya/projects/default/cache/alembic/AbcExport_writeUVSets.abc";

Writing UV sets together with creases information
AbcExport -verbose -j "-frameRange 1001 1025 -noNormals -ro -stripNamespaces -autoSubd -uvWrite -writeColorSets -writeUVSets -writeFaceSets -wholeFrameGeo -worldSpace -writeVisibility -eulerFilter -dataFormat ogawa -root |pCube1 -file C:/Users/nyue/Documents/maya/projects/default/cache/alembic/AbcExport_autoSubd_writeUVSets.abc";

The exported file AbcExport_autoSubd_writeUVSets.abc has the creases information but will loose the multiple UV sets that was present in the maya mesh.

Anyone encounter this problem?

**Comment by lamiller0** [comment]
Released in 1.7.1
