### ISSUE TITLE
compile parameter error for support HDF5 and without install HDF5

### ISSUE THREAD

**Issue by jiexiajoy** [alembic/alembic#117]
cmake compile parameter for support HDF5 should be -DHDF5_ROOT=...
-DHDF_ROOT will report error

AlembicHDF5.cmake

IF (DEFINED HDF5_ROOT)
    MESSAGE(STATUS "Using HDF5_ROOT: ${HDF5_ROOT}")
    # set HDF5_ROOT in the env so FindHDF5.cmake can find it
    SET(ENV{HDF5_ROOT} ${HDF5_ROOT})
ENDIF()

and this version is not support after hdf5-1.8.9

**Comment by lamiller0** [comment]
The error you get from -DHDF_ROOT appears to be a standard CMake error.  You have to specify it like that for all those variables.

**Comment by jiexiajoy** [comment]
yeha,i fellow readme.txt and take a afternoon to solve the error 
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
