### ISSUE TITLE
Can Ogawa use pread instead of streams for input? 

### ISSUE THREAD

**Issue by spiffmon** [alembic/alembic#124]
The requirement of needing to pre-allocate as many streams as you expect to have threads simultaneously accessing data from an Ogawa archive is tricky in scenarios where you expect to provide lazy access to the data, and therefore are keeping the archive open indefinitely; further, it consumes many file descriptors.  This causes poor alembic streaming performance when consumed in USD compositions, for example, because we try to be conservative wrt file-descriptor consumption, and therefore only allocate the default single stream when opening an archive.

pread is well supported on linux, OSX and Windows, and its use would eliminate the need for any locking in the Ogawa read-path, simplify client code, and may simplify the code a bit, also. 

Thanks for reading,
--spiff

**Comment by lamiller0** [comment]
Oh wow, is pread well supported on Windows?  If so, I didn't realize that.

Did you notice any difference in read performance on a single thread?

I don't know if I would want to totally remove the stream interface, instead the constructor that takes the filename could internally use a stream-like interface that uses pread.

**Comment by spiffmon** [comment]
Hey Lucas - totally busted!  I was a little too glib there, and should have stated "pread equivalent".  We actually wrap pread like so: https://github.com/PixarAnimationStudios/USD/blob/2f1494e43e430d7f4187968fd6888d49ade3be80/pxr/base/lib/arch/fileSystem.cpp#L492

Not too bad?

**Comment by spiffmon** [comment]
To your question about performance: we never compared pread directly to streams or any other filesystem call; we only compare to direct mmapping.  At the granularity of data requests we make in usdc, which I think is roughly the same as Ogawa, we have measured pread as about 10% slower, which we attribute to the system call overhead of pread (which streams share, I believe), vs a memcpy in the mmap case.

**Comment by lamiller0** [comment]
First pass is here:
https://github.com/lamiller0/alembic/commit/f28a47dd2331ab4eea7ad68090042f4637d1ef54

Thanks for pointing this out, I'm measuring a very interesting speed increase with some of my production data.

**Comment by lamiller0** [comment]
This made it into 1.7.2

**Comment by meshula** [comment]
@lamiller0 Any theories as to why you have a speed increase?

**Comment by lamiller0** [comment]
I haven't looked at a diff between strace logs, but I suspect the extra seekg calls were doing more work than I would have guessed.  Same guess could be applied to whatever the default ifstream::read call is doing.

**Comment by meshula** [comment]
Plausible!
