### ISSUE TITLE
[cmake] some minor problems in cmake

### ISSUE THREAD

**Issue by simogasp** [alembic/alembic#127]
Hi @lamiller0 

Here are few minor issues concerning the cmake:

* `Foundation.h` from AbcCoreLayer is not installed, yet `Util.h`, which is installed, explicitly includes it. This will end up in a compiling error whenever Util.h is included in a third party application. So it must be added to the list of the headers to install.

* This is just nitpicking: the message `MESSAGE(STATUS "Skipping AbcDiff and AbcConvert: requires USE_HDF5")` should just read `"Skipping AbcConvert: requires USE_HDF5"` as AbcDiff is not anymore dependent of hdf5.

* I think C++11 (or more) is mandatory to build the library. If it is the case and I'm not wrong then:
  * when checking for c++11 or c++0z, an error should be thrown if neither of the two are supported.
  * we should enforce c++11 when alembic is used as 3rd party IF the headers contain c++11 code (i have to check that, you maybe can tell me). If it is the case, the only way that I know to enforce c++11 in another project is to add a line to the `AlembicConfig.cmake.in`: the proper way would be to add `set_target_properties(Alembic::Alembic PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED ON)` but this requires cmake > 3.0, otherwise the classic `SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`

As I said in #126, i can address these problems in a PR.

Simone

**Comment by lamiller0** [comment]
C++11 is not mandatory.

**Comment by simogasp** [comment]
if I manually disable the c++11 flag i get this error (on osx with clang 3.9)
```
alembic/lib/Alembic/AbcCoreHDF5/CprData.cpp:208:38: error: use of overloaded operator '==' is ambiguous (with operand types 'PropertyHeaderPtr'
      (aka 'shared_ptr<AbcA::PropertyHeader>') and 'long')
    if ( m_propertyHeaders[i].header == NULL )
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
/usr/local/Cellar/llvm@3.9/3.9.1_1/bin/../include/c++/v1/memory:4922:1: note: candidate function [with _Tp = Alembic::AbcCoreAbstract::v10::PropertyHeader]
operator==(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
alembic/libAlembic/Util/PlainOldDataType.h:116:13: note: candidate function
inline bool operator==( bool a, const bool_t &b )
            ^
alembic/lib/Alembic/AbcCoreHDF5/CprData.cpp:208:38: note: built-in candidate operator==(int, long)
    if ( m_propertyHeaders[i].header == NULL )
                                     ^
alembic/lib/Alembic/AbcCoreHDF5/CprData.cpp:208:38: note: built-in candidate operator==(unsigned __int128, long)
alembic/lib/Alembic/AbcCoreHDF5/CprData.cpp:208:38: note: built-in candidate operator==(unsigned long long, long)
alembic/lib/Alembic/AbcCoreHDF5/CprData.cpp:208:38: note: built-in candidate operator==(unsigned long, long)
alembic/lib/Alembic/AbcCoreHDF5/CprData.cpp:208:38: note: built-in candidate operator==(unsigned int, long)
etc etc
```
I'll try on other systems to see I i get the same error

**Comment by lamiller0** [comment]
If you aren't using C++11 then you either need to use C++0x or boost.

**Comment by simogasp** [comment]
What i meant is that you need to have either C++11 or C++0x (or boost) to be able to build the library, but also you need one of those standards set if you want to build an app that depends on alembic. 
I just made a stupid test, with simple hello world example in which i include all the headers of alembic. It compiles only with the C++11 flag, otherwise I get the above error (meaning that also the API headers of alembic needs either C++11 or C++0x).

**Comment by simogasp** [comment]
Concretely, what i mean is that we should add these lines to `AlembicConfig.cmake.in` exactly as done in the main CMakeLists:
```cmake
...
SET(Alembic_USES_BOOST @ALEMBIC_LIB_USES_BOOST@)
if(@ALEMBIC_LIB_USES_TR1@ AND NOT @ALEMBIC_LIB_USES_BOOST@)
    SET(Alembic_USES_TR1 TRUE)
else()
    SET(Alembic_USES_TR1 FALSE)
endif()

# add this part: if it is not built with boost and tr1 then check if the compiler support at least 11 or 0x
IF (NOT ${Alembic_USES_TR1} AND NOT ${Alembic_USES_BOOST})
    # TODO figure out how to do this for Windows
    INCLUDE(CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
    CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
    IF (COMPILER_SUPPORTS_CXX11)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    ELSEIF (COMPILER_SUPPORTS_CXX0X)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
    ENDIF()
ENDIF()
```
With this I can import alembic into a 3rd project and force the proper standard if i didn't compile it with boost. Of course, it's not a big deal, you can always enforce it from the cmake of your project.

What do you think?

**Comment by simogasp** [comment]
A more elegant way to do that would be to add
```cmake
target_compile_options(Alembic PUBLIC -std=c++11) #or 0x
```
in the relevant CMakeLists
