### ISSUE TITLE
Specify key length for UNIQUE constraints

### ISSUE THREAD

**Issue by jenstroeger** [alembic/alembic#130]
Looking at [the latest docs](http://alembic.zzzcomputing.com/en/latest/ops.html#alembic.operations.Operations.create_unique_constraint) it seems that I can not specify a `UNIQUE` constraint with a key length that would translate into the following SQL statement:
```sql
ALTER TABLE table ADD UNIQUE (column(128));
```
Here, the `128` would be the length or index into the `BLOB` which would be checked for uniqueness.

In my particular case, `column` is a [MySQL `BLOB`](https://dev.mysql.com/doc/refman/5.7/en/blob.html) type, and in order for `BLOB` and `TEXT` types to handle uniqueness, the [length of the key needs to be specified](https://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length#1827099).

It would be good to call
```python
from alembic import op
import sqlalchemy as sa

op.create_unique_constraint("uq_table_column", "table", ["column"], key_lengths=[128])
```
in such situations. I’m somewhat undecided how this would translate to the [`Column`](http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.Column) constructor, perhaps:
```python
op.add_column("table", sa.Column("column", sa.LargeBinary(), nullable=True, unique=True, unique_key_length=128))
```

**Comment by sideband** [comment]
Hi Jens,
    I think you're looking for alembic the database migration tool, not
alembic the visual effects file format, which is this list. Good luck with
your issue!

**Comment by jenstroeger** [comment]
Indeed.
