### ISSUE TITLE
What is the problem with ENUM type?

### ISSUE THREAD

**Issue by ffreitasit** [alembic/alembic#133]
What is the problem with ENUM type?

Once I have an enum column on my database, everything I try to change on that column is IGNORED!
EVEN CHANGE FROM ENUM TO SOMETHING ELSE!

**Comment by lamiller0** [comment]
This is the wrong Alembic project, the one I think you want is here:

http://www.sqlalchemy.org/

**Comment by ffreitasit** [comment]
@lamiller0 
NO.. ITS THE CORRECT PROJECT:
<img width="1306" alt="screen shot 2017-07-21 at 17 33 18" src="https://user-images.githubusercontent.com/184118/28481318-da4e0da6-6e3a-11e7-94df-a80e4db18722.png">
<img width="566" alt="screen shot 2017-07-21 at 17 33 25" src="https://user-images.githubusercontent.com/184118/28481324-dfb729da-6e3a-11e7-83ce-bf9efa4fd617.png">

**Comment by lamiller0** [comment]
Issues for this project are for:

Alembic is an open framework for storing and sharing scene data that includes a C++ library, a file format, and client plugins and applications. http://alembic.io/

Have a nice day.
