### ISSUE TITLE
Window VS2015 Issue

### ISSUE THREAD

**Issue by ArthurChiu** [alembic/alembic#134]
When I get the Alembic.sln，error will appear：  c2668  “boost::get_pointer”:ambiguous call to overloaded function, how can i solver this problem

**Comment by lamiller0** [comment]
Is this for the python bindings?

**Comment by lamiller0** [comment]
Can you try it with 1.7.2?  I know we've addressed an issue like this in the past.

**Comment by ArthurChiu** [comment]
i have been try with 1.7.0,also like this, i don't know it my msvc Configuration problem or other things

**Comment by ArthurChiu** [comment]
I use boost 1.61,

**Comment by lamiller0** [comment]
It might be a configuration issue as I've seen this happen when the python bindings get confused between boost::shared_ptr and std::shared_ptr.  What are you passing into CMake?

**Comment by ArthurChiu** [comment]
cmake -DILMBASE_ROOT=D:\Library\Devkit\libs\ilmbase\2.2.0 -DZLIB_ROOT=D:\Library\Devkit\libs\zlib\1.2.8 -DUSE_HDF5=ON -DHDF5_ROOT=D:\Library\Devkit\libs\hdf5\1.8.17 -DUSE_STATIC_HDF5=ON -DALEMBIC_LIB_USES_TR1=ON -DALEMBIC_ILMBASE_LINK_STATIC=ON -DUSE_STATIC_BOOST=ON -DALEMBIC_LIB_USES_BOOST=ON -DBOOST_ROOT=D:\Library\Devkit\libs\Boost\1.61.0 -DUSE_PYALEMBIC=ON -DPYILMBASE_ROOT=D:\Library\Devkit\libs\pyilmbase\2.2.0 -DUSE_EXAMPLES=ON -DUSE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=D:\Library\Devkit\libs\alembic\1.6.1 -G "Visual Studio 14 2015 Win64" ..\alembic-1.6.1

**Comment by lamiller0** [comment]
Don't set these:
ALEMBIC_LIB_USES_TR1
ALEMBIC_LIB_USES_BOOST

Or explicitly set to off:
-DALEMBIC_LIB_USES_TR1=OFF
-DALEMBIC_LIB_USES_BOOST=OFF

**Comment by ArthurChiu** [comment]
Ok:
I will try this
Thanks!

**Comment by ArthurChiu** [comment]
New Error
error MSB3073: 命令“setlocal
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd”已退出，代码为 1。

**Comment by ArthurChiu** [comment]
CMake Error at python/PyAlembic/cmake_install.cmake:46 (file):
12>    file INSTALL cannot find
12>    "D:/Library/Devkit/compile/Alembic/alembic-1.6.1/python/PyAlembic/Release/alembicmodule.so".

**Comment by ArthurChiu** [comment]
maybe not create alembicmodule.so

**Comment by ArthurChiu** [comment]
alembicmodule have so much problem

**Comment by ArthurChiu** [comment]
Boost is the using BOOST_DYN_LINK?

**Comment by ArthurChiu** [comment]
LINK1104 cannot open file boost_python_vc140-mt-1_61.lib
