### ISSUE TITLE
Visual Studio bug with HDF5 in Alembic 1.7.2

### ISSUE THREAD

**Issue by tyanalunas** [alembic/alembic#135]
IFactory::getArchive() does this bit where it tries to open every file as Ogawa first, and if that fails it goes to HDF5:
https://github.com/alembic/alembic/blob/master/lib/Alembic/AbcCoreFactory/IFactory.cpp#L68

If a non-Ogawa (HDF5) file is detected, IStreams will close the file here:
https://github.com/alembic/alembic/blob/master/lib/Alembic/Ogawa/IStreams.cpp#L254

The bug is that IStreams will also try to close the file again in its destructor:
https://github.com/alembic/alembic/blob/master/lib/Alembic/Ogawa/IStreams.cpp#L225

This could be fixed by either removing one of the CLOSEFILE calls or setting the fid to -1 when a failure is caught. I commented out the the CLOSEFILE on IStreams.cpp line 254 and it seems to work fine.

This bug was tested in Visual Studio 2012, though it probably happens with other msvc compilers.

**Comment by lamiller0** [comment]
Fixed in 1.7.3
