### ISSUE TITLE
AbcImport.mll using alembic 1.7.3

### ISSUE THREAD

**Issue by dnx4015** [alembic/alembic#139]
I compiled alembic 1.7.3 and when loading the plugins for maya I get the following error:
```python
// Error: line 1: Unable to dynamically load : C:/Program Files/Maya2016/bin/plug-ins/AbcImport.mll
The specified procedure could not be found.
 // 
# Error: pymel : Failed to get controlCommand list from AbcImport # 
# Error: pymel : Failed to get modelEditorCommand list from AbcImport # 
# Error: pymel : Failed to get command list from AbcImport # 
# Error: pymel : Failed to get constraintCommand list from AbcImport # 
# Error: pymel.core : Failed to get depend nodes list from AbcImport # 
// Error: line 1: The specified procedure could not be found.
 (AbcImport) // 
```

I run depends and no missing library seems to be missing. It seems like the definitions are not found in time.

**Comment by lamiller0** [comment]
What compiler were you using, and just to double check, you were using Maya 2016?  (not something like trying to load a Maya 2016 plugin into Maya 2018, etc)

**Comment by adriankrupa** [comment]
Add paths to alembics lib directory (with Alembic.dll) and to ilmbase/lib directory to your "PATH"
