### ISSUE TITLE
Setup.cfg: Migrate to/or support [python] config best practices

### ISSUE THREAD

**Issue by kmcminn** [alembic/alembic#144]
Since multiple tools can be controlled via directives in a setup.cfg for python repos (e.g. linting, test harnesses), it would very handy to be able to move all my alembic config directives there and perhaps collapse the logging directives in a reasonable way so as to distinguish them from other directives.

I'm aware that I can run alembic <command> --config setup.cfg, but the probability of user errors for this workflow is not None and thus not a reasonable design.

What do you fine people think?

**Comment by lamiller0** [comment]
Hmmmmm, I think you have the wrong project.

Do you mean this one?

http://alembic.zzzcomputing.com/en/latest/

**Comment by kmcminn** [comment]
apologies, thank you.
