### ISSUE TITLE
default Twitter card, plus Twitter share button does not include link

### ISSUE THREAD

**Issue by SimonEnsemble** [alembic/alembic#149]
A Twitter card when sharing a post does not display an image, e.g.:

https://twitter.com/CoryMSimon/status/947217511174496256

What is the best way to e.g. use the site logo as an image for a Twitter card in the Alembic theme?

Also, the Twitter share button, when clicked on the post, does not include the link to the post.

Thanks, awesome theme!

**Comment by adriankrupa** [comment]
Hey,
That's not repo with alembic theme.
I think you wanted post it there: https://github.com/daviddarnes/alembic
