### ISSUE TITLE
New ENUM not generated correctly

### ISSUE THREAD

**Issue by rachel-md** [alembic/alembic#161]
When creating a new ENUM, it is not generated correctly. They have to be manually created and dropped. We have many migrations in the past that have worked without a problem so we're not sure why this one failed. Here's the [StackOverflow](https://stackoverflow.com/questions/37848815/sqlalchemy-postgresql-enum-does-not-create-type-on-db-migrate) that resolved the issue for us.

Error:
```bash
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) type "colors" does not exist
LINE 1: ALTER TABLE app_example ADD COLUMN colors colors
                                                     ^
 [SQL: 'ALTER TABLE app_example ADD COLUMN colors colors']
```
[gist of entire traceback](https://gist.github.com/rachel-md/77519f9134b7a00b9fb3d7891a9b6316)

Here's what's generated:
``` python
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_example', sa.Column('colors', sa.Enum('RED', 'GREEN, 'BLUE, 'PURPLE', name='colors'), nullable=True))
    # ### end Alembic commands ###
```

Here's what works:
``` python
def upgrade():
    colors = postgresql.ENUM('RED', 'GREEN, 'BLUE, 'PURPLE', name='colors')
    colors.create(op.get_bind())

    op.add_column('app_example', sa.Column('colors', sa.Enum('RED', 'GREEN, 'BLUE, 'PURPLE', name='colors'), nullable=True))
```

**Comment by lamiller0** [comment]
I think the Alembic project you want is here:
https://bitbucket.org/zzzeek/alembic

**Comment by rachel-md** [comment]
So sorry about the confusion @lamiller0. Thanks for pointing me in the right direction.
