### ISSUE TITLE
OPolyMeshTest (basic example on using Alembic) crashes in Debug build VS2017

### ISSUE THREAD

**Issue by eddiz** [alembic/alembic#170]
Hi, 

while trying to write my own Alembic Exporter, I have discovered that the OPolyMeshTest crashes in Debug mode with Visual Studio 2017. Release built is fine and the test seems to work. The issue is critical as this is the entry example for using Alembic and prevents to debug any initial Alembic implementation. If you do not have VS 2017 at your hand, let me know if more details are required or if I should try out anything.

The function in PolyMeshTest.cpp and critical line (103) are below:

void Example1_MeshOut()
{
...
    OArchive archive( Alembic::AbcCoreOgawa::WriteArchive(),  "polyMesh1.abc" );   <<CRASH
…
}

**Comment by lamiller0** [comment]
Yeah I just tested this again and didn't get crashes.

Here is what I did:

cmake -DILMBASE_INCLUDE_DIR=%LIBAREA%\include\OpenEXR -DILMBASE_ROOT=%LIBAREA%\lib -DCMAKE_INSTALL_PREFIX=%INSTAL_LOCATION% -DUSE_HDF5=OFF -DUSE_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 15 2017 Win64" %LOCATION%

cmake --build . --config Debug

PATH=%PATH%;$LOCATION\lib\Alembic\Debug
ctest

**Comment by eddiz** [comment]
hm that's strange. The configuration and cmake settings look pretty much identical to mine. What makes me wonder while I am looking on it again is that the Debug built, does not link to the Debug built of Alembic.

stack trace is:
KernelBase.dll!00007ffb0199f218()
 vcruntime140.dll!00007ffaff604462()
 msvcp140.dll!00007ffafef24e02()
 Alembic.dll!00007ffaaa3726a0()
Alembic.dll!00007ffaaa3a372f()
Alembic.dll!00007ffaaa3a388d()
AbcGeom_PolyMeshTest.exe!Alembic::Abc::v10::ErrorHandler::Context::operator()(std::exception & iExc) Line 102
AbcGeom_PolyMeshTest.exe!`Alembic::Abc::v10::OArchive::OArchive<Alembic::AbcCoreOgawa::v10::WriteArchive>'::`1'::catch$8() Line 216
[External Code]		
AbcGeom_PolyMeshTest.exe!Alembic::Abc::v10::OArchive::OArchive<Alembic::AbcCoreOgawa::v10::WriteArchive>(Alembic::AbcCoreOgawa::v10::WriteArchive iCtor, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & iFileName, const Alembic::Abc::v10::Argument & iArg0, const Alembic::Abc::v10::Argument & iArg1) Line 214
AbcGeom_PolyMeshTest.exe!Example1_MeshOut() Line 103
AbcGeom_PolyMeshTest.exe!main(int argc, char * * argv) Line 432

**Comment by lamiller0** [comment]
Hmmm, is your path setup correctly to pick up the recently compiled debug dll instead of some other one?  (like maybe an official install already in your path?)

**Comment by eddiz** [comment]
Oh damm it. You are right and I should have known it. It seems that I copied the release Alembic.dll to the Debug build, while trying to compile Alembic. Sorry for the inconvenience! 

Solution: Make sure that Tests call the Debug version of the Alembic libraries (Alembic.lib/Alembic.dll)
