### ISSUE TITLE
Shape name discrepancy in Maya when importing instanced mesh

### ISSUE THREAD

**Issue by pankajpundir** [alembic/alembic#171]
Per conversation on the [google group](https://groups.google.com/forum/#!topic/alembic-discussion/b93846CYuIo), we get unexpected shape names in Maya when importing instanced geometry that has a different name from it's master object.

Attached is the repro file that has the following hierarchy,
```
ABC
 `--root
     |--trans1
     |   `--masterShape
     `--trans2
         `--instanceShape [INSTANCE OF: /root/trans1/masterShape]
```
When imported in Maya, without instancing, we get the same name for the shape node (as represented below), where as, we were hoping to get different names.
```
--root
     |--trans1
     |   `--masterShape
     `--trans2
         `--masterShape
```
[plane_instanced.gz](https://github.com/alembic/alembic/files/2050311/plane_instanced.gz)

Thanks
Pankaj

**Comment by lamiller0** [comment]
This should be fixed now from this PR:
https://github.com/alembic/alembic/pull/195
