### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [alembic/alembic#184]
I would like to point out that an identifier like “[`_Alembic_Abc_Reference_h_`](https://github.com/alembic/alembic/blob/d75360416b1b20df85c4f58195d0898695ceb525/lib/Alembic/Abc/Reference.h#L37 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by lamiller0** [comment]
For completeness, the expected naming convention is?

Alembic_Abc_Refernce_h 

or do we now live in a world where it's safe to use:

#pragma once

**Comment by elfring** [comment]
I guess that it will be sufficient to [delete leading underscores from mentioned include guards](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?"), won't it?

**Comment by lamiller0** [comment]
If it's getting changed anyway, I would prefer to move to:

#pragma once 

for the reasons listed here:

https://en.wikipedia.org/wiki/Pragma_once

**Comment by elfring** [comment]
Do you [care for information around the question “Why isn't C/C++'s “#pragma once” an ISO standard?”](https://stackoverflow.com/questions/1695807/why-isnt-c-cs-pragma-once-an-iso-standard "Considerations around “#pragma once”")?

**Comment by gildor2** [comment]
This guy is just filling his "github activity" line with opening issues in hundreds of repositories. Or this is a kid who's looking for ways of speaking with someone. Just one of other "issues" here:
https://github.com/curl/curl/issues/2838
Simply ignore him.

**Comment by lamiller0** [comment]
Done in PR192
