### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [alembic/alembic#185]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [AttrInfo::clear](https://github.com/alembic/alembic/blob/d75360416b1b20df85c4f58195d0898695ceb525/lib/Alembic/AbcCoreHDF5/HDF5Hierarchy.h#L200 "AttrInfo::clear function")
* [CprData](https://github.com/alembic/alembic/blob/d75360416b1b20df85c4f58195d0898695ceb525/lib/Alembic/AbcCoreOgawa/CprData.cpp#L78 "Destructor for CprData")
* [unique_ptr::reset](https://github.com/alembic/alembic/blob/895a7c6a8b3396a21c6ba03ddf91ed91514d7b93/lib/Alembic/Util/Foundation.h#L177 "unique_ptr::reset function")

**Comment by lamiller0** [comment]
Addressed in PR193
