### ISSUE TITLE
convert from old python string style to new style

### ISSUE THREAD

**Issue by ron819** [alembic/alembic#186]
You are using the old python format style using the `'%s'(parameter)` . The new format is `'{0}'.format(parameter)`

This is a problem because users must escape the `%` symbol. 
Sometimes passwords strings contains `% `symbol and we use it as parameter so we can't know whats inside (hashed passwords).

```
http://alembic.zzzcomputing.com/en/latest/api/config.html

Parameters: | section – name of the sectionname – name of the valuevalue – the value. Note that this value is passed to ConfigParser.set, which supports variable interpolation using pyformat (e.g. %(some_value)s). A raw percent sign not part of an interpolation symbol must therefore be escaped, e.g. %%. The given value may refer to another value already in the file using the interpolation format.
-- | --

```

Please convert to new style

**Comment by lamiller0** [comment]
Wrong project, please submit to:

https://bitbucket.org/zzzeek/alembic
