### ISSUE TITLE
OXform and OGeom schemas can fail to retrieve userProperties and arbGeomParams

### ISSUE THREAD

**Issue by nfrechette** [alembic/alembic#188]
On both `OXformSchema` and `OGeomBaseSchema`, the functions for `getArbGeomParams()` and `getUserProperties()` check if the property has been queried already, and if not, it attempts to create it. If the property already exists, this will error out with no way to suppress it.

Because the library allows copying schemas around freely, this scenario is possible:

*  Create a schema A
*  Copy schema A into schema B
*  Call `getUserProperties()` on A, the property is created, it works
*  Call `getUserProperties()` on B, the property fails to create and it cannot be bound

The expected behavior here would be that B is able to find the already created property from A. However, if the copy from A into B happens after the first call to `getUserProperties()`, everything works.

Working around this is easy once the issue has been identified but I did not expect that behavior.

**Comment by lamiller0** [comment]
Could you provide a more concrete example to make sure I understand all the nuances, and to make it easy to create a unit test.

**Comment by nfrechette** [comment]
Try the following:

```c++
Alembic::AbcGeom::OXform xform(some_parent, "test", 0);
auto schema0 = xform.getSchema();
auto schema1 = schema0;
schema0.getUserProperties();
schema1.getUserProperties(); // exception is raised here
```

It yields the following exception:

> OXformSchema::getUserProperties()
ERROR: EXCEPTION:
OCompoundProperty::init()
ERROR: EXCEPTION:
Already have a property named: .userProperties

The first call to `getUserProperties()` creates the actual property underneath and caches a pointer to it. The second call attempts to create it again but fails and throws an exception.

I tried this with v1.7.5 but I imagine it still happens with the latest as the code seems identical to me.

**Comment by lamiller0** [comment]
I've attempted to address this here:
https://github.com/alembic/alembic/pull/200

**Comment by nfrechette** [comment]
You know the internals better than I do but as long as `iParent->getProperty` doesn't throw an exception and returns null if the property isn't found, that fix looks good to me.
