### ISSUE TITLE
Alembic not working after installing with pip

### ISSUE THREAD

**Issue by patrikhuber** [alembic/alembic#189]
Hi,

I've just done `pip install alembic`, and am following the tutorial on the [alembic docs](https://docs.alembic.io/python/examples.html) website to read an .abc file from Python. I can do `import alembic`, but that's as far as I am able to go. I can't use `IArchive` to read an `.abc` file ("function not defined"), nor can I import `alembic.Abc` or anything else from alembic.
From reading and following the documentation, I'd expect this to work.

After a bit of digging it seems like the alembic version on pip (https://pypi.org/project/alembic/) might be `1.0.0`, which if true, would be really ancient? It says `Last released: Jul 13, 2018` though, adding to the confusion.

I've read the documentation and googled but it's not obvious what I am doing wrong.
Probably I can build Alembic and its Python bindings manually from source and then it would work, but I'd like to avoid that if possible, since there is a `pip` package, which is supposed to do the building if there is no wheel available for a given platform.

Thanks!

**Comment by lamiller0** [comment]
That python module is for a different project.
The one you are grabbing is for:
http://alembic.zzzcomputing.com/en/latest/

Hence the missing functions.

I'm currently unsure if this one is in pypi.

**Comment by patrikhuber** [comment]
Aah! I see - how confusing. Indeed that page says "Alembic is a lightweight database migration tool for usage with the SQLAlchemy Database Toolkit for Python."... not quite the alembic I wanted!

Thank you, and I'm pretty sure this one is then not on pypi.
