### ISSUE TITLE
Create date column with "server_default='now()'" add current date in db as default instead of "now()"

### ISSUE THREAD

**Issue by Le-Stagiaire** [alembic/alembic#190]
`
op.create_table('test', sa.Column('date', sa.DateTime(), server_default='now()', nullable=False))
`

I've tested with possible value, like 'sa.func.now()', or 'now' with the parentheses, ...
I think this is more of a sqlalchemy error, but it's when we use it in alembic that the sql generated is bad so ... And also I cannot create issue on sqlalchemy repo :$

**Comment by lamiller0** [comment]
Wrong Alembic project.

Please try:
https://bitbucket.org/zzzeek/alembic/issues?status=new&status=open
