### ISSUE TITLE
How to get IPoint Primitive Propertie in 1.7.9

### ISSUE THREAD

**Issue by ArthurChiu** [alembic/alembic#201]
in houdini 17, export particle with primitive string attribute , but i can't read it in my custom proc

**Comment by lamiller0** [comment]
Is there a simple example you can share?

Is the string attr in the file?

**Comment by lamiller0** [comment]
Did you use ROP_Alembic to export your abc file?

**Comment by lamiller0** [comment]
My hunch is that it might be a Houdini 17 issue.
