### ISSUE TITLE
Not able to migrate geoalchemy2 geometry type

### ISSUE THREAD

**Issue by neebj** [alembic/alembic#204]
Getting following error while migrating sqlalchemy fields using flask db migrate:
 File "\site-packages\graphene_sqlalchemy\converter.py", line 87, in convert_sqlalchemy_type
    % (column, column.__class__)
Exception: Don't know how to convert the SQLAlchemy field property.location_geometry (<class 'sqlalchemy.sql.schema.Column'>)

**Comment by lamiller0** [comment]
Wrong Alembic project, I believe the one you want to submit an issue for is here:

https://bitbucket.org/zzzeek/alembic
