### ISSUE TITLE
Many user attributes get converted to arbGeom after 8d60a89755

### ISSUE THREAD

**Issue by AndrewJDR** [alembic/alembic#209]
I may be mistaken, but I believe this line introduced in 8d60a89755 has effectively made it so just about any object within maya that has user defined attributes will have those saved as arbgeom params rather than userProperties, even if `-uatp` is passed to AbcExport, and even if those objects aren't involved with particles in any way.

Was this the intent?
https://github.com/alembic/alembic/blob/8d60a897551d6ebc6975483cdd95eb46745198ae/maya/AbcExport/AttributesWriter.cpp#L1817

Just to clarify, calling `hasObj(MFn::kParticle)` on just about anything will return true, even a fresh sphere:
```
import maya.api.OpenMaya as om
import maya.cmds as cmds

aSphere = cmds.polySphere()[0]
print("aSphere: " + str(aSphere))
mSel = om.MSelectionList()
mSel.add(str(aSphere))
mDag = mSel.getDagPath(0)
mDag.extendToShape()
thisObj = mDag.node()
dgNode = om.MFnDependencyNode( thisObj )
hasParticle = dgNode.hasObj(om.MFn.kParticle)

print(mDag.fullPathName() + " hasObj(kParticle)?", hasParticle)
```
(Also tried quite a few other node types, all returned `true`)

So the code effectively seems to be:
```
if (userAttr)
{
userAttr = false;
userPerParticleAttr = true;
}
```

Perhaps the intent was this?
```
if (userAttr && isPerParticle)
...
```
But I'm just guessing.

**Comment by AndrewJDR** [comment]
Paging @HansBaldzuhn :)

**Comment by lamiller0** [comment]
Just tried this out and it appears to be working correctly, do you have a stand alone test case where it wasn't working?  What version of Maya are you using?

**Comment by AndrewJDR** [comment]
Hi @lamiller0, I sent you an email about this with some repro details.

**Comment by lamiller0** [comment]
Thank you for the example case.

The reason why I didn't hit this issue in my initial test was, I was putting that attr on the polySphere NOT the faceset.

I added this to your repro case:
addAttr -longName "testprefix_attr" "pSphereShape1";
setAttr pSphereShap1.testprefix_attr 42;

And noticed that for the polySphere testprefix_attr made its way into the user properties correctly.
However for the faceset it was making its way into the .arbGeomParams as you reported.

**Comment by lamiller0** [comment]
I put in a fix here, and ran a few tests on it.  It appears to be working.

https://github.com/alembic/alembic/pull/211

**Comment by AndrewJDR** [comment]
Great, I had already tried that particular fix so I know it works. Hopefully it doesn't cause problems for the particles use case.
