### ISSUE TITLE
symbol(s) not found for architecture x86_64 using alembic 1.7.10

### ISSUE THREAD

**Issue by feeling1982113** [alembic/alembic#210]
Ld: symbol(s) not found for architecture x86_64
Clang: error: linker command failed with exit code 1 (use -v to see invocation)
Make[2]: *** [lib/Alembic/libAlembic.1.7.10.dylib] Error 1
Make[1]: *** [lib/Alembic/CMakeFiles/Alembic.dir/all] Error 2
Make: *** [all] Error 2

I changed the statement of AlembicMaya.cmake when this error occurred.
    SET( MAYA_COMPILE_FLAGS
      "-mmacosx-version-min=10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -DAW_NEW_IOSTREAMS -DCC_GNU_ -DOSMac_ -DOSMacOSX_ -DOSMac_MachO_ -DREQUIRE_IOSTREAM - Fno-gnu-keywords -D_LANGUAGE_C_PLUS_PLUS -include ${MAYA_INCLUDE_PATH}/maya/OpenMayaMac.h" )

Changed

    SET( MAYA_COMPILE_FLAGS
      "-DAW_NEW_IOSTREAMS -DCC_GNU_ -DOSMac_ -DOSMacOSX_ -DBits32_
      -DOSMac_MachO_ -DREQUIRE_IOSTREAM -fno-gnu-keywords -fpascal-strings
    -arch i386 -D_LANGUAGE_C_PLUS_PLUS -include ${MAYA_INCLUDE_PATH}/maya/OpenMayaMac.h" )

At the same time, I was prompted to find OpenMayaMac.h so I blocked the flag of OpenMayaMac.h and found a similar problem saying to join -mmacosx-version-min=10.14. I also tried a single or no effect, only shield it. It can be compiled by a drop, and a small problem is that -framework Quicktime is replaced.
 -framework QTKit
May be the reason for my system, I probably modified these to pass the compilation.
Import into Maya import prompt I did not find the plugin in that directory, but I tried to download the version downloaded from AutoDesk can be imported directly but the version is 1.7.5 version, I want to test the new version of the compiler if you can trouble to see where it is Thank you for the question.

    SET( MAYA_LINK_FLAGS
      #"-dynamic -g -fPIC "
      #"-shared -g -fPIC "
      "-fno-gnu-keywords -framework System -framework SystemConfiguration -framework CoreServices -framework Carbon -framework Cocoa -framework ApplicationServices -framework QTKit -framework IOKit -bundle -fPIC -L${ALEMBIC_MAYA_LIB_ROOT} -Wl,-executable_path,${ALEMBIC_MAYA_LIB_ROOT }" )#-framework Quicktime
I don't know where the most important thing is to make a mistake. I know that blocking openmayamac.h is wrong, but I don't know how to pass this step. I am using macOS Mojave10.14.
Thank you.

**Comment by lamiller0** [comment]
Was there any hint given as to what symbols?  Or an extra flag to pass to the linker to print them out?

**Comment by feeling1982113** [comment]
I think it should not be this problem. I am using Maya2019 to compile. Is it different from before?
I tried to find this file OpenMayaMac.h I looked at the openMaya provided by the development package provided by autoDesk in the FindMaya.cmake file. The code is like this. It does not directly provide this file, but the compiled library file.

Set(MAYA_VERSION 2019)

If (WIN32)
Set(MAYA_DEFAULT_LOCATION "C:/Program Files/Autodesk/Maya${MAYA_VERSION}")
Set(OPEN_MAYA OpenMaya.lib)
     Set(LIB_SUFFIX "lib/")
Elseif(APPLE)
Set(MAYA_DEFAULT_LOCATION "/Applications/Autodesk/maya${MAYA_VERSION}")
Set(OPEN_MAYA libOpenMaya.dylib)
     Set(LIB_SUFFIX "Maya.app/Contents/MacOS")
Elseif(LINUX)
Set(MAYA_DEFAULT_LOCATION "/usr/autodesk/maya${MAYA_VERSION}")
Set(OPEN_MAYA libOpenMaya.so)
     Set(LIB_SUFFIX "lib/")
Endif()

I am trying to compile it from a brand new file today. Thank you.

**Comment by feeling1982113** [comment]
I don't modify the code MAYA_COMPILE_FLAGS to prompt such an error.

huanghaibindeiMac:build huanghaibin$ cmake -DALEMBIC_SHARED_LIBS=ON -DUSE_HDF5=ON -DUSE_MAYA=ON -DALEMBIC_LIB_USES_TR1=OFF -DALEMBIC_LIB_USES_BOOST=ON -DMAYA_ROOT=/Volumes/work/Applications/Autodesk/maya2019 ../
-- CMAKE SYSTEM NAME: Darwin
CMake Deprecation Warning at CMakeLists.txt:110 (CMAKE_POLICY):
  The OLD behavior for policy CMP0042 will be removed from a future version
  Of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  Policies are deprecated and that a policy should be set to OLD only under
  Specific short-term circumstances. Projects should be ported to the NEW
  Behavior and not rely on setting a policy to OLD.


-- The install dir is /usr/local
-- Boost version: 1.69.0
-- Found the following Boost libraries:
-- program_options
-- BOOST INCLUDE DIRS: /usr/local/include
-- BOOST LIBRARIES: /usr/local/lib/libboost_program_options-mt.dylib
ILMBASE_ROOT is undefined
-- ILMBASE INCLUDE PATH: /usr/local/include/OpenEXR
-- HALF LIB: /usr/local/lib/libHalf.dylib
-- IEX LIB: /usr/local/lib/libIex.dylib
-- IEXMATH LIB: /usr/local/lib/libIexMath.dylib
-- ILMTHREAD LIB: /usr/local/lib/libIlmThread.dylib
-- IMATH LIB: /usr/local/lib/libImath.dylib
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5_INCLUDE_DIRS: /usr/local/Cellar/hdf5/1.10.5/include;/usr/local/opt/szip/include
-- HDF5_LIBRARIES: /usr/local/Cellar/hdf5/1.10.5/lib/libhdf5.dylib;/usr/local/opt/szip/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/ Lib/libdl.dylib;/usr/lib/libm.dylib
-- Using MAYA_ROOT /Volumes/work/Applications/Autodesk/maya2019
-- Maya lib root: /Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/MacOS
-- Found Maya!
-- Building Maya plugins

   * Alembic Configuration ===
   * USE_ARNOLD OFF
   * USE_BINARIES ON
   * USE_EXAMPLES OFF
   * USE_HDF5 ON
   * USE_MAYA ON
   * USE_PRMAN OFF
   * USE_PYALEMBIC OFF
   * USE_STATIC_BOOST OFF
   * USE_STATIC_HDF5 OFF
   * USE_TESTS ON
   * ALEMBIC_ILMBASE_LINK_STATIC OFF
   * ALEMBIC_SHARED_LIBS ON
   * ALEMBIC_LIB_USES_BOOST ON
   * ALEMBIC_LIB_USES_TR1 OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/huanghaibin/alembic-1.7.10/build
huanghaibindeiMac:build huanghaibin$ make -j4
-------------------------------------------------------------------------------
[ 91%] Building CXX object maya/AbcExport/CMakeFiles/AbcExport.dir/AbcExport.cpp.o
cd /Users/huanghaibin/alembic-1.7.10/build/maya/AbcExport && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DAbcExport_EXPORTS -DPLATFORM=DARWIN -DPLATFORM_DARWIN -I/usr/local/include -I/usr/local/include/OpenEXR -I/usr/local/Cellar/hdf5/1.10.5/include -I/usr/local/opt/szip/include -I/Users/huanghaibin/alembic-1.7.10/lib -I/Users/huanghaibin/alembic-1.7.10/build/lib -I/Users/huanghaibin/alembic-1.7.10/maya/AbcExport/.. -I/Volumes/work/Applications/Autodesk/maya2019/include  -DH5_USE_18_API -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC   -fPIC -fPIC -DAW_NEW_IOSTREAMS -DCC_GNU_ -DOSMac_ -DOSMacOSX_ -DOSMac_MachO_ -DREQUIRE_IOSTREAM -fno-gnu-keywords -D_LANGUAGE_C_PLUS_PLUS -include /Volumes/work/Applications/Autodesk/maya2019/include/maya/OpenMayaMac.h -o CMakeFiles/AbcExport.dir/AbcExport.cpp.o -c /Users/huanghaibin/alembic-1.7.10/maya/AbcExport/AbcExport.cpp
<built-in>:1:10: fatal error: '/Volumes/work/Applications/Autodesk/maya2019/include/maya/OpenMayaMac.h' file not found
#include "/Volumes/work/Applications/Autodesk/maya2019/include/maya/OpenMayaMac.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 91%] Building CXX object maya/AbcImport/CMakeFiles/AbcImport.dir/AbcImport.cpp.o
cd /Users/huanghaibin/alembic-1.7.10/build/maya/AbcImport && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DAbcImport_EXPORTS -DPLATFORM=DARWIN -DPLATFORM_DARWIN -I/usr/local/include -I/usr/local/include/OpenEXR -I/usr/local/Cellar/hdf5/1.10.5/include -I/usr/local/opt/szip/include -I/Users/huanghaibin/alembic-1.7.10/lib -I/Users/huanghaibin/alembic-1.7.10/build/lib -I/Users/huanghaibin/alembic-1.7.10/maya/AbcImport/.. -I/Volumes/work/Applications/Autodesk/maya2019/include  -DH5_USE_18_API -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC   -fPIC -fPIC -DAW_NEW_IOSTREAMS -DCC_GNU_ -DOSMac_ -DOSMacOSX_ -DOSMac_MachO_ -DREQUIRE_IOSTREAM -fno-gnu-keywords -D_LANGUAGE_C_PLUS_PLUS -include /Volumes/work/Applications/Autodesk/maya2019/include/maya/OpenMayaMac.h -o CMakeFiles/AbcImport.dir/AbcImport.cpp.o -c /Users/huanghaibin/alembic-1.7.10/maya/AbcImport/AbcImport.cpp
<built-in>:1:10: fatal error: '/Volumes/work/Applications/Autodesk/maya2019/include/maya/OpenMayaMac.h' file not found
#include "/Volumes/work/Applications/Autodesk/maya2019/include/maya/OpenMayaMac.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [maya/AbcImport/CMakeFiles/AbcImport.dir/AbcImport.cpp.o] Error 1
make[1]: *** [maya/AbcImport/CMakeFiles/AbcImport.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Building CXX object bin/AbcStitcher/CMakeFiles/abcstitcher.dir/util.cpp.o
cd /Users/huanghaibin/alembic-1.7.10/build/bin/AbcStitcher && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DPLATFORM=DARWIN -DPLATFORM_DARWIN -I/usr/local/include -I/usr/local/include/OpenEXR -I/usr/local/Cellar/hdf5/1.10.5/include -I/usr/local/opt/szip/include -I/Users/huanghaibin/alembic-1.7.10/lib -I/Users/huanghaibin/alembic-1.7.10/build/lib  -DH5_USE_18_API -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -fPIC -fPIC -o CMakeFiles/abcstitcher.dir/util.cpp.o -c /Users/huanghaibin/alembic-1.7.10/bin/AbcStitcher/util.cpp
1 error generated.
make[2]: *** [maya/AbcExport/CMakeFiles/AbcExport.dir/AbcExport.cpp.o] Error 1
make[1]: *** [maya/AbcExport/CMakeFiles/AbcExport.dir/all] Error 2
[ 91%] Linking CXX executable abcdiff
cd /Users/huanghaibin/alembic-1.7.10/build/bin/AbcDiff && /usr/local/Cellar/cmake/3.14.2/bin/cmake -E cmake_link_script CMakeFiles/abcdiff.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DH5_USE_18_API -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/abcdiff.dir/AbcDiff.cpp.o  -o abcdiff ../../lib/Alembic/libAlembic.1.7.10.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIlmThread.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libIexMath.dylib /usr/local/lib/libHalf.dylib -lm 
[ 91%] Built target abcdiff
[ 91%] Linking CXX executable abcstitcher
cd /Users/huanghaibin/alembic-1.7.10/build/bin/AbcStitcher && /usr/local/Cellar/cmake/3.14.2/bin/cmake -E cmake_link_script CMakeFiles/abcstitcher.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DH5_USE_18_API -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/abcstitcher.dir/AbcStitcher.cpp.o CMakeFiles/abcstitcher.dir/util.cpp.o  -o abcstitcher ../../lib/Alembic/libAlembic.1.7.10.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIlmThread.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libIexMath.dylib /usr/local/lib/libHalf.dylib -lm 
[ 91%] Built target abcstitcher
make: *** [all] Error 2
huanghaibindeiMac:build huanghaibin$

**Comment by lamiller0** [comment]
What errors do you get with the build when you remove the -include ${MAYA_INCLUDE_PATH}/maya/OpenMayaMac.h from cmake/AlembicMaya.cmake

It looks like the logic for compiling these plugins on the Mac may need to change as it hasn't been updated since 2015.

**Comment by feeling1982113** [comment]
This error message：
[100%] Linking CXX shared module AbcImport.bundle
Cd /Users/huanghaibin/alembic-1.7.10/build/maya/AbcImport && /usr/local/Cellar/cmake/3.14.2/bin/cmake -E cmake_link_script CMakeFiles/AbcImport.dir/link.txt --verbose= 1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DH5_USE_18_API -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14 .sdk -bundle -Wl,-headerpad_max_install_names -fno-gnu-keywords -framework System -framework SystemConfiguration -framework CoreServices -framework Carbon -framework Cocoa -framework ApplicationServices -framework Quicktime -framework IOKit -bundle -fPIC -L/Volumes/work/ Applications/Autodesk/maya2019/Maya.app/Contents/MacOS -Wl,-executable_path,/Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/MacOS -o AbcImport.bundle CMakeFiles/AbcImport.dir/AbcImport. Cpp.o CMakeFiles/AbcImport.dir/AlembicImportFileTranslator.cpp.o CMakeFiles/AbcImport.dir/AlembicNode.cpp.o CMakeFiles/AbcImport.dir/CameraHelper.cpp.o CMakeFiles/AbcImport.dir/CreateSceneHelper.cpp.o CMakeFiles/AbcImport .dir/main.cpp.o CMakeFiles/AbcImport.dir/LocatorHelper.cpp.o CMakeFiles/AbcImport.dir/MeshHelp Er.cpp.o CMakeFiles/AbcImport.dir/NurbsCurveHelper.cpp.o CMakeFiles/AbcImport.dir/NurbsSurfaceHelper.cpp.o CMakeFiles/AbcImport.dir/NodeIteratorVisitorHelper.cpp.o CMakeFiles/AbcImport.dir/PointHelper.cpp.o CMakeFiles /AbcImport.dir/util.cpp.o CMakeFiles/AbcImport.dir/XformHelper.cpp.o -framework Foundation /Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/MacOS/libOpenMaya.dylib /Volumes/work /Applications/Autodesk/maya2019/Maya.app/Contents/MacOS/libOpenMayaAnim.dylib /Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/MacOS/libOpenMayaFX.dylib /Volumes/work/Applications/Autodesk/maya2019 /Maya.app/Contents/MacOS/libOpenMayaRender.dylib /Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/MacOS/libOpenMayaUI.dylib -framework Foundation /Volumes/work/Applications/Autodesk/maya2019/Maya. App/Contents/MacOS/libOpenMaya.dylib /Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/MacOS/libOpenMayaAnim.dylib /Volumes/work/Applications/Autodesk/maya201 9/Maya.app/Contents/MacOS/libOpenMayaFX.dylib /Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/MacOS/libOpenMayaRender.dylib /Volumes/work/Applications/Autodesk/maya2019/Maya.app/ Contents/MacOS/libOpenMayaUI.dylib ../../lib/Alembic/libAlembic.1.7.10.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIlmThread.dylib /usr/local/lib /libIex.dylib /usr/local/lib/libIexMath.dylib /usr/local/lib/libHalf.dylib -lm
Ld: framework not found Quicktime
Clang: error: linker command failed with exit code 1 (use -v to see invocation)
Make[2]: *** [maya/AbcImport/AbcImport.bundle] Error 1
Make[1]: *** [maya/AbcImport/CMakeFiles/AbcImport.dir/all] Error 2
Make: *** [all] Error 2
huanghaibindeiMac:build huanghaibin$

**Comment by lamiller0** [comment]
I heard OpenMayaMac.h was removed from the Devkit for Maya 2016.  It will need to be removed from the CMake file.

It also sounds like the linker error may be related to libFoundation.dylib not being properly found.

**Comment by lamiller0** [comment]
I removed OpenMayaMac.h in 1.7.11 but didn't try to address your linker error.

Was libFoundation.dylib properly found?
