### ISSUE TITLE
missing modules in alembic.so python

### ISSUE THREAD

**Issue by remusavram** [alembic/alembic#212]
Hi guys,

I managed to successfully compile alembic version 1.7.10 using the following configuration:
```
cmake .. \
    -DUSE_MAYA=ON \
    -DUSE_ARNOLD=OFF \
    -DUSE_HDF5=ON \
    -DUSE_PYALEMBIC=ON \
    -DUSE_STATIC_BOOST=ON \
    -DUSE_STATIC_HDF5=ON \
    -DALEMBIC_SHARED_LIBS=OFF \
    -DALEMBIC_ILMBASE_LINK_STATIC=ON \
    -DALEMBIC_LIB_USES_BOOST=ON \
    -DILMBASE_ROOT=${ILMBASE_ROOT} \
    -DHDF5_ROOT=${HDF5_ROOT} \
    -DMAYA_ROOT=${MAYA_ROOT} \
    -DBOOST_ROOT=${BOOST_ROOT} \
    -DARNOLD_ROOT=${ARNOLD_ROOT} \
    -DCMAKE_BUILD_TYPE=Release \
    -DALEMBIC_PYILMBASE_INCLUDE_DIRECTORY=${PYILMBASE_INCLUDE_DIR} \
    -DALEMBIC_PYILMBASE_PYIMATH_LIB=${PYILMBASE_LIBRARY_DIR} \
    -DPYTHON_INCLUDE_DIR=${PYTHON_ROOT}"/include/python2.7" \
    -DPYTHON_LIBRARY=${PYTHON_ROOT}"/lib/libpython2.7.so" \
    -DCMAKE_CXX_FLAGS="-std=c++11" \
    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
```

Unfortunately, there are a few modules missing when I import `alembic` in python like `AbcGeom`:
```
>>> import alembic
>>> print dir(alembic)
['Abc', 'AbcCoreAbstract', 'Util', '__doc__', '__name__', '__package__', '__path__']
```

I expect to get:
```
['Abc', 'AbcCollection', 'AbcCoreAbstract', 'AbcGeom', 'AbcMaterial', 'Util', '__doc__', '__file__', '__name__', '__package__', '__path__']
```

**Versions:**
```
PYTHON_VERSION='2.7'
MAYA_VERSION='2018'
ARNOLD_VERSION='5.2.2.1'
CMAKE_VERSION='3.3.2'
HDF5_VERSION='1.10.4'
ILMBASE_VERSION='2.2.1_static'
PYILMBASE_VERSION='2.2.1_static'
BOOST_VERSION='1.54.0_static'
OS= 'CentOS 7'
```

Do I need to set any special configuration to get all the modules available?

**Comment by lamiller0** [comment]
Are the things in Abc the same in both?

AbcGeom module is setup and populated here:
https://github.com/alembic/alembic/blob/master/python/PyAlembic/main.cpp#L183

It's a bit suspicous that in your top one, you don't see __file__ in the list.
Could the Alembic bindings be coming from an incorrect location that you didn't build?

**Comment by remusavram** [comment]
Thanks @lamiller0 for the quick answer!

I think I missed a "small" detail.
When I import the first time `alembic` in `python` I get this error:
```
TypeError: No Python class registered for C++ class PyImath::FixedArray<bool>
```

>  Could the Alembic bindings be coming from an incorrect location that you didn't build?

No, I am sure about this.

**Comment by lamiller0** [comment]
Ahhhh, digging around on the Alembic forums others have hit this issue as well and it is because of an imath library mismatch.

Is the imath you import in python is the same version as what is used to build your bindings?

**Comment by remusavram** [comment]
> Is the imath you import in python is the same version as what is used to build your bindings?
yes, is the same version.

**Comment by sopvop** [comment]
Do you compile with clang and libc++? I does dynamic_cast not the same way as gcc and libstdc++, and requires more export annotations on classes to work correctly.

**Comment by remusavram** [comment]
> Do you compile with clang and libc++? I does dynamic_cast not the same way as gcc and libstdc++, and requires more export annotations on classes to work correctly.

No. I compiled it with gcc, the version which centos 7 is coming: `4.8.5`

**Comment by remusavram** [comment]
I found out the issue. This happens when I compile `pyilmbase` and `alembic` against the static boost libs.
I managed to have it working when I compile them agains the shared libs. I still don't know why...

**Comment by sopvop** [comment]
Oh, I had the exact same issue with usd. Some c++ wart I guess
