### ISSUE TITLE
Z-Axis flip

### ISSUE THREAD

**Issue by rsodre** [alembic/alembic#214]
I have a Maya plugin that is being ported to Cinema 4D, and it has a custom Alembic importer/exporter. The maya version is in production for some years, and was thoroughly tested.

Using my custom Maya exporter to generate an Alembic file, and importing it in Cinema 4D using the same custom importer, I notice that the Z axis is visually flipped. Indeed the Z axis of both applications are inverted (Maya i right-hand and C4D is left-hand), and the imported coordinates are preserved, so an object at Z=100 in Maya is imported at Z=100 in Cinema 4D, so that's kinda expected.

But, when using the native Maya exporter and native Cinema 4D importer, somehow the Z axis is automatically corrected. Visually, it looks ok, because the coordinates were flipped, an object at Z=100 in Maya is imported at Z=-100 in Cinema 4D, .

Any ideas how this information is passed from one host to the other?
I can't find anything in the Alembic specification that stores the Z-axis direction of the exporter.
Both applications up vector are Y, and this is set correctly.

**Comment by lamiller0** [comment]
I wonder if the C4d importer looks at the IArchive metadata to see if it was exported from Maya to make it's flipping decision.

Is the source for the C4d plugin available somewhere so I can try to confirm?

**Comment by rsodre** [comment]
Some Cinema 4D importers (like the OBJ importer), there's a Flip Z Axis enabled by default, so looks like it's a common issue and the nature of C4D.
I'm now assuming that by default, flipping Z on import and export and everything's compatible.
