### ISSUE TITLE
Error ReadWrite.cpp

### ISSUE THREAD

**Issue by vutran000** [alembic/alembic#218]
Attempting to build PyAlembic on macOS Mojave 10.14.4
Running make produces this error:

/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.cpp:75:5: error: use of undeclared identifier 'm_useMMap'
    m_useMMap = true;
    ^
/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.cpp:79:14: error: out-of-line definition of 'ReadArchive'
      does not match any declaration in 'Alembic::AbcCoreOgawa::v10::ReadArchive'
ReadArchive::ReadArchive( size_t iNumStreams, bool iUseMMap )
             ^~~~~~~~~~~
/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.cpp:82:5: error: use of undeclared identifier 'm_useMMap';
      did you mean 'iUseMMap'?
    m_useMMap = iUseMMap;
    ^~~~~~~~~
    iUseMMap
/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.cpp:79:52: note: 'iUseMMap' declared here
ReadArchive::ReadArchive( size_t iNumStreams, bool iUseMMap )
                                                   ^
/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.cpp:87:26: error: member initializer 'm_useMMap' does not
      name a non-static data member or base class
    : m_numStreams( 1 ), m_useMMap(true), m_streams( iStreams )
                         ^~~~~~~~~~~~~~~
/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.cpp:100:50: error: use of undeclared identifier 'm_useMMap'
            new ArImpl( iFileName, m_numStreams, m_useMMap ) );
                                                 ^
/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.cpp:121:50: error: use of undeclared identifier 'm_useMMap'
            new ArImpl( iFileName, m_numStreams, m_useMMap ) );
                                                 ^
6 errors generated.
make[2]: *** [lib/Alembic/CMakeFiles/Alembic.dir/AbcCoreOgawa/ReadWrite.cpp.o] Error 1
make[1]: *** [lib/Alembic/CMakeFiles/Alembic.dir/all] Error 2
make: *** [all] Error 2

**Comment by lamiller0** [comment]
Are you pulling in AbcCoreOgawa/ReadWrite.h from a different place?

m_useMMap should be defined in:
/Users/vu/Documents/NON_UNITY_STUFF/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa/ReadWrite.h

**Comment by vutran000** [comment]
AbcCoreOgawa/ReadWrite.cpp and AbcCoreOgawa/ReadWrite.h are both in the same directory.
I made no directory changes for any of the files from my initial git clone.

AbcCoreOgawa vu$ pwd
/Users/vu/Documents/_NON_UNITY_STUFF_/PyAlembic/alembic/lib/Alembic/AbcCoreOgawa

AbcCoreOgawa vu$ ls -l
total 712
-rw-r--r--   1 vu  staff   2047 Jun 25 00:28 All.h
-rw-r--r--   1 vu  staff   7587 Jun 25 00:28 AprImpl.cpp
-rw-r--r--   1 vu  staff   3898 Jun 25 00:28 AprImpl.h
-rw-r--r--   1 vu  staff  10409 Jun 25 00:28 ApwImpl.cpp
-rw-r--r--   1 vu  staff   3810 Jun 25 00:28 ApwImpl.h
-rw-r--r--   1 vu  staff   7134 Jun 25 00:28 ArImpl.cpp
-rw-r--r--   1 vu  staff   4413 Jun 25 01:13 ArImpl.h
-rw-r--r--   1 vu  staff   8722 Jun 25 00:28 AwImpl.cpp
-rw-r--r--   1 vu  staff   4558 Jun 25 00:28 AwImpl.h
-rw-r--r--   1 vu  staff   2622 Jun 25 00:28 CMakeLists.txt
-rw-r--r--   1 vu  staff   9785 Jun 25 00:28 CprData.cpp
-rw-r--r--   1 vu  staff   3792 Jun 25 00:28 CprData.h
-rw-r--r--   1 vu  staff   6097 Jun 25 00:28 CprImpl.cpp
-rw-r--r--   1 vu  staff   4228 Jun 25 00:28 CprImpl.h
-rw-r--r--   1 vu  staff   9642 Jun 25 00:28 CpwData.cpp
-rw-r--r--   1 vu  staff   4113 Jun 25 00:28 CpwData.h
-rw-r--r--   1 vu  staff   7575 Jun 25 00:28 CpwImpl.cpp
-rw-r--r--   1 vu  staff   4906 Jun 25 00:28 CpwImpl.h
-rw-r--r--   1 vu  staff   6172 Jun 25 00:28 Foundation.h
-rw-r--r--   1 vu  staff   4063 Jun 25 00:28 MetaDataMap.cpp
-rw-r--r--   1 vu  staff   2897 Jun 25 00:28 MetaDataMap.h
-rw-r--r--   1 vu  staff   6886 Jun 25 00:28 OrData.cpp
-rw-r--r--   1 vu  staff   3860 Jun 25 00:28 OrData.h
-rw-r--r--   1 vu  staff   6604 Jun 25 00:28 OrImpl.cpp
-rw-r--r--   1 vu  staff   3980 Jun 25 00:28 OrImpl.h
-rw-r--r--   1 vu  staff   7742 Jun 25 00:28 OwData.cpp
-rw-r--r--   1 vu  staff   3950 Jun 25 00:28 OwData.h
-rw-r--r--   1 vu  staff   6226 Jun 25 00:28 OwImpl.cpp
-rw-r--r--   1 vu  staff   4088 Jun 25 00:28 OwImpl.h
-rw-r--r--   1 vu  staff  53982 Jun 25 00:28 ReadUtil.cpp
-rw-r--r--   1 vu  staff   4617 Jun 25 00:28 ReadUtil.h
-rw-r--r--   1 vu  staff   4737 Jun 25 00:28 ReadWrite.cpp
-rw-r--r--   1 vu  staff   3987 Jun 25 01:26 ReadWrite.h
-rw-r--r--   1 vu  staff   5301 Jun 25 00:28 SprImpl.cpp
-rw-r--r--   1 vu  staff   3658 Jun 25 00:28 SprImpl.h
-rw-r--r--   1 vu  staff   9536 Jun 25 00:28 SpwImpl.cpp
-rw-r--r--   1 vu  staff   3789 Jun 25 00:28 SpwImpl.h
-rw-r--r--   1 vu  staff   6089 Jun 25 00:28 StreamManager.cpp
-rw-r--r--   1 vu  staff   3520 Jun 25 00:28 StreamManager.h
drwxr-xr-x  10 vu  staff    320 Jun 25 11:51 Tests
-rw-r--r--   1 vu  staff  17204 Jun 25 00:28 WriteUtil.cpp
-rw-r--r--   1 vu  staff   4669 Jun 25 00:28 WriteUtil.h
-rw-r--r--   1 vu  staff   4660 Jun 25 00:28 WrittenSampleMap.h

**Comment by lamiller0** [comment]
Is m_useMMap defined in your ReadWrite.h?

AND  are you sure your compiler include path isn't accidentally pulling Alembic headers from somewhere else?

**Comment by vutran000** [comment]
Thank you! 
The latter you suggested was the problem. It was using the ReadWrite.h from my old 2017 alembic source files. I deleted the old source files and all is good now.
