### ISSUE TITLE
Could not determine ILMBase library version, assuming...  STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to

### ISSUE THREAD

**Issue by rosset** [alembic/alembic#226]
**BUILDSTDERR: CMake Warning at cmake/Modules/FindIlmBase.cmake:124 (MESSAGE):
BUILDSTDERR:   Could not determine ILMBase library version, assuming .
BUILDSTDERR: Call Stack (most recent call first):
BUILDSTDERR:   cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
BUILDSTDERR:   CMakeLists.txt:230 (INCLUDE)
BUILDSTDERR: CMake Error at cmake/Modules/FindIlmBase.cmake:134 (STRING):
BUILDSTDERR:   STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
BUILDSTDERR:   command.
BUILDSTDERR: Call Stack (most recent call first):
BUILDSTDERR:   cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
BUILDSTDERR:   CMakeLists.txt:230 (INCLUDE)**

Mock Version: 1.4.16
Mock Version: 1.4.16
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/alembic.spec'], chrootPath='/var/lib/mock/f31-build-17186212-1233918/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f70bbfbeb50>timeout=172800uid=1000gid=425user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=False)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/alembic.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1558137600
Wrote: /builddir/build/SRPMS/alembic-1.7.11-1.fc31.src.rpm
Child return code was: 0
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/alembic.spec'], chrootPath='/var/lib/mock/f31-build-17186212-1233918/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f70bbfbeb50>timeout=172800uid=1000gid=425user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=False)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/alembic.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1558137600
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.DuNyVN
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf alembic-1.7.11
+ /usr/bin/gzip -dc /builddir/build/SOURCES/alembic-1.7.11.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd alembic-1.7.11
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ sed -i -e 's/ConfigPackageLocation lib/ConfigPackageLocation lib64/g' lib/Alembic/CMakeLists.txt
+ iconv -f iso8859-1 -t utf-8 ACKNOWLEDGEMENTS.txt
+ mv -f ACKNOWLEDGEMENTS.txt.conv ACKNOWLEDGEMENTS.txt
+ mkdir build
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.kCI0PM
+ umask 022
+ cd /builddir/build/BUILD
+ cd alembic-1.7.11
+ pushd build
+ export 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,--as-needed'
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,--as-needed'
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,--as-needed'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ export LDFLAGS
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_SKIP_RPATH:BOOL=ON -DALEMBIC_LIB_INSTALL_DIR=/usr/lib64 -DALEMBIC_SHARED_LIBS=ON -DUSE_BINARIES=ON -DUSE_HDF5=ON -DUSE_EXAMPLES=ON -DUSE_PYALEMBIC=OFF -DUSE_STATIC_BOOST=OFF -DUSE_STATIC_HDF5=OFF -DUSE_TESTS=ON ..

BUILDSTDERR: CMake Warning at cmake/Modules/FindIlmBase.cmake:124 (MESSAGE):
BUILDSTDERR:   Could not determine ILMBase library version, assuming .
BUILDSTDERR: Call Stack (most recent call first):
BUILDSTDERR:   cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
BUILDSTDERR:   CMakeLists.txt:230 (INCLUDE)
BUILDSTDERR: CMake Error at cmake/Modules/FindIlmBase.cmake:134 (STRING):
BUILDSTDERR:   STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
BUILDSTDERR:   command.
BUILDSTDERR: Call Stack (most recent call first):
BUILDSTDERR:   cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
BUILDSTDERR:   CMakeLists.txt:230 (INCLUDE)
BUILDSTDERR:    * Alembic Configuration          ===
BUILDSTDERR:    * USE_ARNOLD                     OFF
BUILDSTDERR:    * USE_BINARIES                   ON
BUILDSTDERR:    * USE_EXAMPLES                   ON
BUILDSTDERR:    * USE_HDF5                       ON
BUILDSTDERR:    * USE_MAYA                       OFF
BUILDSTDERR:    * USE_PRMAN                      OFF
BUILDSTDERR:    * USE_PYALEMBIC                  OFF
BUILDSTDERR:    * USE_STATIC_BOOST               OFF
BUILDSTDERR:    * USE_STATIC_HDF5                OFF
BUILDSTDERR:    * USE_TESTS                      ON
BUILDSTDERR:    * ALEMBIC_ILMBASE_LINK_STATIC    OFF
BUILDSTDERR:    * ALEMBIC_SHARED_LIBS            ON
BUILDSTDERR:    * ALEMBIC_LIB_USES_BOOST         OFF
BUILDSTDERR:    * ALEMBIC_LIB_USES_TR1           OFF
~/build/BUILD/alembic-1.7.11/build ~/build/BUILD/alembic-1.7.11
-- The C compiler identification is GNU 9.1.1
-- The CXX compiler identification is GNU 9.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE SYSTEM NAME: Linux
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- The install dir is /usr
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- ILMBASE_ROOT is undefined
-- ILMBASE INCLUDE PATH: /usr/include/OpenEXR
-- HALF LIB: /usr/lib64/libHalf.so
-- IEX LIB: /usr/lib64/libIex.so
-- IEXMATH LIB: /usr/lib64/libIexMath.so
-- ILMTHREAD LIB: /usr/lib64/libIlmThread.so
-- IMATH LIB: /usr/lib64/libImath.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.10.5") found components:  C 
-- HDF5_INCLUDE_DIRS: /usr/include
-- HDF5_LIBRARIES: /usr/lib64/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so
-- Configuring incomplete, errors occurred!
See also "/builddir/build/BUILD/alembic-1.7.11/build/CMakeFiles/CMakeOutput.log".
See also "/builddir/build/BUILD/alembic-1.7.11/build/CMakeFiles/CMakeError.log".
RPM build errors:
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.kCI0PM (%build)
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.kCI0PM (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 736, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/alembic.spec

**Comment by rosset** [comment]
CMake Warning at cmake/Modules/FindIlmBase.cmake:124 (MESSAGE):
  Could not determine ILMBase library version, assuming .
Call Stack (most recent call first):
  cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
  CMakeLists.txt:230 (INCLUDE)

-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- ILMBASE_ROOT is undefined

CMake Error at cmake/Modules/FindIlmBase.cmake:134 (STRING):
  STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
  CMakeLists.txt:230 (INCLUDE)

**Comment by rosset** [comment]
ilmbase-2.3.0-3.fc31.x86_64
ilmbase-devel-2.3.0-3.fc31.x86_64

**Comment by lamiller0** [comment]
What version of CMake are you using, and where did that alembic.spec file come from?

**Comment by luyatshimbalanga** [comment]
@lamiller0 
> What version of CMake are you using, and where did that alembic.spec file come from?

.spec file is a file needed to build packages for rpm based distribution like Fedora in this case.  CMake included in the distribution is 3.14.5.
The bug occurred in  _cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)_ where that line failed to detect the already installed ilmbase.

**Comment by luyatshimbalanga** [comment]
@lamiller0 
Gentoo has a patch addressing the ilmbase_root detection issue.See the following link:
https://gitweb.gentoo.org/repo/gentoo.git/plain/media-gfx/alembic/files/alembic-1.7.11-0002-Find-IlmBase-by-setting-a-proper-ILMBASE_ROOT-value.patch?id=953b3b21db55df987dd8006dcdec19e945294d98

It will be great to port over on the next release as a bug fix.

**Comment by lamiller0** [comment]
The CMake logic has been significantly reworked to accomodate Imath 3 in the upcoming 1.8.0 release.
