### ISSUE TITLE
Add optional meta data hint to archive about what FPS a DCC may have been using at write time.

### ISSUE THREAD

**Issue by lamiller0** [alembic/alembic#229]
As a hint to DCCs that support multiple FPS settings, it would be useful to record what was used
if known at write time, so that it could optionally be restored if supported.

**Comment by sybrenstuvel** [comment]
What is the status of this? There is already [the feeling that this proposal isn't going anywhere and a suggestion to start adding DCC-specific fields](https://github.com/PixarAnimationStudios/USD/issues/940#issuecomment-538681190) to work around it. I want to avoid such custom fields if at all possible, and just work with the Alembic standard. However, if the Alembic library isn't going to support the suggested FPS hint, it may be our only option.

**Comment by lamiller0** [comment]
This was released, done in these 2 PRs:

https://github.com/alembic/alembic/pull/240
https://github.com/alembic/alembic/pull/242

in 1.7.12

https://github.com/alembic/alembic/releases/tag/1.7.12

Support was added to AbcExport to automatically write this, and abcls advertises it.

**Comment by sybrenstuvel** [comment]
That's great news, thanks.
