### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [alembic/alembic#233]
Greetings Alembic developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by Google-Autofuzz** [comment]
We can also help by starting the OSS-Fuzz integration process for you if lack of time at this point. We just need a google email from you to send bugs to you when libfuzzer finds any.

**Comment by lamiller0** [comment]
Yes please, you can send any bugs you find to miller.lucas@gmail.com

**Comment by Google-Autofuzz** [comment]
````
-- Found Threads: TRUE  
-- ILMBASE_ROOT is undefined
CMake Error at cmake/Modules/FindIlmBase.cmake:156 (MESSAGE):
  ilmbase libraries (Half, Iex, IlmThread, Imath) not found, required
Call Stack (most recent call first):
  cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
  CMakeLists.txt:230 (INCLUDE)
````
Why do I get the error as shown above when I try to build it? This is what I have to build the package:

````
mkdir build
cd build
cmake ..
cd ..
````

**Comment by lamiller0** [comment]
Where do you have OpenEXR installed at?
Maybe this will work?

cmake -DILMBASE_INCLUDE_DIR=/usr/include/OpenEXR2 -DILMBASE_ROOT=/usr/lib64/OpenEXR2 ..

**Comment by Google-Autofuzz** [comment]
I am building everything in a [Docker](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#Dockerfile). As for setting up a new project to upstream to OSS-Fuzz, we uses docker to build everything. Is there a way to install OpenEXR in the docker and use it? I am trying to get around this. Thanks. @lamiller0

**Comment by lamiller0** [comment]
I see a few other Docker container projects that use OpenEXR that will hopefully give you a few hints:

https://hub.docker.com/r/vistalab/pbrt
https://hub.docker.com/r/ayoburgess/oiio/dockerfile

I know OIIO definitely has a dependency on OpenEXR.

Is this helpful?

**Comment by Google-Autofuzz** [comment]
Thank you, this was helpful. I was able to `cmake` the project successfully. But, I can't find the library file to build the fuzz targets. I used `find . -name "*.a"` to find the library file for Alembic but it gave me nothing. It failed because it couldn't find some of the files that were included in the fuzzers. I used `-Ibuild` and `-Ilib` but still didn't work. The following is the output what I got after trying to build the fuzz target: 

````
-- Configuring done
-- Generating done
-- Build files have been written to: /src/alembic/build
+ cd ..
+ find . -name '*.a'
+ ls
ACKNOWLEDGEMENTS.txt  Doxyfile	    LICENSE.txt  README.txt  bin    cmake     houdini  maya   python
CMakeLists.txt	      FEEDBACK.txt  NEWS.txt	 arnold      build  examples  lib      prman
++ find /src -name '*_fuzzer.cc'
+ for fuzzers in '$(find $SRC -name '\''*_fuzzer.cc'\'')'
++ basename -s .cc /src/alembic_fuzzer.cc
+ fuzz_basename=alembic_fuzzer
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -I. -Ilib -Ibuild /src/alembic_fuzzer.cc -fsanitize=fuzzer -o /out/alembic_fuzzer
In file included from /src/alembic_fuzzer.cc:15:
In file included from lib/Alembic/AbcCoreFactory/All.h:41:
In file included from lib/Alembic/AbcCoreFactory/IFactory.h:40:
In file included from lib/Alembic/AbcCoreAbstract/ReadArraySampleCache.h:41:
In file included from lib/Alembic/AbcCoreAbstract/Foundation.h:40:
In file included from lib/Alembic/Util/All.h:40:
lib/Alembic/Util/Foundation.h:39:10: fatal error: 'Alembic/Util/Config.h' file not found
#include <Alembic/Util/Config.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Fuzzers build failed.
````

**Comment by lamiller0** [comment]
By default it builds the shared (.so) libs, try -DALEMBIC_SHARED_LIBS=OFF  hopefully that will build the static lib correctly for you.

**Comment by Google-Autofuzz** [comment]
````
mkdir build
cd build
cmake -DALEMBIC_SHARED_LIBS=OFF ..
cd ..

find . -name "*.a"
ls

# build fuzzers
for fuzzers in $(find $SRC -name '*_fuzzer.cc'); do
  fuzz_basename=$(basename -s .cc $fuzzers)
  $CXX $CXXFLAGS -std=c++11 -I. -Ilib -Ibuild \
  $fuzzers $LIB_FUZZING_ENGINE \
  -o $OUT/$fuzz_basename
done
````
As what you suggested, I did try ` -DALEMBIC_SHARED_LIBS=OFF` and I still got no "*.a" file from it?

**Comment by Google-Autofuzz** [comment]
I got the static lib to work now. I am able to build the static lib and find it. However, it fails at the point when it tries to find '#include <half.h>` in the `Alembic/Util/Foundation.h` file. I tried to search in the github too and can't find this file. Where is this .h file located? @lamiller0 

````
+ find . -name '*.a'
./lib/Alembic/libAlembic.a
+ ls
CMakeCache.txt	CMakeFiles  CTestTestfile.cmake  Makefile  bin	cmake_install.cmake  install_manifest.txt  lib
++ find /src -name '*_fuzzer.cc'
+ for fuzzers in '$(find $SRC -name '\''*_fuzzer.cc'\'')'
++ basename -s .cc /src/alembic_fuzzer.cc
+ fuzz_basename=alembic_fuzzer
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -I. -Ilib /src/alembic_fuzzer.cc -fsanitize=fuzzer ./lib/Alembic/libAlembic.a -o /out/alembic_fuzzer
In file included from /src/alembic_fuzzer.cc:15:
In file included from /usr/local/include/Alembic/AbcCoreFactory/All.h:41:
In file included from /usr/local/include/Alembic/AbcCoreFactory/IFactory.h:40:
In file included from /usr/local/include/Alembic/AbcCoreAbstract/ReadArraySampleCache.h:41:
In file included from /usr/local/include/Alembic/AbcCoreAbstract/Foundation.h:40:
In file included from /usr/local/include/Alembic/Util/All.h:40:
/usr/local/include/Alembic/Util/Foundation.h:66:10: fatal error: 'half.h' file not found
#include <half.h>
         ^~~~~~~~
1 error generated.
````

**Comment by lamiller0** [comment]
half.h is included as part of OpenEXR2.

**Comment by Google-Autofuzz** [comment]
In my Dockerfile, OpenEXR has been installed. After building alembic, it still cannot find the `half.h` file. I am stuck on this error. Do you have any suggestions? 

Here is my Dockerfile:
````
FROM gcr.io/oss-fuzz-base/base-builder
MAINTAINER miller.lucas@gmail.com
RUN apt-get update && apt-get install -y build-essential python cmake make automake libtool curl git-core wget openexr openexr-viewers libopenexr-dev libilmbase-dev
RUN git clone --depth 1 https://github.com/alembic/alembic alembic
WORKDIR alembic
COPY build.sh alembic_fuzzer.cc *.h $SRC/
````
Here is my BUILD file:
````
# build project
mkdir build
cd build
cmake .. -DALEMBIC_SHARED_LIBS=OFF

make -j2 install

# build fuzzers
for fuzzers in $(find $SRC -name '*_fuzzer.cc'); do
  fuzz_basename=$(basename -s .cc $fuzzers)
  $CXX $CXXFLAGS -std=c++11 -I. -Ilib \
  $fuzzers $LIB_FUZZING_ENGINE ./lib/Alembic/libAlembic.a \
  -o $OUT/$fuzz_basename
done
````

**Comment by lamiller0** [comment]
Depending where you install OpenEXR try:

cmake .. -DALEMBIC_SHARED_LIBS=OFF -DILMBASE_INCLUDE_DIR=/usr/include/OpenEXR2 -DILMBASE_ROOT=/usr/lib64/OpenEXR2

**Comment by lamiller0** [comment]
Based on some issues that were created from autofuzz results it looks like this was resolved.

Thank you!

**Comment by Google-Autofuzz** [comment]
Hi, alembic has not been integrated to OSS-Fuzz yet.

**Comment by lamiller0** [comment]
We've been getting reports from it though?

Whats the difference from being setup and getting Github Issues automatically being created, to being integrated?

**Comment by alsophian** [comment]
Hi Lucas,

I work on one of Google's fuzzing-related teams and I hope I can clear up the confusion.  The bugs you receive from Google-Autofuzz come from our internal fuzzers, which test the version of Alembic in Google's internal repository.  When Autofuzz finds a bug in that version, a Google engineer checks if the same bug is present in this repository's `HEAD`, and that's when we file a bug using the Google-Autofuzz account.

OSS-Fuzz automates this process by constantly running fuzzers against this repository's `HEAD`, and automatically opening and closing issues ([example](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48&can=1&q=Type%3ABug%2CBug-Security)) in the [OSS-Fuzz bug tracker](https://bugs.chromium.org/p/oss-fuzz/issues).  If we integrate Alembic with OSS-Fuzz, you'll automatically receive bug reports for the latest version of Alembic, you won't have to wait for a human to handle them, you don't need to worry about any Google-specific customizations or inconsistencies, and you'll get automatic re-checking when the issue is fixed.  OSS-Fuzz also has a feature offering free [continuous integration](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) fuzzing your project's pull requests.

As part of our [open-source internship program](https://blog.google/inside-google/working-google/google-internships-go-virtual-help-open-source/) this summer, we have some interns working to onboard additional projects to OSS-Fuzz, and we'd like to include Alembic.  If you are okay with this, we will handle all of the integration work, and once it's done you'll start receiving crash reports.

The OSS-Fuzz documentation is at https://google.github.io/oss-fuzz/, and I'll be happy to answer any questions you might have.  Thanks!

Michael
Google Security

**Comment by alsophian** [comment]
Can you assign this issue to @rjotwani (he may have to comment on the issue first)?  He'll be working on the initial integration.  Thanks!

**Comment by lamiller0** [comment]
Yeah, he has to comment first.

**Comment by rjotwani** [comment]
Hi Lucas! I'll be handling OSS-Fuzz integration for Alembic, so hopefully this comment allows you to assign this issue to me.

**Comment by rjotwani** [comment]
Hi Lucas, the PR for Alembic's initial integration has been merged. There's no further work to be done, so please feel free to close this issue.

**Comment by lamiller0** [comment]
Thank you!  I noticed a report earlier today, so it appears to be working.
