### ISSUE TITLE
1.7.12 introduced an ABI breaking change

### ISSUE THREAD

**Issue by svenstaro** [alembic/alembic#243]
I'm the maintainer for alembic in Arch Linux. I just updated alembic 1.7.11 to 1.7.12 and then noticed that applications now show this message:

```
blender: symbol lookup error: blender: undefined symbol: _ZN7Alembic3Abc3v1114OArrayProperty3setERKNS_15AbcCoreAbstract3v1111ArraySampleE
```

So this latest patch version introduced an ABI breaking change. Usually this is very unexpected and should never happen in patch releases without a soname change (the latter usually being part of a  minor version bump).

Please try to keep that in mind for the next releases.

**Comment by lamiller0** [comment]
Does Blender in your distro link against libAlembic.so.1.7 or libAlembic.so?

The ABI was broken on purpose, with the ALEMBIC_VERSION_NS being bumped up, I'll try to be more careful about this in the future.

**Comment by svenstaro** [comment]
It links to `libAlembic.so.1.7 => /usr/lib/libAlembic.so.1.7` which is great as when you bump the minor soname then I'll get a breakage that I can statically check.

**Comment by lamiller0** [comment]
Ok, thanks for the feedback, my plan is to add some reminder comments so in the future when we bump up the version namespace again, we will make sure we at LEAST bump up the minor version as well.

Will close once this is done.

**Comment by lamiller0** [comment]
Added here:

https://github.com/alembic/alembic/commit/a8dc83579be2775b26eaebb569666e28b4ed40e9
