### ISSUE TITLE
windows pyalembic - unresolved externals?

### ISSUE THREAD

**Issue by cbdwtv** [alembic/alembic#244]
Hello,

Currently trying to build 1.7.12 for windows, and running into some unresolved externals with the pyalembic vcxproj:

`
PyICamera.obj : error LNK2019: unresolved external symbol "class Alembic::AbcGeom::v12::ICameraSchema const volatile * __cdecl boost::get_pointe
r<class Alembic::AbcGeom::v12::ICameraSchema const volatile >(class Alembic::AbcGeom::v12::ICameraSchema const volatile *)" (??$get_pointer@$$CDVI
CameraSchema@v12@AbcGeom@Alembic@@@boost@@YAPEDVICameraSchema@v12@AbcGeom@Alembic@@PEDV1234@@Z) referenced in function "public: static struct _obj
ect * __cdecl boost::python::objects::make_instance_impl<class Alembic::AbcGeom::v12::ICameraSchema,struct boost::python::objects::pointer_holder<
class Alembic::AbcGeom::v12::ICameraSchema *,class Alembic::AbcGeom::v12::ICameraSchema>,struct boost::python::objects::make_ptr_instance<class Al
embic::AbcGeom::v12::ICameraSchema,struct boost::python::objects::pointer_holder<class Alembic::AbcGeom::v12::ICameraSchema *,class Alembic::AbcGe
om::v12::ICameraSchema> > >::execute<class Alembic::AbcGeom::v12::ICameraSchema *>(class Alembic::AbcGeom::v12::ICameraSchema * &)" (??$execute@PE
AVICameraSchema@v12@AbcGeom@Alembic@@@?$make_instance_impl@VICameraSchema@v12@AbcGeom@Alembic@@U?$pointer_holder@PEAVICameraSchema@v12@AbcGeom@Ale
mbic@@V1234@@objects@python@boost@@U?$make_ptr_instance@VICameraSchema@v12@AbcGeom@Alembic@@U?$pointer_holder@PEAVICameraSchema@v12@AbcGeom@Alembi
c@@V1234@@objects@python@boost@@@678@@objects@python@boost@@SAPEAU_object@@AEAPEAVICameraSchema@v12@AbcGeom@Alembic@@@Z)
`
I get multiple of these from various objects. I am linking Alembic.lib so I figure there is nothing else I am missing?
I was curious if anyone else ran into this issue or if I messed something up during my setup or cmake command.

My version layout:
Win10
OpenEXR 2.4.0 (latest master commit)
boost 1.63
python 2.7.14

TIA for any advice you have

**Comment by lamiller0** [comment]
Do you ONLY have python 2.7.14 installed, I know something was added to CMake so you can choose which python.

**Comment by cbdwtv** [comment]
Hey @lamiller0 , 

Thanks for the response, that is correct, I only have that version installed.
Double checked to make sure my environment is clean and only pulling in the one python.
I guess it would help to say which cmake I am using too: 3.14.3, but I will grab the latest and see if that does anything.
Cheers

**Comment by lamiller0** [comment]
What CMake command are you using to setup the project?

**Comment by cbdwtv** [comment]
Here is the cmake command:
I had to explicitly turn off boost_use_debug_libs or else I was getting a cmake error because the boost_python_library var had multiple values, and I only wanted to use the release variant of the lib.
```
call cmake -DBoost_USE_DEBUG_LIBS=OFF ^
 -DUSE_PYALEMBIC=ON ^
 -DILMBASE_ROOT=%OPENEXR_ROOT% ^
 -DALEMBIC_PYILMBASE_INCLUDE_DIRECTORY=%OPENEXR_ROOT%\include ^
 -DALEMBIC_PYILMBASE_PYIMATH_LIB=%OPENEXR_ROOT%\lib\PyImath_Python2_7-2_4.lib ^
 -DALEMBIC_PYIMATH_MODULE_DIRECTORY=%OPENEXR_ROOT%\python ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DCMAKE_INSTALL_PREFIX="%BUILD_PATH%" ^
 -G "Visual Studio 14 2015 Win64" ^
 %BUILD_SOURCE_PATH%\repo
```

**Comment by cbdwtv** [comment]
Well, I compiled/built against boost 1.71 and my issue went away....so I will close this ticket.
Thank you for looking into it still! Much appreciated.

**Comment by lamiller0** [comment]
Ahhhh, an issue with the boost version, that sounds familiar now, sorry my memory wasn't jogged earlier.
