### ISSUE TITLE
PyAlembic: segmentation fault

### ISSUE THREAD

**Issue by freder** [alembic/alembic#252]
hi,

I managed to build alembic; also `make test` tells me everything works. however, when I do `import alembic` in the python REPL, I get a segmentation fault. – it's the same python I set `PYTHON_EXECUTABLE` to. 

any ideas what could be going wrong here?

**Comment by lamiller0** [comment]
What version of python?  And what version of boost did you use to create the bindings?

**Comment by freder** [comment]
- boost 1.72
- boost-python 1.72
- python 3.7.3

**Comment by lamiller0** [comment]
I haven't tried that combination, are those all the same as how you built the imath bindings?

**Comment by lamiller0** [comment]
Is it pulling in the correct imath?  Sometimes the system imathmodule.so will be incompatible with the PyImath bindings you built against.

**Comment by lamiller0** [comment]
This is hopefully better with the python 3 changes that went into 1.8.0 rc
