### ISSUE TITLE
[Question] - How to populate table with data, while running migrations?

### ISSUE THREAD

**Issue by vjanz** [alembic/alembic#261]
Hello guys, 
I am using alembic to make migrations, everything is working fine.

One of the tables from my database needs to be populated with data as long as the migrations run, so what I mean is, I have a `CSV` file, and I must populate the fields of `x` table from that csv file.

My question is: Is there a way to populate a specific table in database while running migrations.
Simply said when I run migrations for ex:`alembic upgrade head`, to create all the tables and db, but one of the tables to be pre-populated from a csv file?

Any help is appreciated..
Thank you in advance

**Comment by lamiller0** [comment]
Wrong Alembic project, try this one.

https://github.com/sqlalchemy/alembic
