### ISSUE TITLE
VFX2020 Python 3 support: __nonzero__ is deprecated

### ISSUE THREAD

**Issue by adsk-rivag** [alembic/alembic#273]
Greetings, when building Alembic under the vfx platform CY2020 requirements there were errors on python 3 when testing for truth. Python2's `__nonzero__` is deprecated in favor of `__bool__`. Adding `#ifdef` clauses solved the issue.

**Comment by lamiller0** [comment]
This has been merged into master as part of the 1.8.0 rc
