### ISSUE TITLE
Boost 1.72.0 support: crash on testCollections.py

### ISSUE THREAD

**Issue by adsk-rivag** [alembic/alembic#274]
Greetings, when `Alembic 1.7.5` is built with `boost::python 1.72.0` (cannot confirm nor deny other versions), regardless of python version, found that the test `testCollections.py` would crash on the line: `group.getSchema().createCollection("cool", md, ts)`.

Upon debugging, found that the variable `ts`, which looks complete upon inspection, fails to arrive as an `Argument` of `createCollection`, `m_variant.timeSamplingPtr` holding junk bytes.

Tracked this into the boost function `construct()`: https://github.com/boostorg/python/blob/develop/include/boost/python/converter/implicit.hpp:29, line 33 receives a clone `TimeSamplingPtr` (reference count: 1) on the `get_source` variable. This is passed into the `Argument`, which only holds a pointer to it. `get_source` leaves scope and the pointed-to data is lost.

Please confirm the issue, as for fixes, was looking into boost python policies to avoid having this middleman `shared_ptr` that gets destroyed immediately, but would prefer advice, e.g. is `Argument` read-only? then holding a full `shared_ptr` would keep the reference alive and be enough.

**Comment by lamiller0** [comment]
I think a better solution is to eventually drop the createCollection method on polymesh and subd and instead create it via normal child/parent OObject creation like everything else.

**Comment by lamiller0** [comment]
nvm, I misunderstood, this wasnt through the OPolyMesh or OSubd.

I've been able to recreate the issue, and am trying a few things.

**Comment by OEP** [comment]
I've been able to reproduce this same problem using Alembic 1.7.10 and Boost 1.73.0 on Windows using Visual Studio 2017 (following the VFX platform guidance).

```
> python -m trace --trace testCollections.py
...
testCollections.py(75):     group.getSchema().createCollection("cool", md, ts)

>echo %errorlevel%
-1073741819
```

That was the only test I noticed crashing. I was investigating one of my own tests which also happens to involve a TimeSampling being passed over Boost.Python, into the `OXform`. In that case, it looked like an stl vector was getting initialized from junk data leading to a `vector<T> too long` message. These two crashes seemed related so I thought I'd include that as pertinent info.

I was upgrading from Boost 1.61 which seems to pass this test. Let me know if I can provide any more information.

**Comment by plattfot** [comment]
Adding another data point. Able to reproduce the exact same behavior with `alembic-1.7.16`,`boost-1.73.0`, `python-2.7.13` using `gcc-9.4.0`. Test does not segfault when I'm use `python-3.7.7` but that's probably just luck.

**Comment by Arbeyem** [comment]
I was able to reproduce the issue as well using Alembic 1.7.10 going from Boost 1.61 to 1.73.  I found this interesting bit in the changes of boost_python between those releases:

```include/boost/python/object/py_function.hpp 
@@ -135,7 +135,11 @@ struct py_function
    {}

    py_function(py_function const& rhs)
-        : m_impl(rhs.m_impl)
+#if defined(BOOST_NO_CXX11_SMART_PTR)
+      : m_impl(rhs.m_impl)
+#else
+      : m_impl(std::move(rhs.m_impl))
+#endif


@@ -164,7 +168,11 @@ struct py_function
    }

 private:
+#if defined(BOOST_NO_CXX11_SMART_PTR)
    mutable std::auto_ptr<py_function_impl_base> m_impl;
+#else
+    mutable std::unique_ptr<py_function_impl_base> m_impl;
+#endif
```

I built with 'BOOST_NO_CXX11_SMART_PTR' defined and ran the test again without crashing this time.  The change from auto_ptr to unique_ptr seems to explain @adsk-rivag 's findings.
