### ISSUE TITLE
Python 3: Python tests are not python 2 + 3 compatible

### ISSUE THREAD

**Issue by adsk-rivag** [alembic/alembic#276]
Greetings, Alembic's python tests are only compatible with python 2. Changes should be minimal, expect most, if not all of them to be about adding parentheses to the print function used on these tests.

**Comment by adsk-rivag** [comment]
There is also a couple has_key() uses, a couple deprecated exception syntax, some deprecated print syntax (trailing comma), a few incomplete iterators (created separate issue),  classes lack a bool() operator (created separate issue)

**Comment by lamiller0** [comment]
Thanks for the hints!

**Comment by lamiller0** [comment]
I'm slowly going through these and converting them over to use unittest, I estimate I'm about 50-60% through.

**Comment by lamiller0** [comment]
The tests were converted over in the python3 fixes branch and merge into master as part of 1.8.0 rc
