### ISSUE TITLE
PyAlembic_Test rpath issues on Mac

### ISSUE THREAD

**Issue by adsk-rivag** [alembic/alembic#277]
Greetings, it could be due to local environment, but the test `PyAlembic_Test` is having issues locating the dependencies the project is built with, when built on osx.

Using cmake Unix Makefiles to build the project, and ctest to test the project and without modifying the cmake scripts in order to edit how ctest will be setup. The test has correct rpaths only to the openexr/ilmbase library it was built with. Python and boost do not point to their libraries/frameworks correctly, this may cause the test to load system python's python 2 rather than the version 3 it may have been built with.

CTest from CMake 3.17 does not seem to pass environment into the individual tests (unlike other platforms). So, while it is possible to run failing tests with custom environment manually -outside of CTest, and have them run. It is not possible as part of a CTest run. In this case DYLD_FRAMEWORK_PATH and DYLD_LIBRARY_PATH are needed to fix discovery of libraries, and PYTHONPATH to fix discovery of python extensions (alembic and imath/iex). 

The build possibly copies the rpaths from the given PyIlmBase, even if it could have them wrong, and despite Alembic having defined its own set of dependency paths that have to be correct for the project wouldn't build otherwise.

The issue also happens on Windows and Linux, but Windows is very easy to fix by modifying PATH, and Linux with LD_LIBRARY_PATH within the session, as they get inherited from CTest into the individual tests.

So, although there are workarounds, having the rpaths correctly set to the given dependencies would be a better setup.

**Comment by lamiller0** [comment]
Is this any better in the 1.8.0 release candidate currently on master?
