### ISSUE TITLE
PyAlembic_Python_TEST should mention prerequisites

### ISSUE THREAD

**Issue by adsk-rivag** [alembic/alembic#278]
The test may fail silently. The test requires visibility of `python`, `boost` and `ilmbase` dll/so/dylibs on `((DY)LD_)PATH`. Because it runs `pyalembic` it also needs visibility of `alembic.so` and `imath/iex.so` on `PYTHONPATH`. If the python install that it uses has all of these already installed then the actual testing will run, however, if not, and the files are each on their build output folders, there will be errors loading modules as `sys.path` will be incomplete.

Despite of the errors, and despite printing a stack trace, I have seen `ctest` report the test passed.

In addition, errors on `main.cpp` may happen from lack of configuration as well as it has embedded python code as strings. On Windows, the C++ part of the test seems to set up `PYTHONPATH` with a folder relative to the test, and it seems it is set up so that it works if the build is done in-source. If the build is done out of the source tree, the folders should not match and the import strings passed into the interpreter won't be able to find the test scripts launched by the c++ test. There is a file `run_tests` that seems better configured on unix.

As configuring all of this automatically may be too much work, just for edge cases, simply adding documentation would be good enough. First, the test must be ensured to fail when finding errors to raise the alert. Second, the test should always print its set-up documentation so that anyone reading the logs will understand what the issue likely is and may set up the environment before calling `ctest`.

**Comment by lamiller0** [comment]
I'm currently (and slowly) converting these over to use the native python unittest instead of the current scaffolding.
I'm fairly certain I'll be able to configure the CMake to be able to import alembic.so from the correct built place, figuring out the same stuff for importing imath is on my TODO list.

If you are curious about my progress you can watch:
https://github.com/lamiller0/alembic/tree/python3_fixes

**Comment by lamiller0** [comment]
This has been merged into master.
