### ISSUE TITLE
VFX2020 Python 3 support: iterator requires __iter__ and __next__

### ISSUE THREAD

**Issue by adsk-rivag** [alembic/alembic#279]
Greetings, iterators requirements on python 3 have changed. Currently, Alembic is set up with iterators that implement `next`, `next` is deprecated in Python 3 in favor of the object having both `__iter__` and `__next__`, `__iter__` needs to point to self and `__next__` is just a rename of `next`.

Boost::python has an iterator construct to ease this up, but it seems Alembic defines the functions manually.

**Comment by lamiller0** [comment]
This is now in the latest 1.8.0 beta
