### ISSUE TITLE
Question about working with multiple bases.

### ISSUE THREAD

**Issue by Wim-De-Clercq** [alembic/alembic#299]
Imagine `base1` has revisions **A** --> **B** --> **C**
Imagine `base2` has just revision **B'**

The **B'** depends on **B**.
But the **C** revision does a change which would break applying **B'**.

I can make an `alembic upgrade` work if I do:
```
alembic upgrade base2@head
Executes: A, B, B'
alembic upgrade base1@head
Executes: C
```
This, however, requires people who do the alembic upgrade to have specific knowledge of which branch to do when, which I would like to avoid. Imagine if there are more than 2 bases, the set of instructions to execute gets complicated quickly.

By default `alembic upgrade heads` would execute `A, B, C, B'` which wouldn't work.
Is there something I can declare on **B'** to have priority to run right after **B**, before **C** to make this work?

**Comment by lamiller0** [comment]
I believe you have the wrong Alembic project.

Try this one:
https://bitbucket.org/zzzeek/alembic/src/master/
