### ISSUE TITLE
Missing bracket in PyAlembic CMakeLists.txt?

### ISSUE THREAD

**Issue by Narann** [alembic/alembic#30]
I've found a missing bracket [here](https://github.com/alembic/alembic/blob/master/python/PyAlembic/CMakeLists.txt#L158). It prevent `cmake` to prepare the build.

Just FYI.

Keep the good work!

**Comment by AWhetter** [comment]
This got fixed in e03d5eb2cdfd5bc068e3499c22462863e742cc7f so I believe it can be closed.
