### ISSUE TITLE
No module named alembic.__main__; 'alembic' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by MosheVai** [alembic/alembic#300]
I am trying to run alembic inside a venv inside of WSL-2 Ubuntu.
I am using using the following command:
```
python -m alembic revision --autogenerate -m "create foo"
```
resulting in 
```python-exception
/home/ubuntu/code/my-repo/venv/bin/python: No module named alembic.__main__; 'alembic' is a package and cannot be directly executed
```

python version: Python 3.7.8
alembic version:  1.4.0

**Comment by lamiller0** [comment]
I believe you have the wrong Alembic project.

Try this one:
https://bitbucket.org/zzzeek/alembic/src/master/
