### ISSUE TITLE
[QUESTION] Is it possible to mark a revision as a "milestone"?

### ISSUE THREAD

**Issue by dhermes** [alembic/alembic#301]
For example, consider a scenario where a column `users.name` is being renamed to `users.username`:

```
-- Revision 000000000001
CREATE TABLE users (
    id UUID NOT NULL,
    "name" TEXT NOT NULL,
);
-- Revision 000000000002
ALTER TABLE users
  ADD COLUMN username TEXT;
-- Revision 000000000003
ALTER TABLE users
  ALTER COLUMN username
  SET NOT NULL; -- Don't do this on a large table!
-- Revision 000000000004
ALTER TABLE users
  DROP COLUMN name;
```

During a rolling update of the codebase, if the active revision was `000000000001`, then applying all the migrations up to `000000000004` would cause the current code to fail anywhere that it referenced `users.name`.

Is there some kind of "milestone" metadata to set on `000000000002` to say "don't apply migrations past this point"? In this contrived case, application owners would need to
- apply up to `000000000002`
- deploy code that starts writing to `users.username`
- make sure some offline job runs to backfill `users.username` with the contents of `users.name`
- apply up to `000000000003`
- deploy code that no longer depends on `users.name`
- apply up to `000000000004`

**Comment by lamiller0** [comment]
Wrong Alembic, try:

https://bitbucket.org/zzzeek/alembic

**Comment by dhermes** [comment]
Whoops! Thanks for humoring me.
