### ISSUE TITLE
Type annotations return SyntaxError

### ISSUE THREAD

**Issue by nisbus** [alembic/alembic#304]
Having a method like this in the code where base is throws a SyntaxError when trying to create a revision:

```python
def remove_application(self, application_id: str) -> bool:
```

```
def remove_application(self, application_id: str) -> bool:
                                               ^
SyntaxError: invalid syntax
```

**Comment by sideband** [comment]
Do you mean alembic the database migration tool? This repo/list is for
alembic the visual effects file format.

It may be that you're somehow using python2 which doesn't seem to support
specifying argument or return types.

**Comment by lamiller0** [comment]
Yeah, this looks like it needs to go over here:

https://bitbucket.org/zzzeek/alembic/src/master/
