### ISSUE TITLE
Build of 1.7.13 fails because of -werror

### ISSUE THREAD

**Issue by virtualritz** [alembic/alembic#307]
This is essentially the same issue as #293:
Just curious but do you not check the build with `-werror` yourself before tagging a release or how can this slip?

```
/Users/moritz/code/vcpkg/buildtrees/alembic/src/e708d838ae-dc6119ffed.clean/lib/Alembic/AbcMaterial/Tests/WriteGeometryWithMaterials.cpp:37:21: error: unused variable 'g_uindices' [-Werror,-Wunused-const-variable]
const Abc::uint32_t g_uindices[] = {
```

**Comment by lamiller0** [comment]
I thought I was, but something must be off with either the CMake setup, or gcc.

**Comment by virtualritz** [comment]
Well, this is inside a test. Maybe you just ran `make` but not `make test`? :)

**Comment by lamiller0** [comment]
With CMake, make test runs the test suite it doesn't build it.

Turns out the version of gcc I was using (6.3) wasn't flagging this but clang (10) is, I've got a setup that tries to use both now.

**Comment by virtualritz** [comment]
Ah, I didn't know. It was just a wild guess. So you are saying gcc doesn't warn about the unused variable and hence it doesn't turn into an error, right?

**Comment by lamiller0** [comment]
Correct.

This issue also caused me to dig into our Travis CI config, and realize that should also be bumped up as well since it's currently on an EOL config.

**Comment by virtualritz** [comment]
Any ETA for this in a release? 😜
I am working on some code in Rust that uses `alembic-rs` (wrapper) which depends on the `vcpkg` for Alembic which depends on the latest official release from this repository. See [here](https://github.com/microsoft/vcpkg/issues/13371).

**Comment by lamiller0** [comment]
I was aiming for 9-6 but WIndows flagged a couple of minor issues in the fuzzer tests, I did a release yesterday.

**Comment by virtualritz** [comment]
Thanks for fixing this & the update!
