### ISSUE TITLE
Build of 1.7.15 fails on Linux because of -werror=deprecated-copy

### ISSUE THREAD

**Issue by virtualritz** [alembic/alembic#309]
Forwarding [a report](https://github.com/microsoft/vcpkg/issues/13371#issuecomment-691833248) from a `vcpkg` issue that was tracking #307.
The user was reportedly building against a3ad9600f5b5299dffda3d285aeab89023d2d801.

> @virtualritz
> Thanks for your above information and also for moving this issue forward.
> In fact, I have tested the latest version 1.7.15 two days ago and it can be built successfully on Windows and failed on linux and osx.
> 
> On Linux:
> 
> ```
> /home/vruil/vcpkg/buildtrees/alembic/src/9023d2d801-71fc0d388b.clean/lib/Alembic/AbcGeom/ICamera.h: In copy constructor ‘Alembic::AbcGeom::v12::ICameraSchema::ICameraSchema(const Alembic::AbcGeom::v12::ICameraSchema&)’:
> /home/vruil/vcpkg/buildtrees/alembic/src/9023d2d801-71fc0d388b.clean/lib/Alembic/AbcGeom/ICamera.h:101:17: error: implicitly-declared ‘Alembic::AbcGeom::v12::ICameraSchema& Alembic::AbcGeom::v12::ICameraSchema::operator=(const Alembic::AbcGeom::v12::ICameraSchema&)’ is deprecated [-Werror=deprecated-copy]
>   101 |         *this = iCopy;
>       |                 ^~~~~
> /home/vruil/vcpkg/buildtrees/alembic/src/9023d2d801-71fc0d388b.clean/lib/Alembic/AbcGeom/ICamera.h:98:5: note: because ‘Alembic::AbcGeom::v12::ICameraSchema’ has user-provided ‘Alembic::AbcGeom::v12::ICameraSchema::ICameraSchema(const Alembic::AbcGeom::v12::ICameraSchema&)’
>    98 |     ICameraSchema(const ICameraSchema& iCopy)
>       |     ^~~~~~~~~~~~~
> cc1plus: all warnings being treated as errors
> ```

**Comment by virtualritz** [comment]
The macOS build failure they mentioned is not related to Alembic and I omitted it therefore.

**Comment by virtualritz** [comment]
On that note: I suggest testing tagged releases of Alembic as building _with_ `-werror` but _removing_ it from the build itself. I.e. make it require a flag/option to CMake so this constant stream of issues related to this and all the downstream breakage it causes stops.

The `vcpkg` of Alembic has now been broken since (at least) two months because of this. For no good reason. And the only reason you know about this one is because someone (me) reported it.
Alembic is narrow use case enough that you will only hear about this randomly if someone happens to use package manager and takes the time to bother.

Studios or vendors that use Alembic internally will just work around this/never encounter it as they may simply disable `-werror` or use their own method of building. I.e. no gain for anyone but a lot of noise for you, the maintainers.

If you make sure tagged releases build fine on all supported platforms _with_ `-werror` that should be enough – it's better QA than most 3rd party libs I use offer. :)

**Comment by lamiller0** [comment]
-werror is enabled when doing a Debug build here:

https://github.com/alembic/alembic/blob/master/CMakeLists.txt#L141

 I did do debug builds with gcc48, gcc63, and llvm 10 in order to try and find your previous issue.
What compiler version tripped up this time, and are you going through CMake?

**Comment by virtualritz** [comment]
Maybe you missed the first line? I am _forwarding_ [a report](https://github.com/microsoft/vcpkg/issues/13371#issuecomment-691833248). I can't answer these questions.

**Comment by lamiller0** [comment]
I saw that in the report, and I do not know anything about vcpkg to know what CMake line its using.

Since I have not yet been successful in recreating this issue with the compilers I currently have access to, and for the Debug builds -Wno-deprecated is provided with the -Werror as was mentioned previously, I need more info.

Can @NancyLi1013 provide this info?

**Comment by virtualritz** [comment]
> Can @NancyLi1013 provide this info?

I guess so. I didn't know about `vcpkg` until two weeks ago. I learned about it when a Rust crate that wraps Alembic broke because it depends on `vcpkg` to install it. So I traced the breakage all the way here. Everything works for me now on macOS & Windows which are my two target platforms. Read: I'm not affected by *this* issue.

I just thought it would be kind to at least forward the report as judging from turnaround times on issue replies on the `vcpkg` repo these folks seem to have not enough resources to deal with this timely. And I mean that in a very caring way.

**Comment by NancyLi1013** [comment]
Sorry for the delay.
@lamiller0 
Could you please help list what the detailed information that need to get from me?

Can you build `Alembic ` on linux successfully with the latest version? @virtualritz , @lamiller0 

If this issue only happens on my side, I will try to test this again on a clean environment.

Thanks.

**Comment by lamiller0** [comment]
@NancyLi1013 Yes, I've built it successfully with gcc4.8, gcc6.3, and llvm10 on Linux.

**Comment by lamiller0** [comment]
I suspect that this is the same issue:

https://github.com/alembic/alembic/issues/312

**Comment by NancyLi1013** [comment]
Hi @lamiller0 
Sorry for the delay. 

I used Ubuntu 18.04.01 with gcc 9.2.1 to build `Alembic ` on Linux. It failed with the same error:

```
/home/user/vcpkg/buildtrees/alembic/src/9023d2d801-71fc0d388b/lib/Alembic/AbcGeom/ICamera.h:101:17: error: implicitly-declared ‘Alembic::AbcGeom::v12::ICameraSchema& Alembic::AbcGeom::v12::ICameraSchema::operator=(const Alembic::AbcGeom::v12::ICameraSchema&)’ is deprecated [-Werror=deprecated-copy]
  101 |         *this = iCopy;
      |                 ^~~~~
/home/user/vcpkg/buildtrees/alembic/src/9023d2d801-71fc0d388b/lib/Alembic/AbcGeom/ICamera.h:98:5: note: because ‘Alembic::AbcGeom::v12::ICameraSchema’ has user-provided ‘Alembic::AbcGeom::v12::ICameraSchema::ICameraSchema(const Alembic::AbcGeom::v12::ICameraSchema&)’
   98 |     ICameraSchema(const ICameraSchema& iCopy)
      |     ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
Which seems different from the error mentioned #312. 

Could you please help us take a look again?

Thanks.

**Comment by lamiller0** [comment]
Do you have the compile flags and the CMake flags you use for setup?
gcc9 isn't something that I have easy access to yet.

**Comment by NancyLi1013** [comment]
This is the flags that we used:

```
if(NOT VCPKG_TARGET_IS_WINDOWS)
    # In debug mode with g++, alembic defines -Werror
    # so we need to disable some warnings to avoid build errors
    list(APPEND GXX_DEBUG_FLAGS
        -DCMAKE_CXX_FLAGS_DEBUG=-Wno-deprecated
        -DCMAKE_CXX_FLAGS_DEBUG=-Wno-error=implicit-fallthrough
    )
endif()
```
Except this, it seems there are no additional flags.

**Comment by chausner** [comment]
I have a PR pending for the vcpkg port which should work around these issues in the latest release of alembic: https://github.com/microsoft/vcpkg/pull/21041. Of course, if we can fix it in alembic itself in the future, that would be ideal.

**Comment by simogasp** [comment]
that's nice, we can have alembic available on vcpkg again even before the next release that will solve this issue, one way or another.

**Comment by lamiller0** [comment]
Many of the initially reported warnings are hopefully fixed in the latest master and will go out in the next release.
