### ISSUE TITLE
ILMbase build errors

### ISSUE THREAD

**Issue by ahemberger** [alembic/alembic#327]
Hi there;

I'm trying to build out the latest version of Alembic on Windows. I'm getting tripped up with cmake because of its expectations about ilmbase, which seems to differ from what the current version of openexr generates. 

Cmake initially fails to find ilmbase, but I can manually point it to the libraries openexr generates. Where I'm getting hung up is the following:

> CMAKE SYSTEM NAME: Windows
The install dir is C:/Program Files (x86)/Alembic
ILMBASE_ROOT is undefined
CMake Error at cmake/Modules/FindIlmBase.cmake:134 (STRING):
  STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
  CMakeLists.txt:230 (INCLUDE)

Am I doing something obviously wrong, or might I ask for some advice as to how I might encourage this build along? 

Thank you!

**Comment by lamiller0** [comment]
What flags are you passing in to CMake?  You may need to specify ILMBASE_ROOT and ILMBBASE_INCLUDE_DIR.

**Comment by ahemberger** [comment]
Hi Lucas!

Let's see, for those two vars I'm doing this:

ILMBBASE_INCLUDE_DIR = C:/Program Files (x86)/OpenEXR/include
ILMBASE_ROOT  = C:/Program Files (x86)/OpenEXR

Digging into the cmake scripts, I can see it's trying to figure out a version for ilmbase - but it seems that ilmbase itself might no longer be a thing (?) so I'm guessing at the version to set it manually, and my guess is 2_5 (openexr currently generates a few 2_5 dlls for IEX and ilmThread, but iMath - where I'm told Half exists - is 3_0. 

Using these options seems to make cmakeUI's config output happy, but when I generate and build the result, I get a ton of errors about half.h not being found, so I'm clearly still doing something wrong. 

(if it's not painfully obvious, my strengths lie more in an artist trying to use alembic rather than a developer trying to build it, so apologies if my questions are rudimentary). 

Thanks!

**Comment by ahemberger** [comment]
(And, to be clear, I'm starting totally fresh here building Alembic...I have no previous experience or builds for either it or openexr laying around. I've cloned down and built the latest version of openexr - which seems to build fine. It seems - though I could be mistaken - that Alembic is expecting something different than what the openexr build is producing?)

**Comment by lamiller0** [comment]
Does this exist for you?

C:/Program Files (x86)/OpenEXR/include/half.h

If not, then where IS half.h?  Your include path should be THAT directory.

**Comment by ahemberger** [comment]
Setting ILMBBASE_INCLUDE_DIR  to C:\Program Files (x86)\OpenEXR\include\Imath seems to get me further along the build path, though now I'm seeing this error:

>Error	LNK1107	invalid or corrupt file: cannot read at 0x2F8	Alembic	C:\Program Files (x86)\OpenEXR\bin\Imath-3_0.dll	1	

This complaint seems to be about Imath-3.0.dll. I must still be doing something incorrectly...

**Comment by lamiller0** [comment]
Hmmm, 

Does:
 C:\Program Files (x86)\OpenEXR\bin\Imath-3_0.dll

exist?

I'm a little suspicious about the weird looking 1 after it....

**Comment by ahemberger** [comment]
Indeed it does exist, sir.

**Comment by lamiller0** [comment]
Could it be something weird like the dll you are using is only 32 bit, but you are doing a 64 bit build?

**Comment by ahemberger** [comment]
Hi sir;

I'm not confident enough in my ability to navigate this adroitly to say I haven't inadvertently done something weird, so what you're suggesting isn't out of the realm of possibility! But while I dig more deeply into trying to troubleshoot that particular question, may I also re-highlight the thread on the openexr thread I mentioned earlier (which, again, is [here](https://github.com/AcademySoftwareFoundation/openexr/issues/900), specifically Larry Gritz's suggestion that the most recent version of openexr may require other downstream packages to be modified in order to build properly? I ask because I'd like to clarify whether - in light of that comment - what I'm trying to do SHOULD work straightforwardly. 

Again, I'm starting totally fresh, with the latest openexr and the latest Alembic, and I worry that there might be an inherent compatibility issue.

**Comment by ahemberger** [comment]
Oh man, I think I figured something out. I discovered I can install openexr (2.5) via vcpkg, which in turn allows me to build the latest version of alembic. 

I think there may still be a hiccup with regards to the latest version of openexr (as offered on github), but for the time being at least I am unstuck I think.

**Comment by meshula** [comment]
Hi, I'm on the OpenEXR team. The Alembic cmake scripts are explictly looking for IlmBase, which is part of OpenEXR2. OpenEXR3, at the top of tree, no longer has an IlmBase library, and the associated libraries, Half, Iex, IexMath, IlmThread and so on. For OpenEXR3, Half and Imath were moved into a new repo, https://github.com/AcademySoftwareFoundation/Imath. The other libraries that made up IlmBase were either moved into OpenEXR or removed, because they have been superceded by C++11 std features and don't make sense to keep around in OpenEXR for new software, as they duplicate a small subset of functionality that has been standard for a decade now.

VfxPlatform for 2021 migrated from the OpenEXR 2 series to OpenEXR 3.

@lamiller0 These days Imath installs a cmake.config file which means that in a conventional installation, there's no custom find scripts necessary, a find_package(Imath) should just work. Perhaps the way forward is to start with a find_package(Imath) which will detect the latest version, and fall back to Alembic's own find when support for OpenEXR2 is required. Unfortunately the transition is a bit prickly. As far as I recall, Alembic only uses Imath, not Iex, or IlmThread, etc., so perhaps this migration might not be too terrible?

**Comment by lamiller0** [comment]
Thanks for the hint @meshula I'll give it a shot (most likely as part of https://github.com/lamiller0/alembic/tree/python3_fixes).

**Comment by lamiller0** [comment]
@meshula Poking around https://github.com/AcademySoftwareFoundation/Imath a bit, I noticed that there doesn't appear to be any official releases yet, is this correct?

**Comment by meshula** [comment]
Hmm, you're right; something to follow up with the TSC. Now might be a good time to dry run a migration in order that we know the new Imath meets your needs, then coordinate with the TSC on a 1.0 release for Imath.

**Comment by lamiller0** [comment]
@meshula  Dry run went fairly well, I was able to get both Alembic and PyAlembic using Imath 3, and the Alembic unit tests passing with a bit of hackery.  I just need to polish the remaining warts.

**Comment by meshula** [comment]
"a bit of hackery" :) Anything for us to look at at this end?

**Comment by lamiller0** [comment]
The issue with the include files going into OpenEXR is already in a pull request here:
https://github.com/AcademySoftwareFoundation/Imath/pull/88

The other bit is on my end making sure to use Imath::PyImath_Python2_7 or Imath::PyImath_Python3_7.

**Comment by lamiller0** [comment]
I've got this building now, the choice to build python 3 or python 2 bindings is controlled by the variable PYALEMBIC_PYTHON_MAJOR (which defaults to 3).  I've tested it both against Imath 3 and the older Imath 2.

The README still needs to be updated with newer examples of how to build based on what libraries you have.

**Comment by lamiller0** [comment]
This has been merged into master as part of the 1.8.0 rc
