### ISSUE TITLE
No templates in template directory or documentation

### ISSUE THREAD

**Issue by chorlick** [alembic/alembic#328]
Installed alembic with pip on windows
Requirement already satisfied: alembic in c:\users\chorl\appdata\roaming\python\python37\site-packages (1.5.0)
Requirement already satisfied: SQLAlchemy>=1.3.0 in<full path>\appdata\roaming\python\python37\site-packages (from alembic) (1.3.22)
Requirement already satisfied: Mako in c:\users\chorl\appdata\roaming\python\python37\site-packages (from alembic) (1.1.4)
Requirement already satisfied: python-editor>=0.3 in <full path>\appdata\roaming\python\python37\site-packages (from alembic) (1.0.4)
Requirement already satisfied: python-dateutil in <full path>\appdata\roaming\python\python37\site-packages (from alembic) (2.8.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in <full path>\appdata\roaming\python\python37\site-packages (from Mako->alembic) (1.1.1)
Requirement already satisfied: six>=1.5 in <full path>\appdata\roaming\python\python37\site-packages (from python-dateutil->alembic) (1.15.0)

There are no templates in the templates directory, in fact there are no templates. I also dont see any template documentation on the alembic site. 

Available templates:

Traceback (most recent call last):
  File "<full path>\env\Scripts\alembic-script.py", line 11, in <module>
    load_entry_point('alembic==1.5.0', 'console_scripts', 'alembic')()
  File "<full path>\env\lib\site-packages\alembic\config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "<full path>\env\lib\site-packages\alembic\config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "<full path>\env\lib\site-packages\alembic\config.py", line 533, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "<full path>\env\lib\site-packages\alembic\command.py", line 17, in list_templates
    for tempname in os.listdir(config.get_template_directory()):
FileNotFoundError: [WinError 3] The system cannot find the path specified: '<full windows path>\\env\\lib\\site-packages\\alembic\\templates'

**Comment by lamiller0** [comment]
Wrong project, please try:

https://github.com/sqlalchemy/alembic/issues
