### ISSUE TITLE
AlembicOgawa sometimes export corrupted archives.

### ISSUE THREAD

**Issue by ainaerco** [alembic/alembic#33]
Some Ogawa archives exports corrupted in Maya. I've checked Alembic Ogawa OStream::write function and it seems that after "mData->stream->write((const char *)iBuf, iSize).flush()"       stream->seekp(0, std::ios_base::end) makes a huge leap (like 1000000 * iSize) and stream->seekp(0, std::ios_base::cur) becomes negative. It repeats for same maya scene and same frame range.

**Comment by lamiller0** [comment]
Is this on Windows with Visual Studio 2010?

**Comment by ainaerco** [comment]
Windows 7, Compiled with Visual Studio 2013 Windows7.1SDK

**Comment by lamiller0** [comment]
Is it this issue?
https://connect.microsoft.com/VisualStudio/feedback/details/627639/std-fstream-use-32-bit-int-as-pos-type-even-on-x64-platform

**Comment by ainaerco** [comment]
Well, it seems so. We are using Maya 2014 and plugin should be compiled with VS2010. What may you suggest to solve this problem?

**Comment by ainaerco** [comment]
Found solution on the same page. It seems to be working, thank you.
How to implement Microsoft's fix yourself:
Assuming VC2010 is installed on your drive C:,
In file c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\iosfwd
Change line #65
From: return ((streamoff)(_Myoff + _FPOSOFF(_Fpos)));
To    : return ((streamoff)(_Myoff + _Fpos));

**Comment by ainaerco** [comment]
Maybe it is better to implement writing using boost::iostreams?

**Comment by meshula** [comment]
please less boost, not more ;)

**Comment by lamiller0** [comment]
There is no plan to officially use boost::iostreams in the main Alembic library anytime soon.
Reintroducing a boost dependency because of a Windows bug would be most unfortunate.

**Comment by ainaerco** [comment]
And that's smart enough, because boost iostreams uses same functions from std.
