### ISSUE TITLE
[Question] How to add a Property to an alembic object in c++

### ISSUE THREAD

**Issue by ben-mkiv** [alembic/alembic#330]
Hi,

i'm trying for hours now to get this solved somehow.

I have an alembic file which consists of an arbitrary number of curve objects, the curves need one additional scalar property attached to them. named "groom_group_id" and a int32 value

```
ScalarProperty name=groom_group_id;interpretation=;datatype=int32_t;arraysize=1;numsamps=1
```

My personal favor would be to do it in c++, so i've started to rip apart the AbcStitcher tools `visitObjects()` method as i thought this would be a good place to just insert the necessary data. (the stitcher should just stitch the file to itself and insert a ScalarProperty to the Curves CompoundProperty...

The index that i want as "metadata" comes from an string vector where i add the object name, so my only issue is handling the alembic properties...

However i'm lost with creating the ScalarProperty and appending it to the data.

Any help is appreciated :)

This is the files hierarchy
```ScalarProperty name=.childBnds;interpretation=box;datatype=float64_t[6];arraysize=6;numsamps=1
Object name=/Hair
  CompoundProperty name=.xform;schema=AbcGeom_Xform_v3
    ScalarProperty name=.inherits;interpretation=;datatype=bool_t;arraysize=1;numsamps=1
    ScalarProperty name=.ops;interpretation=;datatype=uint8_t;arraysize=1;numsamps=1
    ScalarProperty name=.vals;interpretation=;datatype=float64_t[16];arraysize=16;numsamps=1
    ScalarProperty name=isNotConstantIdentity;interpretation=;datatype=bool_t;arraysize=1;numsamps=1
    CompoundProperty name=.userProperties;schema=
      ArrayProperty name=groom_version_major;interpretation=;datatype=int32_t;arraysize=1;numsamps=1
      ArrayProperty name=groom_version_minor;interpretation=;datatype=int32_t;arraysize=1;numsamps=1
  ScalarProperty name=visible;interpretation=;datatype=int8_t;arraysize=1;numsamps=1
Object name=/Hair/Main
  CompoundProperty name=.geom;schema=AbcGeom_Curve_v2
    ScalarProperty name=.selfBnds;interpretation=box;datatype=float64_t[6];arraysize=6;numsamps=1
    ArrayProperty name=P;interpretation=point;datatype=float32_t[3];arraysize=1774500;numsamps=1
    ArrayProperty name=nVertices;interpretation=;datatype=int32_t;arraysize=27300;numsamps=1
    ScalarProperty name=curveBasisAndType;interpretation=;datatype=uint8_t[4];arraysize=4;numsamps=1
Object name=/Hair/Tail
  CompoundProperty name=.geom;schema=AbcGeom_Curve_v2
    ScalarProperty name=.selfBnds;interpretation=box;datatype=float64_t[6];arraysize=6;numsamps=1
    ArrayProperty name=P;interpretation=point;datatype=float32_t[3];arraysize=18000;numsamps=1
    ArrayProperty name=nVertices;interpretation=;datatype=int32_t;arraysize=2000;numsamps=1
    ScalarProperty name=curveBasisAndType;interpretation=;datatype=uint8_t[4];arraysize=4;numsamps=1```

**Comment by lamiller0** [comment]
To create the scalar property:

Alembic::Abc::OInt32Property prop(curveObj.getSchema(), "groom_group_id");

However based on the name it sounds like this is for Unreal grooms, if so I don't think you want it as a scalar property parented directly beneath the parent, instead you probably want it in the arbitrary geom params, created like this:

Alembic::AbcGeom:OInt32GeomParam prop(curvrObj.getSchema().getArbGeomParams(), "groom_group_id", false, 
   Alembic::AbcGeom::kConstantScope, 1);

**Comment by ben-mkiv** [comment]
Thanks for your quick response, yes it's supposed to be imported in Unreal later, (blender isn't able to add the groom_group_id as any custom property on the hair system gets ignored ;()

and you are probably correct, unreal won't recognize the groom_group_id on the curve object, however now i'm stuck with the GeoParams, as i can't figure out how to fill this with data.

and i'm not quite sure if my hierarchy is correct now, here's one object
```
Object name=/Hair/Tail
  CompoundProperty name=.geom;schema=AbcGeom_Curve_v2
    ScalarProperty name=.selfBnds;interpretation=box;datatype=float64_t[6];arraysize=6;numsamps=1
    ArrayProperty name=P;interpretation=point;datatype=float32_t[3];arraysize=18000;numsamps=1
    ArrayProperty name=nVertices;interpretation=;datatype=int32_t;arraysize=2000;numsamps=1
    ScalarProperty name=curveBasisAndType;interpretation=;datatype=uint8_t[4];arraysize=4;numsamps=1
    ScalarProperty name=groom_group_id;interpretation=;datatype=int32_t;arraysize=1;numsamps=1
    CompoundProperty name=.arbGeomParams;schema=
      ArrayProperty name=groom_group_id;interpretation=;datatype=int32_t;arraysize=0;numsamps=0
```
