### ISSUE TITLE
Autogenerate does not detect addition of a string Enum member if it is not longer than current members

### ISSUE THREAD

**Issue by dactrungnguyen** [alembic/alembic#338]
Alembic version: 1.5.8
How to reproduce the bug:
Column:
```
state = Column(Enum(enums.RunState, native_enum=False), nullable=False, default=enums.RunState.PENDING)
```
Previous Enum:
```
class RunState(str, Enum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    DONE = 'DONE'
    FAILED = 'FAILED'
```
Bugs: 
* If I add to the Enum `POUF = 'POUF'`, Alembic does NOT detect the change, if I add `POUFPOUFPOUF = 'POUFPOUFPOUF'` instead, Alembic does.
* In the latter case where change is detected, generated migration script does not work : Alembic considers existing type to be VARCHAR(7) without constraint :
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'state',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'POUFPOUF', name='runstate', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###
```
This script, when invoked with `alembic upgrade head`, does not work.
That should be VARCHAR(7) with constraint, i.e. a non-native Enum:
```
def upgrade():
    # manually modified
    op.alter_column('runs', 'state',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='runstate', native_enum=False),
               type_=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'POUFPOUF', name='runstate', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###
This script worked.
```

Expected behavior: Alembic also detects the change in the first case (addition of POUF), and the generated script shoud be correct for both cases.

**Comment by waebbl** [comment]
Seeing the SQL code, this is probably the wrong repository. Did you mean https://github.com/sqlalchemy/alembic?

**Comment by lamiller0** [comment]
Yup, this looks like it should be asked in sqlalechemy

**Comment by dactrungnguyen** [comment]
Yes, of course :sweat_smile: 
How is it possible to have more than 1 project named Alembic! Even if that were the case, how sqlalchemy/alembic could not be the 1st result returned by Google?!
