### ISSUE TITLE
Make the 3 int values in OSubD optional.

### ISSUE THREAD

**Issue by lamiller0** [alembic/alembic#34]
We tried to do this back in 2012, but a weird merge caused it to not make it's way into the main branch.

faceVaryingInterpolateBoundary, faceVaryingPropagateCorners, and interpolateBoundary should only be created and set if it is explicitly set by the users.

ISubD needs to be double checked, but I think it safely treats it as optional there.

**Comment by asuter** [comment]
Yes please. Thanks Lucas.

**Comment by lamiller0** [comment]
See:
https://github.com/alembic/alembic/pull/55
