### ISSUE TITLE
Incorrect linkage with Imath

### ISSUE THREAD

**Issue by waebbl** [alembic/alembic#350]
Building alembic against Imath-3.0.4, with `IMATH_BUILD_BOTH_STATIC_SHARED=ON` and installed shared and static libraries leads to linking with the static library, even with `ALEMBIC_ILMBASE_LINK_STATIC=OFF`. I need to rebuild Imath without support for static libraries to link against the shared libs.

**Comment by lamiller0** [comment]
It appears they have dropped this feature in Imath 3.1 can you confirm if its still an issue?

**Comment by waebbl** [comment]
I haven't created a package yet for v3.1. Going to work on this next week. Because the option has been removed, I don't think this will still be an issue. Gonna tell you, once I have tested the package.
