### ISSUE TITLE
[QUESTION] Running migrations in conftest

### ISSUE THREAD

**Issue by jonatasoli** [alembic/alembic#351]
Hi,

I'm trying to make a project in fastapi and I would like to run all migrations in an asynchronous function in my conftest, is there any way to do this? Or would there be some way to build a fixture sync that does this job?

https://github.com/jonatasoli/fastapi-design-api-example/blob/main/app/conftest.py

I try

```
@pytest.fixture(scope="session", autouse=True)
async def apply_migrations() -> None:
     alembic.config.main(argv=["upgrade", "head"])
     alembic.config.main(argv=["downgrade", "base"])
```

**Comment by lamiller0** [comment]
I think you mean this project:
https://github.com/sqlalchemy/alembic
