### ISSUE TITLE
[Question] Is it possible to use Alembic to migrate to a different database type?

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [alembic/alembic#356]
Hi everyone,

is it possible to use Alembic to migrate a currently existing database to a different database type? I have an Oracle database and would like to recreate all currently existing tables in an empty MariaDB database. The problem is there are several Oracle options/types that don't exist in MariaDB, so when I autogenerate the migration, specifying my MariaDB metadata as target and my Oracle database as source, the models that Alembic generates use Oracle types.

Is there a way to convert between different dialects when autogenerating?

**Comment by Narann** [comment]
This is not the proper repository. Here is the Alembic geometry file format. :)

**Comment by FredericoCoelhoNunes** [comment]
Oops! Sorry @Narann
