### ISSUE TITLE
UB sanitizer report OXform.h:55 load of value 110, not a valid type bool

### ISSUE THREAD

**Issue by wayne-arnold-adsk** [alembic/alembic#357]
Undefined Behaviour Sanitizer report of: OXform.h.  
looks the bool members:   m_useArrayProp and m_isIdentity are not initialized for use in the copy constructor 
 

include/Alembic/Alembic/AbcGeom/OXform.h:55:22: runtime error: load of value 110, which is not a valid value for type 'bool'
    #0 0x7f1ccf77fa3b in Alembic::AbcGeom::v10::OXformSchema::operator=(Alembic::AbcGeom::v10::OXformSchema const&) include/Alembic/Alembic/AbcGeom/OXform.h:55
    #1 0x7f1ccf7848d8 in Alembic::Abc::v10::OSchemaObject<Alembic::AbcGeom::v10::OXformSchema>::OSchemaObject(Alembic::Abc::v10::OObject, std::string const&, Alembic::Abc::v10::Argument const&, Alembic::Abc::v10::Argument const&, Alembic::Abc::v10::Argument const&) include/Alembic/Alembic/Abc/OSchemaObject.h:226
    #2 0x7f1ccf75a487 in MayaTransformWriter::MayaTransformWriter(Alembic::Abc::v10::OObject&, Autodesk::Maya::OpenMaya20220000::MDagPath&, unsigned int, JobArgs const&) /local/S/Maya_master_CI_sanitizer/src/Maya/src/Plugins/AbcExport/MayaTransformWriter.cpp:576

initializing in the header file resolves the report

bool m_useArrayProp{false};
bool m_isIdentity{true};

also should these members be reset in the reset() function

**Comment by lamiller0** [comment]
It's kinda strange that it's complaining about the bools and not m_numChannels or m_numOps.  What sanitizer are you using?

**Comment by lamiller0** [comment]
Also Autodesk signed the CLA many years ago so if you already have a branch ready, feel free to add a Pull Request.

**Comment by wayne-arnold-adsk** [comment]
ok, this is on linux using gcc 9.3.1 (DTS-9.1) sanitizer. doesn't show on Mac using Xcode 12.4 clang sanitizer
I'm assuming that its only the bool type that it would know its not a valid value.   its not complaining explicitly of uninitialized value.  an int could  be anything

**Comment by wayne-arnold-adsk** [comment]
local build with the merged change, sanitizer no longer reporting issue
