### ISSUE TITLE
Compile error in StreamManager.cpp with MSVC

### ISSUE THREAD

**Issue by huelj** [alembic/alembic#358]
https://github.com/alembic/alembic/blob/6bd2242154802da210ccd8adcb1aed3086a92125/lib/Alembic/AbcCoreOgawa/StreamManager.cpp#L46-L81

On Windows I currently have:
`__cplusplus = 201703L` and `_MSC_VER = 1927`
Therefore I do not get `ffsll` defined and get the error `error C3861: 'ffsll': identifier not found`

**Comment by lamiller0** [comment]
Is ffsll still not available at ALL on Windows?  Or is it called something slightly different? 
I've been building on Windows for a while, so I'm confused about why this wouldnt have come up sooner.

**Comment by huelj** [comment]
Well I don't know if I have to include something special in order to make it work, but as is, it doesn't look like it can find it. Would getting the definition out of the defines and defining it in all windows be a valid fix?

``` diff
diff --git a/lib/Alembic/AbcCoreOgawa/StreamManager.cpp b/lib/Alembic/AbcCoreOgawa/StreamManager.cpp
index 9154964d..504128c0 100644
--- a/lib/Alembic/AbcCoreOgawa/StreamManager.cpp
+++ b/lib/Alembic/AbcCoreOgawa/StreamManager.cpp
@@ -48,7 +48,20 @@ namespace ALEMBIC_VERSION_NS {
 // Windows
 #elif defined( _MSC_VER )
 #define COMPARE_EXCHANGE( V, COMP, EXCH ) (InterlockedCompareExchange64( &V, EXCH, COMP ) == COMP)
+#elif defined( __HAIKU__ )
+
+#define COMPARE_EXCHANGE( V, COMP, EXCH ) __atomic_compare_exchange_n( &V, &COMP, EXCH, false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST )
+#include <strings.h>
+int ffsll(long long i)
+{
+	return (__builtin_ffsll(i));
+}
+
+#else
+#error Please contact alembic-discuss@googlegroups.com for support.
+#endif
 
+#if defined( _MSC_VER )
 Alembic::Util::int64_t ffsll( Alembic::Util::int64_t iValue )
 {
     if ( !iValue )
@@ -66,18 +79,6 @@ Alembic::Util::int64_t ffsll( Alembic::Util::int64_t iValue )
 
     return 0;
 }
-
-#elif defined( __HAIKU__ )
-
-#define COMPARE_EXCHANGE( V, COMP, EXCH ) __atomic_compare_exchange_n( &V, &COMP, EXCH, false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST )
-#include <strings.h>
-int ffsll(long long i)
-{
-	return (__builtin_ffsll(i));
-}
-
-#else
-#error Please contact alembic-discuss@googlegroups.com for support.
 #endif
 
 StreamManager::StreamManager( std::size_t iNumStreams )
```

**Comment by lamiller0** [comment]
I did some more research and haven't yet been able to find a fsll implementation on Windows.

Yes that would be a valid fix.

What were the Cmake settings you were using btw?

**Comment by lamiller0** [comment]
When you get a chance please try out master.

**Comment by huelj** [comment]
It's working thanks!
As for my configuration, it's as an external project in cmake, so it uses the main project's compiler/flags settings.
Not sure what is relevant in this more than the values I posted before of `__cplusplus` and `_MSC_VER`

**Comment by lamiller0** [comment]
Ok, thanks for the confirmation.
