### ISSUE TITLE
Recommended version of HDF5

### ISSUE THREAD

**Issue by KelSolaar** [alembic/alembic#360]
Hi,

Looking at the README file, the minimal HDF5 version is [HDF5 (1.8.9) which is 9 years old](https://portal.hdfgroup.org/display/support/HDF5+1.8.9). Is there a know version that is known to work with Alembic? I have seen mentions of 1.10.x in the Google Group but it is a bit unclear if there are recommendations as to which one to pick.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
I can see that USD _recommends_ 1.8.11: https://github.com/PixarAnimationStudios/USD/blob/016b4588140ec939e8dab2e052b8eb9fbf68c3db/VERSIONS.md, so it might make sense to pick that one.

**Comment by lamiller0** [comment]
Hopefully you can just drop support (as it is off by default, many of us haven't used it in a very long time)

**Comment by KelSolaar** [comment]
Thanks this is great to know!
