### ISSUE TITLE
URL Link to Python Binding is broken

### ISSUE THREAD

**Issue by JokerMartini** [alembic/alembic#363]
There is a link on the alembic website here https://code.google.com/archive/p/alembic/ that tells people to go to the python bindings shown here (the link is broken though) http://docs.alembic.io/python

**Comment by lamiller0** [comment]
The link SHOULD be:

http://docs.alembic.io/#python

But since code.google.com is now archived there isn't a way to edit it.

How did you come across:  https://code.google.com/archive/p/alembic/   ???

**Comment by JokerMartini** [comment]
The latest version of Autodesk 3ds Max point to this path > https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/3DSMax-Data-Exchange/files/GUID-D80A02B6-BC7B-4070-A959-94EC5FCA22F8-htm.html
