### ISSUE TITLE
Specify a "version_num" for different schemas?

### ISSUE THREAD

**Issue by LoicH** [alembic/alembic#365]
Is there a way to handle multiple Alembic environments, one for each schema in the same database?

I asked a question on StackOverflow (https://stackoverflow.com/questions/69359861/alembic-put-a-version-num-for-each-schema)

In short, in my team we have multiple projects on the same database, each project has a schema, and we want each project to be able to handle migrations/revisions independently of other projects.

**Comment by lamiller0** [comment]
I think you mean this project:
https://github.com/sqlalchemy/alembic

**Comment by LoicH** [comment]
Oh yeah my bad, sorry!
