### ISSUE TITLE
Swap out auto_ptr for unique_ptr in C++11 (and possibly boost)

### ISSUE THREAD

**Issue by lamiller0** [alembic/alembic#37]
std::auto_ptr is considered deprecated in C++11, we should probably swap in unique_ptr for the small handful of cases where it is used, and typedef auto_ptr to it for the  TR1 case.

**Comment by AWhetter** [comment]
Are there any plans for this to be implemented soon? If not I'd be willing to have a stab at it myself.

**Comment by lamiller0** [comment]
Yes, I plan on addressing this soon.
Is it causing issues on certain compilers?

**Comment by AWhetter** [comment]
Nope I was just interested in it.

**Comment by lamiller0** [comment]
First pass at this is here:
https://github.com/lamiller0/alembic/commit/86fcedb97d1bf35aa292f01ae9b3c85c102b6546

**Comment by numas** [comment]
Fails with ALEMBIC_LIB_USES_BOOST=ON (boost-1.60.0)

Fixed by changing in lib/Alembic/Util/Foundation.h:
`#include <boost/move/unique_ptr.hpp>`
`using boost::movelib::unique_ptr;`

Now fails with std::atomic but that's another issue..

**Comment by lamiller0** [comment]
Ok try: https://github.com/alembic/alembic/commit/a9230743220cdc27dcb80ded99f2ff28c7092833

Looking at some older versions of boost, I got an immediate headache when it came to the availability of unique_ptr, so it falls back on the custom one.  Your atomic issue was also hopefully addressed.

**Comment by numas** [comment]
Yes it compiles now, thank you!
