### ISSUE TITLE
Autogenerate not added import for sqlalchemy_utils columns

### ISSUE THREAD

**Issue by tedivm** [alembic/alembic#374]
I'm using an encrypted column from sqlalchemy_utils. The autogenerate tool creating a new revision uses the appropriate column language in the upgrade/downgrade functions but the script files due to an import error.

The workaround is super trivial- I just have to add the import (`import sqlalchemy_utils`) on the revision script.

**Comment by lamiller0** [comment]
I think you mean this project:
https://github.com/sqlalchemy/alembic
