### ISSUE TITLE
Abc_Archive_Test fails on OpenBSD_current

### ISSUE THREAD

**Issue by dkarama** [alembic/alembic#377]
While updating alembic from 1.8.2 to 1.8.3 on OpenBSD_current I came across a single test failure, the significance of this is unknown to me. I tried exporting and importing models in blender with no problem so far. Let me know how I can help in resolving this.

Test project /usr/ports/pobj/alembic-1.8.3/build-amd64
    Start 25: Abc_Archive_TEST
1/1 Test #25: Abc_Archive_TEST .................Subprocess aborted***Exception:   0.01 sec
libc++abi: terminating with uncaught exception of type std::runtime_error: ERROR: Failed Test in File: /usr/ports/pobj/alembic-1.8.3/alembic-1.8.3/lib/Alembic/Abc/Tests/ArchiveTest.cpp Line: 99

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec

The following tests FAILED:
         25 - Abc_Archive_TEST (Subprocess aborted)
Errors while running CTest

**Comment by lamiller0** [comment]
What value is archive.getArchiveVersion() returning?  Is it a total nonsensical value?

A guess is that maybe an older version of Alembic is being picked up when building the tests?

What does your CMake look like?

**Comment by dkarama** [comment]
You no doubt guessed right. Removing the older version of alembic solves the issue. Thank you.
