### ISSUE TITLE
Maya Cannot show abc and the normal of test cube in blender is wrong 

### ISSUE THREAD

**Issue by ziyeshanwai** [alembic/alembic#378]
I compiled the code in windows 7 and successed. Afiter i run AbcGeom_PolyMeshTest.exe , i get meshOptPropTest.abc. Import the abc ifle to maya, maya cannot show the content. Import the abc to blender, blender can show the content

**Comment by lamiller0** [comment]
Maya has an issue with meshes that do not have transforms above them, which is likely why its not loading into Maya properly.

**Comment by ziyeshanwai** [comment]
@lamiller0 thanx. I import meshOptPropTest.abc to blender 2.92, the normal of the cube is wrong, is it the blender problem?
![error_normal](https://user-images.githubusercontent.com/11570825/156686412-919f498f-15c3-4f65-b995-e03e1d21d7ef.png)

**Comment by lamiller0** [comment]
Since this cube is meant more to be a unit test to make sure reading and writing of an OPolyMeshSchema is working correctly, it's possible that the normals are set in a way that will look weird.

The values written to the file are here:
https://github.com/alembic/alembic/blob/master/lib/Alembic/AbcGeom/Tests/MeshData.cpp#L104

**Comment by meshula** [comment]
Alembic faces are right-handed CCW, IIRC. Is it possible they did show up in Maya but showed up as if they were CW and therefore inside out? In that case, "Flip Normals" could fix it. I had a peek at MeshData.c, but haven't got enough mental-geometry-juice this morning to work out the winding this morning ;) If someone remembers, maybe it could be documented in the code.

**Comment by lamiller0** [comment]
A friendly reminder until everyone's caffeine kicks in:
https://github.com/alembic/alembic/wiki/Alembic-Conventions-and-Schema-Types

**Comment by meshula** [comment]
Clockwise, thanks :) It's afternoon now, I'm two cups in. My comment about documentation was specifically about adding a comment to the cube code in the sample, since you mentioned you weren't sure if it was well formed or not.

**Comment by ziyeshanwai** [comment]
@lamiller0 @meshula thanx, the link is useful!
