### ISSUE TITLE
What's the current state of Imath 3 compatibility?

### ISSUE THREAD

**Issue by meshula** [alembic/alembic#380]
Hello, I was wondering what the current state of Imath 3 compatibility is? I can see a lot of work has already gone into compatibility, wasn't sure if it's officially supported yet?

**Comment by lamiller0** [comment]
Yes, its been officially supported in 1.8.0+  We look forward to the day when we can drop support for IlmBase and Imath 2.

**Comment by dgovil** [comment]
Thanks Lucas. Nick had asked after some questions I was asking in the EXR chats, as I was updating some old build scripts on our end that used pre-imath 3 setup.

I managed to get a build going with the following setup if that helps anyone else looking at this.

```
cmake
<Source Root>
-DUSE_BINARIES=ON
-DUSE_TESTS=OFF
-DUSE_HDF5=OFF
-DUSE_PYALEMBIC=ON
-DCMAKE_MACOSX_RPATH=ON
-DImath_ROOT=<Directory with lib/cmake/Imath/ImathConfig.cmake>
-DCMAKE_INSTALL_PREFIX=<Install location>
-DBOOST_ROOT=<Root for Boost>
-DBoost_NO_BOOST_CMAKE=ON
-DCMAKE_OSX_ARCHITECTURES="arm64"
-DPython3_ROOT_DIR=<Python version root>
-DPYALEMBIC_PYTHON_MAJOR=3
-DALEMBIC_PYTHON_INSTALL_DIR=<Install location>/lib/python
```

**Comment by meshula** [comment]
Awesome on both accounts! Thanks :)
