### ISSUE TITLE
Default alembic env.py reconfigures all logging

### ISSUE THREAD

**Issue by awgr** [alembic/alembic#381]
When running alembic from within another application, the default generated env.py will replace the application's existing logging configuration with the one defined in alembic.ini.

I could imagine this tripping up some users who want to run alembic from another application wrapper, as part of a build or deploy process.

It seems like alembic could be changed slightly to be aware of whether (a) it is running as a standalone application, or (b) from within another application, and that it could (by default) skip configuring logging if it is run as part of another application.

Alternatively, I can go bother logging to provide a way to merge-insert logging configuration, which Alembic could then use, so it doesn't matter how Alembic is run.

**Comment by lamiller0** [comment]
Do you mean for this project?

https://github.com/sqlalchemy/alembic

**Comment by awgr** [comment]
Yes
