### ISSUE TITLE
How to build this lib -> Alembic in Windows??

### ISSUE THREAD

**Issue by southeast2017** [alembic/alembic#383]
I want to build Alembic in Windows，But I'm failed. Who succeed?Please tell me the way to build Alembic? Thanks!!!!

**Comment by lamiller0** [comment]
Did you build Imath 3 first?

I've had success with this:

cmake -DUSE_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 15 2017 Win64"  -DImath_ROOT=C:\Users\Lucas\Github_build\install64\Imath -DCMAKE_INSTALL_PREFIX=C:\Users\Lucas\Github_build\install64 -DCMAKE_BUILD_TYPE=Debug C:\Users\Lucas\Github\source\alembic

cmake --build . --config Debug

**Comment by southeast2017** [comment]
Thank you! I successfully build Alembic Lib！
