### ISSUE TITLE
Question：Data about Curve

### ISSUE THREAD

**Issue by southeast2017** [alembic/alembic#384]
Curves
The AbcGeom Curves class has these properties:

P - vertices
nVertices - for each curve the number of vertices in the curve
Pw (optional) - the position weight for each point, if this doesn't exist, assume 1 per point.
knots (optional)
orders (if type is variable order) - the order of each curve

I have many elements such as P, nVertices, Pw, knots, orders, etc. If I want to draw a curve, can I only use P and nVertices, not use “nurbs equation” to calculate real point? I don't know if this is the right way. Who can help me? Thanks!

**Comment by lamiller0** [comment]
The curves may not always be Nurbs curves, they could have several different basis as seen here:
https://github.com/alembic/alembic/blob/master/lib/Alembic/AbcGeom/Basis.h#L48

Depending on your application, it might be acceptable to just draw the curves as simple line segments, if so then using just P (or Pw) is okay.  If you need those curves to look perfect then you might need to handle several different curve equations.

**Comment by southeast2017** [comment]
Got it! Thank you very much!
