### ISSUE TITLE
LINK 2019 Windows：When I use Alembic Lib in visual studio

### ISSUE THREAD

**Issue by southeast2017** [alembic/alembic#385]
First：
LNK2019： "public: void __cdecl Alembic::Abc::v12::ErrorHandler::operator()(class stdext::exception &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??RErrorHandler@v12@Abc@Alembic@@QEAAXAEAVexception@stdext@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，FUNCTION： "public: void __cdecl Alembic::Abc::v12::ErrorHandler::Context::operator()(class stdext::exception &)" (??RContext@ErrorHandler@v12@Abc@Alembic@@QEAAXAEAVexception@stdext@@@Z) 

In Alembic Lib，I saw the symbol is @ErrorHandler@v12@Abc@Alembic@@QEAAXAEAVexception@std@@@Z，but I don't know why and how to solve it?

Second：
LNK2019： "__declspec(dllimport) public: unsigned short __cdecl Imath_3_1::half::bits(void)const " (__imp_?bits@half@Imath_3_1@@QEBAGXZ)，FUNCTION："void __cdecl Alembic::AbcCoreOgawa::v12::ConvertData<signed char,class Imath_3_1::half>(char *,void *,unsigned __int64)" (??$ConvertData@CVhalf@Imath_3_1@@@v12@AbcCoreOgawa@Alembic@@YAXPEADPEAX_K@Z) 
Any one know how to solve it?Thanks

**Comment by lamiller0** [comment]
Are you getting this when building the library, or in an external project that is trying to use Alembic?

**Comment by southeast2017** [comment]
an external project that is trying to use Alembic. I build the Alembic Library successfully. But when I use Alembic in an external project, the visual studio 2019 report this error! I don't know what cause this! I copy other Alembic Library(Alembic Lib version 1.8.3 in Blender) using for an external project, then everything is ok! So I don't know weather the Alembic I build something wrong?

**Comment by southeast2017** [comment]
I build Alembic 1.8.3 is Static Library. Imath Library also static library, version 3.1.3 or 3.1.8

**Comment by southeast2017** [comment]
I solved the second problem.Emm, I delete the Imath Library, then I rebuild the Imath Library(also static Library), then the second problem is solved. I think I build the Imath first which is a shared lib, so cause this problem. The first Problem is not solved until now.I modify some almebic header file to avoid this problem.
