### ISSUE TITLE
Can't build with -DUSE_PYALEMBIC=ON

### ISSUE THREAD

**Issue by Korotsu** [alembic/alembic#386]
Hello, when I try to build the alembic module with cmake (with cygwin terminal) I get this error:

![image](https://user-images.githubusercontent.com/48487579/178805983-b05fb8a0-48d5-4203-8011-40ff73814117.png)

I first think that a miss the component python39 from boost library. But the package didn't exist at all.

Did I have to manually create my version of the boost for python 3.9 lib ?
Any help would be appriciated. Thanks

**Comment by Korotsu** [comment]
I join the output log and the command:  cmake -DUSE_PYALEMBIC=ON -DUSE_STATIC_BOOST=ON -DDOCS_PATH=ON -DCMAKE_INSTALL_PREFIX=./build_folder ../alembic
[CMakeOutput.log](https://github.com/alembic/alembic/files/9105000/CMakeOutput.log)

**Comment by lamiller0** [comment]
Did you build PyImath with python 3.9 bindings?

**Comment by lamiller0** [comment]
Thats the wrong Imath library the one you need is from here:

https://github.com/AcademySoftwareFoundation/Imath

**Comment by Korotsu** [comment]
After more investigation i found that the problem comes from :
![image](https://user-images.githubusercontent.com/48487579/179532790-d3e50139-bd48-40af-a5ac-3378f5118ed1.png)

**Comment by Korotsu** [comment]
i already build Imath with python 3.9 and -BPYTHON=ON for python bindings

**Comment by Korotsu** [comment]
Install is fine, but does alembic need a precise version of Imath/PyImath or python ?

**Comment by Korotsu** [comment]
Yeah, i finally and successfully build the program, the problem comes from me, I used -BPYTHON=ON instead of -DPYTHON=ON.... sorry for the inconvenience. And thanks for your help and time ^^
