### ISSUE TITLE
Need  Basic samples  for Alembic

### ISSUE THREAD

**Issue by uncleRX** [alembic/alembic#387]
Hey. I am a newbee for this.
I want to create a software by using Opengl to show Alembic mesh and Animation
 in Almebic example , i can't get useful infomation , 
i need parse .abc file then  use  graphic api  draw animation scene.
what should I do,  appreciate every one!

**Comment by lamiller0** [comment]
Try this:

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/alembic/Alembic_Octopus_Example.tgz

**Comment by uncleRX** [comment]
Thank you for taking the time to reply, i can't Rely on "maya" or AbcExport , just alembic/lib/Alembic API, i wan't use alembic in custom render engine, and show primitive and texture,  like  "maya app" import .abc file , like "cinema 4d" open .abc file. Can I do this?

**Comment by lamiller0** [comment]
Yes you can do this.

Here are some older examples that might help you:

Reading and converting in OpenGL:
https://github.com/alembic/abcview/tree/master/lib/AbcOpenGL

Old Arnold example:
https://github.com/alembic/alembic/tree/master/arnold/Procedural

Old Prman example:
https://github.com/alembic/alembic/tree/master/prman/Procedural
