### ISSUE TITLE
Too many sections / Files too bigs

### ISSUE THREAD

**Issue by Korotsu** [alembic/alembic#388]
Hello again,

Sorry I'm a big noob with CMake, using Cygwin how can I add the /bigobj or -big-obj option for the CMake --build command ?
I get this error when trying to CMake --build alembic files (in the build directory after the classic cmake command).

![image](https://user-images.githubusercontent.com/48487579/179561413-2d7b937f-fa64-42be-a60f-fdc507cfd034.png)

**Comment by Korotsu** [comment]
Fixed by adding -DCMAKE_C_FLAGS='-Wa,-mbig-obj'
-DCMAKE_CXX_FLAGS='-Wa,-mbig-obj' to the first cmake command.

Tips: to increase the compilation speed for cmake --build  .  Check your available thread on your computer and use -j="your_number_of_threads" without quote symbol.

**Comment by Korotsu** [comment]
Edit: the program still crash at 99% when joining thread.

**Comment by lamiller0** [comment]
CMake crashed?  I've successfully used Visual Studio community edition to compile this and I  suspect CMake may add /bigobj automatically when compiling.

**Comment by Andrej730** [comment]
Met the same issue. Was building the project with `cmake .. -DUSE_PYALEMBIC=ON` and compiling with `msbuild .\INSTALL.vcxproj`. What helped is to explicitly add `/bigobj` to `CMAKE_CXX_FLAGS`: `cmake .. -DUSE_PYALEMBIC=ON -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj"`.

Not sure if it can be considered package cmake issue.
