### ISSUE TITLE
Cannot create ISampleSelector by the sample index in PyAlembic

### ISSUE THREAD

**Issue by geesecross** [alembic/alembic#392]
In PyAlembic, I can't create `ISampleSelector` by the sample index (which is corresponded to [this C++ constructor](https://github.com/alembic/alembic/blob/1.8.3/lib/Alembic/Abc/ISampleSelector.h#L63)). The first argument is always interpreted as sample time (`chrono_t`), not the index (`index_t`).

How to reproduce
---
In Maya 2022 (and PyAlembic 1.7.5), I ran the following code:
```python
from alembic.Abc import ISampleSelector

s = ISampleSelector(int(10))
print(s.getRequestedIndex())
print(s.getRequestedTime())

s = ISampleSelector(float(10))
print(s.getRequestedIndex())
print(s.getRequestedTime())
```
and I expected the following result (expecting the former will call [`index_t`==`int64` constructor](https://github.com/alembic/alembic/blob/1.8.3/lib/Alembic/Abc/ISampleSelector.h#L63) and the latter will call [`chrono_t`==`double` constructor](https://github.com/alembic/alembic/blob/1.8.3/lib/Alembic/Abc/ISampleSelector.h#L68)):
```
10
0.0
-1
10.0
```
But the actual result was:
```
-1
10.0
-1
10.0
```
I have confirmed this result in PyAlembic v1.7.5 of Maya 2022 and v1.8.2 of [Gohlke's unofficial x64 windows build](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyalembic).

**Comment by lamiller0** [comment]
We provide args to help eliminate ANY confusion: 

`alembic.Abc.ISampleSelector(requestedIndex=10)`

`alembic.Abc.ISampleSelector(requestedTime=10)`

**Comment by lamiller0** [comment]
`print(alembic.Abc.ISampleSelector.__init__.__doc__)`

__init__( (object)arg1, (int)requestedIndex) -> None :
    Create an ISampleSelector with the given requested index

__init__( (object)arg1, (float)requestedTime [, (TimeIndexType)requestedIndexType ]) -> None :
    Create an ISampleSelector with the given requested time and  the optional request index type

__init__( (object)arg1) -> None :
    Create an ISampleSelector with the requested index value of 0 and the requested index type of kNearIndex

**Comment by geesecross** [comment]
Oh, I never expected that keyword arguments work in python bindings! Thanks, @lamiller0.
