### ISSUE TITLE
Failed build on windows:  Target "xxx" links to target "Imath::Imath" but the target was not  found.

### ISSUE THREAD

**Issue by scratchapixel** [alembic/alembic#395]
I have been trying to build Alembic from scratch on a windows 10 terminal (GitBash).

- I first cloned, build and successfully installed Imath (in G;/imath).
- I then cloned Alembic using the following command:
```
  cmake -DImath_DIR="/path/to/Imath/config" .
```
But the all targets fail with this message:

```
    CMake Error at lib/Alembic/CMakeLists.txt:51 (ADD_LIBRARY):
    Target "Alembic" links to target "Imath::Imath" but the target was not
    found.  Perhaps a find_package() call is missing for an IMPORTED target, or
    an ALIAS target is missing?
```
Obviously it doesn't know where to find `imath`. I tried using ALEMBIC_ILMBBASE_LIB_DIR  ALEMBIC_ILMBASE_INCLUDE_DIRECTORY etc. but didn't have any luck. Any help would be very useful as I currently have no idea how to fix the issue and move forward. Thanks a lot for your suggestions.

Edit: this is what I see before I get the error messages. So it seems to find Imath. Hence my confusion.

```
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- CMAKE SYSTEM NAME: Windows
Defaulting CMAKE_CXX_STANDARD to 14
-- The install dir is C:/Program Files (x86)/Alembic
-- Found package Imath
-- Skipping AbcConvert: it requires USE_HDF5

   * Alembic Configuration              ===
   * USE_ARNOLD                         OFF
   * USE_BINARIES                       ON
   * USE_EXAMPLES                       OFF
   * USE_HDF5                           OFF
   * USE_MAYA                           OFF
   * USE_PRMAN                          OFF
   * USE_PYALEMBIC                      OFF
   * USE_STATIC_BOOST                   OFF
   * USE_STATIC_HDF5                    OFF
   * USE_TESTS                          ON
   * ALEMBIC_ILMBASE_LINK_STATIC        OFF
   * ALEMBIC_SHARED_LIBS                ON
   * ALEMBIC_DEBUG_WARNINGS_AS_ERRORS   ON
   * PYALEMBIC_PYTHON_MAJOR             3
   * DOCS_PATH                          OFF
```

**Comment by lamiller0** [comment]
If you are using Imath3  try setting Imath_ROOT,  try: -DImath_ROOT="G:/imath"

**Comment by scratchapixel** [comment]
Thank you so much for your help. This is good to know but as you asked me whether I was using Imath3, I looked into the install directory to check the version of the DLL and noticed that the cmake config files were there(. So I have been pointing to the wrong ones all along.

```
 cmake -DImath_DIR="G:/Imath/lib/cmake/Imath"  .
```

This worked for me. Again thank you for the swift reply and for somehow helping me find what I was doing wrong. Cheers.

**Comment by z199416** [comment]
Have you solved your problem? I have encountered the same problem as you.  Could you please advise me on how to solve it later

**Comment by scratchapixel** [comment]
Sadly I forget to document the solution precisely, but I believe the main issue was that I wasn’t pointing  to the right config files.

cmake -DImath_DIR=“D:/Imath/lib/cmake/Imath" -DCMAKE_INSTALL_PREFIX="D:/Alembic" .

You need the config files that are in the build directory not in the source directory (and I was pointing to those in the source directory). So not sure this will solve your problem, but this is what the problem was at the time I think.

So install imath to whatever location you want (no problem installing Imath for what I remember), and then be sure to set the path of your config files to that installed Imath location when you are about to set Alembic cmake options.

**Comment by z199416** [comment]
![Code_giEWZWLxyA](https://user-images.githubusercontent.com/62418217/236594698-345f609b-775c-493e-8454-a8e3ada6f7e5.png)
I set Imath_ ROOT,Imath_ DIR,CMAKE_ INSTALL_ PREFIX in the CMakeList file. But there are still issues

**Comment by z199416** [comment]
I solved this problem，thank you
