### ISSUE TITLE
1.8.4: -Wunused compile error

### ISSUE THREAD

**Issue by huelj** [alembic/alembic#398]
Updating to the new version causes compile errors with 
```
lib/Alembic/AbcCoreOgawa/Tests/fuzzTest.cpp:666:52: error: unused variable 'it' [-Werror,-Wunused-variable]
        ABCA::MetaData::token_map_type::const_iterator it = md.begin();
                                                       ^
    1 error generated.
```
https://github.com/alembic/alembic/blame/1.8.4/lib/Alembic/AbcCoreOgawa/Tests/fuzzTest.cpp#L666

and 

```
python/PyAlembic/PyIScalarProperty.cpp:68:43: error: unused typedef 'U' [-Werror,-Wunused-local-typedef]
        typedef typename TPTraits::value_type U;
                                              ^
    1 error generated.

```
https://github.com/alembic/alembic/blame/1.8.4/python/PyAlembic/PyIScalarProperty.cpp#L68

Though this one doesn't have recent modifications near it, I assume it's because now there are warnings as errors enabled in debug.

**Comment by lamiller0** [comment]
What compiler are you using? 
I'm aware of a bunch of other warnings as well that I've been working on here:
https://github.com/lamiller0/alembic/tree/gcc9_warning_cleanup

This flag was added in 1.8.4 to turn this off:
-DALEMBIC_DEBUG_WARNINGS_AS_ERRORS=OFF

**Comment by huelj** [comment]
Hi, this is on MacOS using Clang 14.0.0.
Thanks!

**Comment by SimonBoorer** [comment]
I'm having the same issue on Ubuntu with Clang 9.0.1 and MacOS with Clang 11.0.0.

**Comment by lamiller0** [comment]
I think the latest master fixes all these warning and it will go out in the next release.  Please reopen if you find another one.
