### ISSUE TITLE
CentOS 7 and ilmbase (as shipped) supported ?

### ISSUE THREAD

**Issue by nyue** [alembic/alembic#399]
I have been able to build Alembic 1.8.4 (non-shared)

I have deployed it and tested out the executable, all is well.

However, when I tried to use it to build other applications, I come across the following cmake error and wasn't sure where to aim my troubleshooting.

I use Alembic_DIR to get the package but there is a find_dependency(IlmBase) that is breaking but I just used IlmBase to build Alembic to begin with so I am puzzled.

```
-- Detecting CXX compile features - done
CMake Error at /home/nyue/systems/cmake/cmake-3.24.1-linux-x86_64/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindImath.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Imath", but
  CMake did not find one.

  Could not find a package configuration file provided by "Imath" with any of
  the following names:

    ImathConfig.cmake
    imath-config.cmake

  Add the installation prefix of "Imath" to CMAKE_PREFIX_PATH or set
  "Imath_DIR" to a directory containing one of the above files.  If "Imath"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/nyue/systems9/alembic/1.8.4-centos/lib/cmake/Alembic/AlembicConfig.cmake:30 (find_dependency)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by lamiller0** [comment]
Do you need to use Ilmbase or can you use Imath 3+?

**Comment by nyue** [comment]
I did build and deployed one with Imath 3+ but I am exploring if I can reduce a dependency and stick with what is currently shipping with CentOS 7

I will go with Imath 3+, looks like it will make life easier going forward.

Thank you @lamiller0

**Comment by lamiller0** [comment]
I dont recall if the version CentOS 7 uses shipped with Cmake files for IlmBase, that may have happened just before 3 to make compatibility slightly easier.
