### ISSUE TITLE
Use of deprecated IObject( AbcA::ObjectReaderPtr iPtr, WrapExistingFlag...) in IObject.cpp

### ISSUE THREAD

**Issue by scratchapixel** [alembic/alembic#402]
Wanted to point out in case you look to clean the code that lib/Alembic/Abc/IObject.cpp is using 

```
 return IObject( m_object->getParent(),
                        kWrapExisting,
                        getErrorHandlerPolicy() );
```

(#255) which is indicated as deprecated in lib/Alembic/Abc/IObject.h (#99)

**Comment by lamiller0** [comment]
Thanks for flagging this.

**Comment by lamiller0** [comment]
This has been merge into master and will go into the next release.
