### ISSUE TITLE
AbcTree.cpp  Xcode 14.3 warning as error encountered

### ISSUE THREAD

**Issue by wayne-arnold-adsk** [alembic/alembic#412]
using Xcode 14.3 on Ventura, when building for debug, encounter warning as error

`bin/AbcTree/AbcTree.cpp:310:12: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]
        size_t count = 0;
               ^
    1 error generated.`

removing the variable count and it single line of ++count later in the function resolves the issue

**Comment by lamiller0** [comment]
This has been merge into master and will go into the next release.
