### ISSUE TITLE
  Target "Alembic" links to:   Imath::Imath    but the target was not found

### ISSUE THREAD

**Issue by z199416** [alembic/alembic#419]
![cmake-gui_dwsiNXajTW](https://user-images.githubusercontent.com/62418217/236417888-407b80ee-61bc-4a49-a721-744e6ac535f1.png)

How to solve it?

**Comment by lamiller0** [comment]
It looks like you are pointing at the build for Imath:

d:/gogs/alembic/third_party/Imath/build/config

Where did you end up installing it to, you need to set Imath_DIR to THAT.

**Comment by z199416** [comment]
I want to install to D:/gogs/alembic,But shouldn't  Imath_DIR be specified in a directory with ImathConfig.cmake. in?

**Comment by z199416** [comment]
set(CMAKE_INSTALL_PREFIX "D:/gogs/alembic")
set(Imath_ROOT "D:/gogs/alembic/third_party/Imath")
set(Imath_DIR  "D:/gogs/alembic/third_party/Imath/build/config")

I set Imath_ ROOT,Imath_ DIR,CMAKE_ INSTALL_ PREFIX in the CMakeList file.

**Comment by lamiller0** [comment]
Double checking the Cmake command I use to build Alembic on Windows:

-DImath_ROOT=C:\Users\Lucas\Documents\GitHub\build\install64\Imath -DCMAKE_INSTALL_PREFIX=C:\Users\Lucas\Documents\GitHub\build\install64

My directory for C:\Users\Lucas\Documents\GitHub\build\install64\Imath  has bin, lib and include in it.

ImathConfig.cmake happens to be in:

C:\Users\Lucas\Documents\GitHub\build\install64\Imath\lib\cmake\Imath

**Comment by z199416** [comment]
![Code_8TG9cddAnV](https://user-images.githubusercontent.com/62418217/236598884-05ef993f-657b-4108-a1f1-c32dda9e2d1f.png)
This is my Imath CMakeList file,


After compiling imath, there is no 'Imath/lib/cmake/Imath' in my install folder,why?Is there an error compiling imath?

![Code_hW8M80Rpzm](https://user-images.githubusercontent.com/62418217/236599009-40582ab3-e9db-4d46-8a5c-a3bdac49e766.png)

This is my Alembic CMakeList file,

**Comment by z199416** [comment]
I think I've already solved it，Thanks
