### ISSUE TITLE
How to read a property value which is a char array?

### ISSUE THREAD

**Issue by DKGH** [alembic/alembic#421]
My property is of type Abc::IArrayProperty.

I tried `property.get` and `property.getAs` as shown below. But it didn't work:

`get`:
```
Abc::ArraySamplePtr dataPtr;
property.get(dataPtr);
```

`getAs`:
```
Alembic::Util::Dimensions dimensions;
property.getDimension(dimensions);
std::vector<int8_t> dataVector(dimensions[0]);
property.getAs(&dataVector);
```

Please advise.

**Comment by lamiller0** [comment]
Do you have an example Alembic file I can take a look at to verify that the property you are trying to get data out of IS a char array?

What happened when you used getAs, did it crash?   When you used get were you REALLY using an Abc::ArraySamplePtr?

**Comment by DKGH** [comment]
The output of `property.getDataType()` is `int8_t`. Which, I think is char array. But I haven't been able to read any other arrays (even int32) as well.

Thanks for the correction about ArraySamplePtr. I edited it in the original post. However, that is still throwing memory exception with `get`.

**Comment by DKGH** [comment]
Accidentally closed it. But it is still a problem.

**Comment by lamiller0** [comment]
Is this example from the test suite helpful?
https://github.com/alembic/alembic/blob/master/lib/Alembic/Abc/Tests/ArrayPropertyTest.cpp#L192

**Comment by DKGH** [comment]
Thanks, but it didn't help. The error text I am getting is `Read invalid. No filter defined for compressed data`.

**Comment by lamiller0** [comment]
Is your data written out as HDF5?

**Comment by DKGH** [comment]
The core type received by using `IFactory.getArchive` is `Ogawa`. Opening the file in a binary reader also shows `Ogawa` as the first few letters. Could it still have HDF5 compression?

**Comment by DKGH** [comment]
Unfortunately I am not able to share the archive file. I believe the archive was written using an older version on Alembic. The corresponding imath dll is of version 2.5. Is this message there in an older version of Alembic?

BTW, how do compile imath to get Iex and Half dlls? All I see now is imath.dll.

**Comment by lamiller0** [comment]
With Imath 3 there is only imath.dll, it's no longer split out into several libraries.

**Comment by DKGH** [comment]
Which version of Alembic was compatible with Imath 2.5. Will attempt to compile with that.

**Comment by lamiller0** [comment]
The latest version is still compatible with Imath 2, you just may have to set some extra CMake args.

**Comment by DKGH** [comment]
I found out that the archive was written with Alembic 1.8.0. But there is no error text like that in that version too.

The thing is that the software creating the archive comes with an Alembic.dll. If I let that dll load during runtime (by controlling the environment variables), I am at least able to run abctree.exe to see parts of the file. However, I use the Alembic.dll that I compiled (even version 1.8.0 with IMath v2.5), all abctree shows is `ABC` in green. What's different about my Alembic.dll which fails to read any children?

**Comment by lamiller0** [comment]
Does the dependency walker or dumpbin show any interesting dependency differences between your compiles Alembic.dll and the one that came with the mystery software?

**Comment by DKGH** [comment]
I will compare the assemblies in a while. That is interesting. In the meantime, I can read all scalar data with the mystery dll. I can also read array dimensions (`getDimensions`) and point (`getPtr`). Can I use `getPtr` in some way to access the data directly. I tried the below but it didn't work (`dimensions[0]` has the number of elements in the array):

```
const auto& propPtr = property.getPtr();
std::vector<int8_t> data(dimensions[0]);
memcpy(&data.front(), &propPtr, dimensions[0]);
for(const int8_t& charData : data)
{
  std::cout <<  charData << " ";
}
```

It's producing some arbitrary values.

**Comment by lamiller0** [comment]
No, you can't use the property pointer as thats just a shared AbcCoreOgawa::ArrayProperty pointer, instead you have to get the sample to get the data out of it.

Here is an example of casting the data from that array sample ptr into something usable.

https://github.com/alembic/alembic/blob/master/lib/Alembic/AbcCoreOgawa/Tests/ArrayPropertyTests.cpp#L240

**Comment by DKGH** [comment]
Thanks for the sharing the link. However, when I modified the code as below, I got the same error as before ('`Read invalid. No filter defined for compressed data`'):

```
Alembic::AbcCoreAbstract::ArraySamplePtr samplePtr;
property.getPtr()->getSample(0, samplePtr);
```

Although, when I change `getSample(0, samplePtr)` to `getSample(1, samplePtr)`, the error changes to `Invalid sample index: 1, should be between 0 and 0`. This means I have the right index.

Is there any way to define a filter on array data? Could the file be actually HDF or HDF like with Ogawa headers?

**Comment by lamiller0** [comment]
There isn't a way to define a filter on array data and you can't mix HDF and Ogawa like that which makes me very curious what your mysterious Alembic.dll is doing.

**Comment by DKGH** [comment]
Before doing a assembly comparison, I am trying to read it using PyAlembic. Please point me to an example of navigating an archive using PyAlembic in python.

**Comment by lamiller0** [comment]
Does this help? (or any of the other test example in that directory)

https://github.com/alembic/alembic/blob/master/python/PyAlembic/Tests/testPolyMesh.py

**Comment by DKGH** [comment]
I see that IArchive( 'polyMesh1.abc' ).getTop() can get me the top object. But how do traverse the archive or access a child node?

**Comment by lamiller0** [comment]
import alembic

def walk(parent):
    for child in parent.children:
        print(child.getFullName())
        walk(child)

archive = alembic.Abc.IArchive(FILENAME)
walk(archive.getTop())

**Comment by DKGH** [comment]
How do I ensure that it appears in my DLL?

**Comment by lamiller0** [comment]
Are you compiling it from scratch?

**Comment by DKGH** [comment]
[AlembicExports.txt](https://github.com/alembic/alembic/files/11828729/AlembicExports.txt)
Yes. From 1.8.0. Please see exports attached from lucasg Dependencies.

**Comment by DKGH** [comment]
[AlembicConfig.txt](https://github.com/alembic/alembic/files/11828755/AlembicConfig.txt)
[AlembicConfigVersion.txt](https://github.com/alembic/alembic/files/11828756/AlembicConfigVersion.txt)
[AlembicTargets.txt](https://github.com/alembic/alembic/files/11828757/AlembicTargets.txt)
[AlembicTargets-release.txt](https://github.com/alembic/alembic/files/11828758/AlembicTargets-release.txt)
Also sharing my cmake files. I am using VS 2022 with Win x64. All these files may be renamed from *.txt to *.cmake.

**Comment by lamiller0** [comment]
I'm not seeing anything obviously wrong.

In AlembicExports.txt the reason you arent seeing ArImpl etc is because those parts arent part of the public interfadce, just stuff like AbcCoreOgawa::ReadArchive and AbcCoreOgawa:WriteArchive which are the entry points.

**Comment by DKGH** [comment]
It is clear that this ability to read is not an issue with this code base.
