### ISSUE TITLE
Converting from Ogawa to HDF5

### ISSUE THREAD

**Issue by DKGH** [alembic/alembic#423]
I obtained an archive `Abc::IArchive` by using `IFactory.getArchive`. This is an Ogawa archive as suggested by it's core type. How do write it back as an HDF archive?

**Comment by lamiller0** [comment]
Although I wouldnt normally recommend this as Ogawa is much faster and smaller, you can use the abcconvert utility that is usually built with Alembic.  This assumes you've built in HDF support into the library.

https://github.com/alembic/alembic/blob/master/bin/AbcConvert/AbcConvert.cpp
