### ISSUE TITLE
"alembic revision --autogenerate" does not detect an existing index on a JSONB column field

### ISSUE THREAD

**Issue by BartlomiejSkwira** [alembic/alembic#428]
Let's say I have a table definition (created using SqlAlchemy Core):
```python
some_table = Table(
    "some_table",
    metadata,
    Column("jsonb_column", JSONB, nullable=True),
    Index(
        "ix_some_table_jsonb_column",
        text("(jsonb_column->>'user_id')"),
    ),
)
```
We have a table with a JSONB column and an index on user_id inside the JSONB column.

When I run `alembic revision --autogenerate` the 1st time it generates a migration:
```python
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import PostgreSQL

op.create_table(
        "some_table",
        sa.Column(
            "jsonb_column", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
 op.create_index(
        "ix_some_table_jsonb_column",
        "some_table",
        [sa.text("(jsonb_column->>'user_id')")],
        unique=False,
    )
    
```
This migration is fine. Migrating with `alembic upgrade head` results with a new table with an index:
![image](https://github.com/alembic/alembic/assets/136439009/dfb52827-26da-4ecc-a30f-f9c91fecd1a3)

![image](https://github.com/alembic/alembic/assets/136439009/09d882f3-9484-4331-bf1d-c4903bdf026f)

But when I run `alembic revision --autogenerate` 2nd time, it will create 2nd migration:
```python


def upgrade():
    op.drop_index("ix_some_table_jsonb_column", table_name="some_table")
    op.create_index(
        "ix_some_table_jsonb_column",
        "some_table",
        [sa.text("(jsonb_column->>'user_id')")],
        unique=False,
    )


def downgrade():
    op.drop_index("ix_some_table_jsonb_column", table_name="some_table")
    op.create_index(
        "ix_some_table_jsonb_column",
        "some_table",
        [sa.text("(jsonb_column ->> 'user_id'::text)")],
        unique=False,
    )
```
This is unexpected, the database should be up to date and should not need a new migration with a new index. Maybe the `::text` is the culprit of this diff? 

I can see in the logs:

> INFO  [alembic.autogenerate.compare] Detected changed index 'ix_some_table_jsonb_column' on 'some_table': expression ('INDEX', "jsonb_column ->> 'user_id'") to ('INDEX', "jsonb_column->>'user_id'")

So it detects a change that is not a change. If I run `alembic revision --autogenerate` again, it will create 3rd migration - same as the 2nd one. 

Seems that autogenerate is not detecting the index for a JSONB column field.

[edit] Or maybe my index definition is wrong?

Versions:
- Alembic: 1.11.2 
- SqlAlchemy: 2.0.19
- psycopg2: 2.9.6
- Postgres: 11

**Comment by BartlomiejSkwira** [comment]
This looks like an issue with SqlAlchemy >=2.0, on 1.4.49 this works but raises a warning: 
```
/usr/local/lib/python3.11/site-packages/alembic/ddl/impl.py:685: UserWarning: autogenerate skipping metadata-specified expression-based index 'ix_some_table_ jsonb_column'; dialect 'postgresql' under SQLAlchemy 1.4.49 can't reflect these indexes so they can't be compared
```

**Comment by BartlomiejSkwira** [comment]
I was able to work around this by ignoring autogenerate on the index:
```python
Index(
        "ix_some_table_jsonb_column",
        text("(jsonb_column->>'user_id')"),
        info={"skip_autogenerated": True},
    ),
```
In `alembic/env.py` file
```python
def include_object(object, name, type_, reflected, compare_to):
    """
    This is a workaround for https://github.com/alembic/alembic/issues/428
    Alembic would keep on creating a new migration for an index that already existed
    (index name: ix_session_version_owner_user_id)
    """
    if (
        type_ == "index"
        and not reflected
        and object.info.get("skip_autogenerate", False)
    ):
        return False
    else:
        return True
        
    # somewhere below, make sure you add it in `run_migrations_online`

    context.configure(
           ..
            include_object=include_object,
        )
```

**Comment by lamiller0** [comment]
Wrong project please try:  https://github.com/sqlalchemy/alembic
