### ISSUE TITLE
Allow explicitly setting the install prefix

### ISSUE THREAD

**Issue by chadrik** [alembic/alembic#44]
There are two cmake defines to set the install prefix:  `ALEMBIC_INSTALL_PREFIX` and `CMAKE_INSTALL_PREFIX`.  Unfortunately, both of these append `alembic-${VERSION}`, which is annoying when you have a build management system like rez that expects things installed a certain way. 

```cmake
IF (DEFINED ENV{ALEMBIC_INSTALL_PREFIX})
    SET( CMAKE_INSTALL_PREFIX
        $ENV{ALEMBIC_INSTALL_PREFIX}/alembic-${VERSION})
ELSE()
    SET(ORIGINAL_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
    SET(CMAKE_INSTALL_PREFIX
        ${ORIGINAL_INSTALL_PREFIX}/alembic-${VERSION})
ENDIF()
```

Since you're in the middle of a build refactor that breaks compatibility with old build scripts anyway, I propose getting rid of the suffix altogether and just use the `CMAKE_INSTALL_PREFIX` as provided.  If you think that people really love this feature, then just choose one to apply the suffix to.

Thanks!

**Comment by rsgalloway** [comment]
This was fixed by #46, closing.
