### ISSUE TITLE
Typo in PyAlembic ObjectVisibility enum

### ISSUE THREAD

**Issue by ugai** [alembic/alembic#440]
`python/PyAlembic/PyVisibility.cpp`

```cpp
    enum_<AbcG::ObjectVisibility>( "ObjectVisibility" )
        .value( "kVisibilityDeferred", AbcG::kVisibilityDeferred )
        .value( "kVisibilityHidden", AbcG::kVisibilityHidden )
        .value( "kkVisibilityVisible", AbcG::kVisibilityVisible )
        ;
```

I think the `kkVisibilityVisible` is a typo.

However, I think it will be difficult to fix it immediately. This is probably because many existing user scripts cause runtime exceptions. I don't know the best solution to this problem, but I would like to suggest some mitigations.

- Add `DeprecationWarning` somehow and fix it the appropriate time.
- Add "This enum has a typo..." to the documentation. For the cognitive loads.

I don't think it's necessarily something that should be fixed, but consider this at least once.

**Comment by lamiller0** [comment]
Yeah, its definitely a typo.
We can introduce the appropriate named one, but leave the typo.

**Comment by lamiller0** [comment]
This was added in Alembic 1.8.7
