### ISSUE TITLE
sqlalehbmcy_utils is not defined... but it is though

### ISSUE THREAD

**Issue by ZackPlauche** [alembic/alembic#442]
I'm working on an SQLAlchemy backend project. I have a JSONType from sqlalchemy_utils. It's installed in my venv. My code works everywhere else...

sqlalchemy_utils is not appearing in the migrations file as an import for some reason.

Please tell me how to fix this.

**Comment by lamiller0** [comment]
Wrong project please try: https://github.com/sqlalchemy/alembic
