### ISSUE TITLE
MigrationContext.stamp() does not work with SQLAlchemy 2.0

### ISSUE THREAD

**Issue by mwerezak** [alembic/alembic#445]
After upgrading to SQLAlchemy 2.0, the [MigrationContext.stamp()](https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.migration.MigrationContext.stamp) method no longer works. No table is created.

If I revert back to 1.4 the method works as normal.

**Comment by lamiller0** [comment]
Wrong project please try: https://github.com/sqlalchemy/alembic
