### ISSUE TITLE
CMake Error at python/PyAlembic/CMakeLists.txt:158 (TARGET_LINK_LIBRARIES)

### ISSUE THREAD

**Issue by suekieza** [alembic/alembic#447]
Hey there,

I'm running into an issue with imath when building pyalembic, I've tried https://groups.google.com/g/alembic-discussion/c/SVO3PEpzQvk, but it did not work for me.

Sys: Windows 11
Alembic: 1.8.6
Openexr: 3.1.11
Boost:1.78
zlib:1.2.13

![image (16)](https://github.com/alembic/alembic/assets/53234220/7e831f23-aecd-4f4b-aed8-7c038df2e271)

my build command look like the following:
'-DUSE_BINARIES=OFF', 
'-DUSE_TESTS=OFF'
'-DUSE_HDF5=OFF',
'-DUSE_PYALEMBIC=ON',
'-DPYALEMBIC_PYTHON_MAJOR=3'
My build log:
[log.txt](https://github.com/alembic/alembic/files/14653179/log.txt)

**Comment by lamiller0** [comment]
Thanks for the screen shots!

Did you build PyImath bindings or were they included with your OpenEXR version if you did not build it yourself?  I don't see anything in your ImathTargets-release.cmake  with libPyImath with that name.

**Comment by suekieza** [comment]
hey there, I build openEXR with Imath but maybe its incorrect heres a screen grab of what's in the openEXR folder for Imath:
 ![image](https://github.com/alembic/alembic/assets/53234220/6395804b-c92d-4ce6-b045-02f1c6c3a47d)

 I tried building against the newer version of openEXR 3.2.2 still no luck I'm afraid. My open EXR build commands are:
                  '-DOPENEXR_INSTALL_PKG_CONFIG=ON',
                  '-DOPENEXR_BUILD_TOOLS=ON',
                  '_DOPENEXR_BUILD_EXAMPLES=ON',
                  '-DOPENEXR_BUILD_PYTHON=ON',
                  '-DOPENEXR_INSTALL_TOOLS=ON',
                  '-DOPENEXR_INSTALL_EXAMPLES=ON',
                  '-DOPENEXR_FORCE_INTERNAL_IMATH=ON',
                  '-DBUILD_TESTING=OFF'

 thanks for the help

**Comment by lamiller0** [comment]
It might be that you are building the OpenEXR python bindings here but NOT the Imath one.  I dont see anything in your screenshots though that indicates you've got working OpenEXR python bindings. (or the PyImath ones)

**Comment by suekieza** [comment]
Hey hey, you are correct I was not building Imath with its python bindings turned on I added:
 [                '-DOPENEXR_INSTALL_PKG_CONFIG=ON',
                  '-DOPENEXR_BUILD_TOOLS=ON',
                  '-DOPENEXR_BUILD_LIBS=ON',
                  '_DOPENEXR_BUILD_EXAMPLES=ON',
                  '-DOPENEXR_BUILD_PYTHON=ON',
                  '-DOPENEXR_INSTALL_LIBS=ON',
                  '-DOPENEXR_INSTALL_TOOLS=ON',
                  '-DOPENEXR_INSTALL_EXAMPLES=ON',
                  '-DOPENEXR_FORCE_INTERNAL_IMATH=ON',
                  **'-DPYTHON=ON',
                  '-DPYBIND11=ON',**
                  '-DBUILD_TESTING=OFF'
]

Too my OpenEXR build and now it works. Thanks so much for all your help.
