### ISSUE TITLE
Feature request: support Feature Branch / Release pattern.

### ISSUE THREAD

**Issue by couling** [alembic/alembic#452]
We use alembic for all of our migrations. And this has worked well for most things.

One thing that is a little awkward is the difference between alembic versions generated for feature branches (usually merged swiftly) and released versions of the data-model which we then apply to various environments. _Just because we merged it in doesn't mean we want it released just yet._

What would be really useful, would be a standardised way to group versions into named releases.

------

What I'm looking for is a way to keep the simplicity of generating a new version with each PR, while also having "versions" (releases) that match a pythonic numbering convention ([PEP 440](https://peps.python.org/pep-0440/)). Each release can contain multiple versions (who's IDs can remain randomised).

This is semi-possible at the moment by generating versions with a PEP 440 number prior to releasing.

--------

This would help with a few things:
 - a new version specifier of `latest` (or pick a better name), to upgrade to the latest _**released**_ version, reducing the the risk of accidentally deploying an un-released version to a live environment.
 - It would allow upgrading or downgrading to named versions that directly match versions released through internal pypi repos.
 - Where databases support transactional DDL (postgresql), commit points can be on named releases instead of versions.
 - It could add a few safety checks for release:
   - ensure there are no dangling (unreleased) versions on release
   - ensure all heads for each release are merged
 - It could allow grouping versions into directories which better align with release order. For larger / older projects this can be really useful to hide the complexity of 50+ versions sorted in a randomised order. 

The structural change to `versions/` would be very simple. Instead of a monolithic directory of versions, the `versions/` directory could contain a directory per release. One additional directory `versions/head` could then contain any pre-release versions.

**Comment by lamiller0** [comment]
Wrong project please try: https://github.com/sqlalchemy/alembic

**Comment by couling** [comment]
ooops. really sorry!
