### ISSUE TITLE
Regarding HDF5-1.10.0

### ISSUE THREAD

**Issue by numas** [alembic/alembic#61]
This is just a question if Alembic will support building with HDF5-1.10.0, as Arch Linux has updated to this version. From the HDF site:

> Due to the requirements of some of the new features, the format of a 1.10.x HDF5 file is likely to be different from that of a 1.8.x HDF5 file. This means that tools and applications built to read 1.10.x files will be able to read a 1.8.x file, but tools built to read 1.8.x files may not be able to read a 1.10.x file.

I guess the "may" here, is if tools use the new features of HDF5? I understand it if Alembic stays with the requirement of HDF5-1.8.x (and that HDF5 is already somewhat legacy), just curious if it is possible to use 1.10.x or if Arch should keep the old version around for this reason.

FYI, the build error is:
`alembic/lib/Alembic/AbcCoreHDF5/HDF5Util.cpp: In function 'Alembic::AbcCoreHDF5::v7::H5Node Alembic::AbcCoreHDF5::v7::OpenGroup(Alembic::AbcCoreHDF5::v7::H5Node&, const string&)':
/home/san/src/blender-deps/alembic/lib/Alembic/AbcCoreHDF5/HDF5Util.cpp:234:51: error: cannot convert 'hobj_ref_t* {aka long unsigned int*}' to 'H5R_type_t' for argument '3' to 'hid_t H5Rdereference2(hid_t, hid_t, H5R_type_t, const void*)'`

**Comment by lamiller0** [comment]
In 1.6 you can optionally leave off HDF5 support.

Supporting 1.10.0 could be troublesome for the reasons you mentioned, we would consider it of course, if it provided a huge over Ogawa.

**Comment by numas** [comment]
Alright, so HDF5 is actually not needed?

**Comment by numas** [comment]
So, I found this: https://www.hdfgroup.org/HDF5/doc/RM/APICompatMacros.html
I'm just not sure yet how and where to apply it... 

**Note:** This is not to use 1.10 functionality, but just to be able to build using this new version.

**Comment by lamiller0** [comment]
Looks like you can configure 1.10 to behave like 1.8 when building it?
-with-default-api-version=v18 ?

**Comment by numas** [comment]
Hi lamiller0,

Yes I figured it out, but not with that line (as it affects those who wants to use the new features). There's an option to compile an app with a specific api version. I'll just post it here since it's one line in CMakeLists.txt:

`219 # HDF5`
`220 IF (USE_HDF5)`
`221     FIND_PACKAGE(ZLIB REQUIRED)`
`222     SET(ALEMBIC_WITH_HDF5 "1")`
`223     INCLUDE("./cmake/AlembicHDF5.cmake")`
`224     INCLUDE_DIRECTORIES(${HDF5_INCLUDE_DIRS})`
**`225     SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DH5_USE_18_API")`**
`226 ENDIF()`

I tested it with HDF5 1.8.9 - 1.8.15 - 1.10.0 and Alembic builds and works with HDF5 archives. Hope it is ok to be added to 1.6.

**Comment by lamiller0** [comment]
Yes, this should be ok to add to 1.6

**Comment by numas** [comment]
Hmprh... I've been getting suspecious crashes with Alembic files (both Ogawa and HDF5), and after digging I found this in the release notes for 1.10.0 and 1.8.16:

      The thread-safety + high-level library combination has been marked
      as "unsupported" in the Autotools

      The global lock used by the thread-safety feature has never been
      raised to the high-level library level, making it possible that
      the library state could change if a context switch were to occur in
      a high-level library call. Because of this, the combination of
      thread-safety and high-level library is officially unsupported by
      The HDF Group.

      In the past, although this combination has never been supported, this
      was not enforced by the build systems. These changes will cause an
      Autotools configure step to fail if --enable-threadsafe and
      --enable-hl are combined unless additional options are specified.

That option is _--enable-unsupported_. As I'm learning, Alembic need both. I am not qualified to understand the above statement, but it builds and I don't get crashes anymore. Hope I can convince the package maintainers to use that option...

**Comment by lamiller0** [comment]
We've noticed the importance of --enable-threadsafe as well.
I can look into the feasibility of avoiding hdf_hl, so we don't have to worry about enabling the unsupported build option.

**Comment by numas** [comment]
I wish I knew what hdf_hl does/affects, but thank you for looking into this and for your patience!

**Comment by numas** [comment]
Wow, when I started this issue I had no idea it would lead to this. Turns out there _is_ a difference in file format, where a 1.10.0 file can't open in tools using 1.8.x. I found the fix though, from here:
https://www.hdfgroup.org/HDF5/doc/RM/H5P/H5Pset_libver_bounds.htm

Changing 'lib/Alembic/AbcCoreHDF5/AwImpl.cpp' line 70 to this:

`70     H5Pset_libver_bounds( faid, H5F_LIBVER_EARLIEST, H5F_LIBVER_LATEST );`

and Alembic files using 1.10.0 are now forward-compatible. This should not have a negative effect on files created using 1.8.x. I tested with Blender and Houdini Apprentice.

Hopefully this is the last issue when using Alembic with HDF5-1.10.0. Does it make sense to do a pull request with these two items (CMakeList + AwImpl.cpp)?

**Comment by lamiller0** [comment]
I'll try to tackle all 3 of the issues in an upcoming pull request.

**Comment by lamiller0** [comment]
I've addressed all 3 in the latest 1.6 branch.

**Comment by numas** [comment]
Nice! Thank you for spending time on this.
