### ISSUE TITLE
Python Alembic Build Error: undefined symbol: OArchive 

### ISSUE THREAD

**Issue by Jingjung** [alembic/alembic#88]
hello

I am new in Alembic I want to build Alembic for Python
finally i have alembicmodule.so but it cannot use
I try this in python
>>> from ctypes import cdll
>>> mydll = cdll.LoadLibrary('/tmp/alembicDownload/buildfiletest/source4/alembic-1.5.8/lib/alembicmodule.so')
>>> oarch = mydll.OArchive('path.../.../file.abc')

so i have error like this
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 366, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 371, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /tmp/alembicDownload/buildfiletest/source4/alembic-1.5.8/lib/alembicmodule.so: undefined symbol: OArchive

i check my alembicmodule.so file I try

>>> ldd /path/.../alembicmodule.so

result show my .so file link to every .so file like this

        linux-vdso.so.1 =>  (0x00007fff767ff000)                                                    
        libPyIex.so.2 => /tmp/alembicDownload/buildfiletest/pyilmbase/lib/libPyIex.so.2 (0x00007f48b51ea000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f48b4fb6000)                                                  
        libImath-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libImath-2_2.so.12 (0x00007f48b4d99000)
        libHalf.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libHalf.so.12 (0x00007f48b4b56000)          
        libIexMath-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libIexMath-2_2.so.12 (0x00007f48b4952000)
        libIlmThread-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libIlmThread-2_2.so.12 (0x00007f48b4748000)
        libIex-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libIex-2_2.so.12 (0x00007f48b451d000)            
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f48b4300000)                                                      
        libboost_python.so.1.55.0 => /tmp/alembicDownload/buildfiletest/boost/lib/libboost_python.so.1.55.0 (0x00007f48b40af000)
        libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007f48b3d08000)                                              
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f48b3a02000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f48b377e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f48b33e9000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f48b31d3000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003e8f200000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f48b2fcf000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f48b2dcb000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f48b2bc3000)

I use
Alembic 1_05_08
boost 1.55
HDF5 1.8.9
ilmbase 2.2
pyilmbase 2.2

Thank you `:)

**Comment by rsgalloway** [comment]
Hi  Jingjung, it's a bit unclear from your report if you're using Windows or Linux. From the pathing I suspect it's Linux, but you are also using cdll to import your alembicmodule.so file, why is that?

It looks like a linking issue, your alembicmodule.so file is not linking to the libAlembicf files as expected, which could explain the missing symbol error.

Can you please try building with the latest release, 1.6.1?

https://github.com/alembic/alembic/releases/tag/1.6.1

**Comment by Jingjung** [comment]
Thank rsgalloway, finally i can link my alembicmodule.so
i use a command 'ld -shared /path/.../alembicmodule.so' 
when i try in python again i can import alembic!!  :)
