### ISSUE TITLE
Maya's alembic menu disappeared when AbcExport.mll and AbcImport.mll were updated

### ISSUE THREAD

**Issue by dnx4015** [alembic/alembic#91]
After building the 1.6.1 AbcExport and AbcImport plugins for Maya (2016) in Windows 7, I replaced the built-in plugin version (1.5.4). The problem is the alembic Cache menu has dissapeared [Cache > Alembic Cache].
I looked around and found that there is a alembic.pyd file in the Python directory that comes with Maya. When I executed 
``import alembic.Abc``
``print alembic.Abc.GetLibraryVersion()``
I got ``1.5.4`` as a response. Now I am building the python module of alembic to figure out whether replacing this file helps.
Do you know if my approach is valid? Is this a known issue?

**Comment by lamiller0** [comment]
Per the alembic-discuss comment:

"AlembicCreateUI.mel appears to be imported directly in main.cpp in the
Maya devkit version of the plugin."

That menu is provided by Autodesk and adding similiar code will reenable it.
