### ISSUE TITLE
Maya Alembic doesn't support film roll attribute

### ISSUE THREAD

**Issue by BigRoy** [alembic/alembic#92]
# Problem

It seems that the Maya plug-in does not support an (animated) film roll attribute. No keys are coming along and it seems to do nothing at all. The source code does mention "roll" in a comment though:
https://github.com/alembic/alembic/blob/master/maya/AbcImport/CameraHelper.cpp#L209

I was wondering whether this is supposed to be working or is left out for particular reasons? It could just be missing because the Alembic Camera does not support this feature.

The main thing confusing me was that particular comment about "film roll" which made me think it would take it along.

**Comment by lamiller0** [comment]
Checking AbcExport:

https://github.com/alembic/alembic/blob/master/maya/AbcExport/MayaCameraWriter.cpp#L208

It looks like we weren't sure how film roll fits into the film back matrix, so it is skipped on purpose.

**Comment by BigRoy** [comment]
Ha, I like how extremely clear that comment was. Seems I exactly missed that one. Thanks for pointing it out.

Since it's been previously investigated (so it seems) and dismissed at the time shall I close this issue and assume it won't be implemented?

**Comment by lamiller0** [comment]
Sure!
If you have a proposed solution feel free to submit a pull request for it.
